In [1]:
import os

# Include modules from path
import sys
sys.path.append(os.path.join("/home/mdafifal.mamun/research/S3M/src"))

:

In [14]:
import matplotlib.pyplot as plt
import torch
from sentence_transformers import (
    SentenceTransformer,
    SentenceTransformerModelCardData,
    SentenceTransformerTrainer,
    SentenceTransformerTrainingArguments,
)
from sentence_transformers.evaluation import (
    EmbeddingSimilarityEvaluator,
    TripletEvaluator,
)
from sentence_transformers.losses import MultipleNegativesRankingLoss
from sentence_transformers.training_args import BatchSamplers
from sklearn.manifold import TSNE
from tqdm import tqdm

from data.buckets.bucket_data import BucketData, OtherBucketData
from data.buckets.issues_data import BucketDataset
from data.triplet_selector import RandomTripletSelector
from datasets import Dataset
from preprocess.entry_coders import Stack2Seq, Stack2SeqMultiStack
from preprocess.seq_coder import SeqCoder, SeqCoderMulti
from preprocess.tokenizers import SimpleTokenizer

In [2]:
# def format_stack(stack):
#     return stack


# def get_data_row(coder, event, similar_stack_id, dissimilar_stack_id):
#     return {
#         "anchor": format_stack(coder(event.st_id, transformer=True)),
#         "positive": format_stack(coder(similar_stack_id, transformer=True)),
#         "negative": format_stack(coder(dissimilar_stack_id, transformer=True)),
#         "ids": [event.st_id, similar_stack_id, dissimilar_stack_id],
#     }

In [3]:
from data.formatters import get_formatter
from

In [15]:
triplet_selector_train = RandomTripletSelector(1)
triplet_selector_eval = RandomTripletSelector(1)
print("Load bucket data...")
bucket_data = OtherBucketData(
    "eclipse",
    "/home/mdafifal.mamun/research/S3M/dataset/EMSE_data/eclipse_2018/eclipse_stacktraces.json",
    3850,
    700,
    350,
    140,
)
bucket_data.load()
stack_loader = bucket_data.stack_loader()
data_gen = BucketDataset(bucket_data)
unsup_stacks = data_gen.train_stacks()

data_gen.reset()

stack2seq = Stack2SeqMultiStack(cased=False, trim_len=0, sep=".")

coder = SeqCoderMulti(
    stack_loader, stack2seq, SimpleTokenizer(), min_freq=0, max_len=None
)

# coder.fit(unsup_stacks)

Load bucket data...
Stack loader:  json_loader_multi

In [34]:
train_data = []
test_data = []
all_data = []
formatter = get_formatter("java")

print("Generate the dataset...")
for i, event in tqdm(enumerate(data_gen.train()), desc="Step"):
    similar_stack_ids, dissimilar_stack_ids = triplet_selector_train(event)
    for similar_stack_id, dissimilar_stack_id in zip(
        similar_stack_ids, dissimilar_stack_ids
    ):
        coded = coder(event.st_id, transformer=True)
        train_data.append(
            {
                "anchor": coder(event.st_id, transformer=True),
                "positive": coder(similar_stack_id, transformer=True),
                "negative": coder(dissimilar_stack_id, transformer=True),
                "ids": [event.st_id, similar_stack_id, dissimilar_stack_id],
            }
        )
        all_data.extend(coded)
        all_data.extend(coder(similar_stack_id, transformer=True))
        all_data.extend(coder(dissimilar_stack_id, transformer=True))

Generate the dataset...

Step: 0it [00:00, ?it/s]

Step: 5180it [01:05, 78.98it/s]

In [44]:
frame_data = []

for frame_list in all_data:
    # Only keep unique frames
    frame_list = list(set(frame_list))
    frame_data.extend(frame_list)

In [26]:
from pprint import pprint

In [29]:
ctr = 0

for d in train_data:
    if len(d["negative"]) > 1:
        ctr+=1
        pprint(d["anchor"])
        print("----------------")
        pprint(d["positive"])
        break
print(ctr)
print("Frequency: ", ctr/len(train_data))

[['org.eclipse.core.launcher.main.main',
  'org.eclipse.core.launcher.main.run',
  'org.eclipse.core.launcher.main.basicrun',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.boot.bootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.getrunnable',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.internal.runtime.internalplatform.loadergetrunnable',
  'org.eclipse.core.internal.plugins.configurationelement.createexecutableextension',
  'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
  'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
  'java.lang.class.newinstance',
  'java.lang.class.newinstance',
  'java.lang.classloader.loadclassinternal',
  'java.lang.classloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.findclassprerequisites',
  'org.eclipse.core.internal.boot.delegatingurlclassloaderdelegateloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.access',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.plugins.pluginclassloader.findclassparentsself',
  'org.eclipse.core.internal.plugins.pluginclassloader.activateplugin',
  'org.eclipse.core.internal.plugins.plugindescriptor.dopluginactivation',
  'org.eclipse.core.internal.plugins.plugindescriptor.internaldopluginactivation',
  'org.eclipse.core.internal.runtime.internalplatform.run',
  'org.eclipse.core.internal.plugins.plugindescriptor.run',
  'org.eclipse.core.resources.resourcesplugin.startup',
  'org.eclipse.core.internal.resources.workspace.open',
  'org.eclipse.core.internal.resources.localmetaarea.readworkspace',
  'org.eclipse.core.internal.resources.modelobjectreader.read',
  'org.eclipse.core.internal.resources.modelobjectreader.read',
  'javax.xml.parsers.documentbuilderfactory.newinstance',
  'java.lang.classcastexception'],
 ['org.eclipse.core.launcher.main.main',
  'org.eclipse.core.launcher.main.run',
  'org.eclipse.core.launcher.main.basicrun',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.boot.bootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.getrunnable',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.internal.runtime.internalplatform.loadergetrunnable',
  'org.eclipse.core.internal.plugins.configurationelement.createexecutableextension',
  'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
  'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
  'java.lang.class.newinstance',
  'java.lang.class.newinstance',
  'java.lang.classloader.loadclassinternal',
  'java.lang.classloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.findclassprerequisites',
  'org.eclipse.core.internal.boot.delegatingurlclassloaderdelegateloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.access',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.plugins.pluginclassloader.findclassparentsself',
  'org.eclipse.core.internal.plugins.pluginclassloader.activateplugin',
  'org.eclipse.core.internal.plugins.plugindescriptor.dopluginactivation',
  'org.eclipse.core.internal.plugins.plugindescriptor.internaldopluginactivation',
  'org.eclipse.core.internal.boot.delegatingloaderexception'],
 ['org.eclipse.core.launcher.main.main',
  'org.eclipse.core.launcher.main.run',
  'org.eclipse.core.launcher.main.basicrun',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.boot.bootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.run',
  'java.lang.reflect.invocationtargetexception']]
----------------
[['org.eclipse.core.launcher.main.main',
  'org.eclipse.core.launcher.main.run',
  'org.eclipse.core.launcher.main.basicrun',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.boot.bootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.getrunnable',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.internal.runtime.internalplatform.loadergetrunnable',
  'org.eclipse.core.internal.plugins.configurationelement.createexecutableextension',
  'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
  'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
  'java.lang.class.newinstance',
  'java.lang.class.newinstance',
  'java.lang.classloader.loadclassinternal',
  'java.lang.classloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.findclassprerequisites',
  'org.eclipse.core.internal.boot.delegatingurlclassloaderdelegateloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.access',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.plugins.pluginclassloader.findclassparentsself',
  'org.eclipse.core.internal.plugins.pluginclassloader.activateplugin',
  'org.eclipse.core.internal.plugins.plugindescriptor.dopluginactivation',
  'org.eclipse.core.internal.plugins.plugindescriptor.internaldopluginactivation',
  'org.eclipse.core.internal.runtime.internalplatform.run',
  'org.eclipse.core.internal.plugins.plugindescriptor.run',
  'org.eclipse.core.resources.resourcesplugin.startup',
  'org.eclipse.core.internal.resources.workspace.open',
  'org.eclipse.core.internal.resources.localmetaarea.readworkspace',
  'org.eclipse.core.internal.resources.modelobjectreader.read',
  'org.eclipse.core.internal.resources.modelobjectreader.read',
  'javax.xml.parsers.documentbuilderfactory.newinstance',
  'java.lang.classcastexception'],
 ['org.eclipse.core.launcher.main.main',
  'org.eclipse.core.launcher.main.run',
  'org.eclipse.core.launcher.main.basicrun',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.boot.bootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.getrunnable',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.internal.runtime.internalplatform.loadergetrunnable',
  'org.eclipse.core.internal.plugins.configurationelement.createexecutableextension',
  'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
  'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
  'java.lang.class.newinstance',
  'java.lang.class.newinstance',
  'java.lang.classloader.loadclassinternal',
  'java.lang.classloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.findclassprerequisites',
  'org.eclipse.core.internal.boot.delegatingurlclassloaderdelegateloader.loadclass',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.access',
  'org.eclipse.core.internal.boot.delegatingurlclassloader.loadclass',
  'org.eclipse.core.internal.plugins.pluginclassloader.findclassparentsself',
  'org.eclipse.core.internal.plugins.pluginclassloader.activateplugin',
  'org.eclipse.core.internal.plugins.plugindescriptor.dopluginactivation',
  'org.eclipse.core.internal.plugins.plugindescriptor.internaldopluginactivation',
  'org.eclipse.core.internal.boot.delegatingloaderexception'],
 ['org.eclipse.core.launcher.main.main',
  'org.eclipse.core.launcher.main.run',
  'org.eclipse.core.launcher.main.basicrun',
  'java.lang.reflect.method.invoke',
  'org.eclipse.core.boot.bootloader.run',
  'org.eclipse.core.internal.boot.internalbootloader.run',
  'java.lang.reflect.invocationtargetexception']]
1
Frequency:  0.0002032520325203252

In [45]:
from collections import Counter
import pandas as pd

# Step 1: Calculate Frequency of Each Frame
frame_counts = Counter(frame_data)

# Step 2: Convert to DataFrame for Easier Analysis
df = pd.DataFrame(frame_counts.items(), columns=["Frame", "Frequency"])

# Step 3: Add Percentage of Total
total_frames = len(train_data) * 3  # Total frames in the dataset
df["Percentage"] = (df["Frequency"] / total_frames) * 100

# Step 4: Sort by Frequency (Descending)
df = df.sort_values(by="Frequency", ascending=False).reset_index(drop=True)

# Step 5: Identify Common Frames (Threshold-Based)
# Adjust the threshold as needed (e.g., frames appearing in >20% of stack traces)
threshold = 20  # Percentage threshold for identifying common frames
common_frames = df[df["Percentage"] > threshold]

# Display Results
print("Top Frequent Frames:")
print(df.head(10))  # Top 10 frames by frequency

print("\nCommon Frames (Above Threshold):")
print(common_frames)

# Save Results to CSV for Further Inspection
df.to_csv("frame_analysis.csv", index=False)
common_frames.to_csv("common_frames.csv", index=False)

Top Frequent Frames:
                                               Frame  Frequency  Percentage
0                    java.lang.reflect.method.invoke      12172   82.466125
1    sun.reflect.delegatingmethodaccessorimpl.invoke      11323   76.714092
2        sun.reflect.nativemethodaccessorimpl.invoke      11255   76.253388
3    org.eclipse.swt.widgets.display.readanddispatch       9966   67.520325
4  org.eclipse.core.runtime.adaptor.eclipsestarte...       9593   64.993225
5     org.eclipse.ui.internal.workbench.runeventloop       9195   62.296748
6  org.eclipse.ui.internal.workbench.createandrun...       8455   57.283198
7    org.eclipse.ui.platformui.createandrunworkbench       8449   57.242547
8            org.eclipse.ui.internal.workbench.runui       8070   54.674797
9       org.eclipse.swt.widgets.eventtable.sendevent       7562   51.233062

Common Frames (Above Threshold):
                                                Frame  Frequency  Percentage
0                     java.lang.reflect.method.invoke      12172   82.466125
1     sun.reflect.delegatingmethodaccessorimpl.invoke      11323   76.714092
2         sun.reflect.nativemethodaccessorimpl.invoke      11255   76.253388
3     org.eclipse.swt.widgets.display.readanddispatch       9966   67.520325
4   org.eclipse.core.runtime.adaptor.eclipsestarte...       9593   64.993225
5      org.eclipse.ui.internal.workbench.runeventloop       9195   62.296748
6   org.eclipse.ui.internal.workbench.createandrun...       8455   57.283198
7     org.eclipse.ui.platformui.createandrunworkbench       8449   57.242547
8             org.eclipse.ui.internal.workbench.runui       8070   54.674797
9        org.eclipse.swt.widgets.eventtable.sendevent       7562   51.233062
10                org.eclipse.core.launcher.main.main       7551   51.158537
11                 org.eclipse.core.launcher.main.run       7469   50.602981
12            org.eclipse.core.launcher.main.basicrun       7460   50.542005
13           org.eclipse.swt.widgets.widget.sendevent       7389   50.060976
14                     java.lang.nullpointerexception       6552   44.390244
15              org.eclipse.ui.internal.workbench.run       6441   43.638211
16          org.eclipse.core.internal.jobs.worker.run       5692   38.563686
17  org.eclipse.core.runtime.internal.adaptor.ecli...       5536   37.506775
18  org.eclipse.core.runtime.internal.adaptor.ecli...       5510   37.330623
19  org.eclipse.swt.widgets.display.rundeferredevents       5330   36.111111
20  org.eclipse.core.internal.runtime.platformacti...       4833   32.743902
21     org.eclipse.ui.internal.ide.ideapplication.run       4727   32.025745
22         org.eclipse.equinox.launcher.main.basicrun       4384   29.701897
23  org.eclipse.equinox.launcher.main.invokeframework       4384   29.701897
24              org.eclipse.equinox.launcher.main.run       4377   29.654472
25  org.eclipse.equinox.internal.app.eclipseapphan...       4234   28.685637
26     org.eclipse.swt.custom.busyindicator.showwhile       4234   28.685637
27           org.eclipse.ui.internal.workbench.access       4199   28.448509
28              org.eclipse.core.runtime.platform.run       4153   28.136856
29  org.eclipse.core.databinding.observable.realm....       3829   25.941734
30  org.eclipse.ui.internal.ide.application.ideapp...       3763   25.494580
31  org.eclipse.swt.widgets.synchronizer.runasyncm...       3227   21.863144
32  org.eclipse.swt.widgets.typedlistener.handleevent       3223   21.836043
33   org.eclipse.swt.widgets.display.runasyncmessages       3113   21.090786
34            org.eclipse.core.runtime.saferunner.run       3033   20.548780
35  org.eclipse.core.internal.runtime.internalplat...       2971   20.128726

In [82]:
frame_freq = {}

In [83]:
from pprint import pprint
# Find frame frequency from the training data
def x():
    
    for row in train_data:
        for stack in ["anchor", "positive", "negative"]:
            for frame in row[stack]:
                # if frame == "org.eclipse.swt.widgets.display.readanddispatch":
                #     pprint(row)
                #     return
                if frame not in frame_freq:
                    frame_freq[frame] = 0
                frame_freq[frame] += 1

x()

In [84]:
# Sort by frequency
frame_freq = dict(sorted(frame_freq.items(), key=lambda item: item[1], reverse=True))

In [85]:
# List frames that occurred more than 2000 times and save in a list
frames = []
for frame, freq in frame_freq.items():
    if freq > 1000:
        print(frame, freq)
        frames.append(frame)

java.awt.component.dispatchevent 10401
java.awt.container.dispatcheventimpl 10400
java.awt.eventqueue.dispatchevent 9394
java.awt.eventdispatchthread.pumpeventsforhierarchy 8513
java.awt.eventdispatchthread.pumpevents 8010
java.awt.eventdispatchthread.run 7970
org.netbeans.api.java.classpath.classpath.getclasspath 7733
org.netbeans.modules.web.freeform.webmodules.findclasspath 7683
org.netbeans.modules.java.project.projectclasspathprovider.findclasspath 7679
org.netbeans.modules.java.freeform.lookupmergerimplclasspathproviderimpl.findclasspath 7677
org.netbeans.modules.web.freeform.webmodulesffwebmodule.findclasspath 7674
java.awt.component.dispatcheventimpl 6192
java.awt.eventdispatchthread.pumponeeventforhierarchy 6175
org.openide.util.requestprocessorprocessor.run 5764
org.openide.util.requestprocessortask.run 5742
java.awt.window.dispatcheventimpl 5213
java.awt.component.processevent 5034
java.awt.container.processevent 5015
java.awt.lightweightdispatcher.dispatchevent 4224
java.awt.lightweightdispatcher.retargetmouseevent 4176
java.awt.event.invocationevent.dispatch 4126
java.awt.lightweightdispatcher.processmouseevent 4099
java.awt.component.processmouseevent 3996
javax.swing.jcomponent.paint 3983
org.netbeans.api.java.classpath.classpath.entries 3611
org.netbeans.modules.java.jseplatform.platformdefinition.defaultclasspathprovidercompileclasspathimpl.getresources 3578
javax.swing.jcomponent.paintchildren 3381
javax.swing.jcomponent.processmouseevent 2841
java.awt.eventdispatchthread.pumponeeventforfilters 2813
javax.swing.abstractbutton.fireactionperformed 2806
java.awt.eventdispatchthread.pumpeventsforfilter 2801
org.openide.util.task.run 2778
javax.swing.defaultbuttonmodel.fireactionperformed 2709
javax.swing.defaultbuttonmodel.setpressed 2611
org.netbeans.modules.javacore.jmiimpl.javamodel.parameterizedtypeimpl.rebuildobject 2548
org.netbeans.modules.javacore.jmiimpl.javamodel.parameterizedtypeimpl.substitute 2547
org.openide.util.mutex.readaccess 2464
java.lang.thread.run 2439
javax.swing.abstractbuttonhandler.actionperformed 2151
java.lang.reflect.method.invoke 2103
org.netbeans.modules.php.editor.parser.gsfphpparser.parsebuffer 2080
org.netbeans.modules.php.editor.parser.gsfphpparser.sanitize 2071
java.beans.propertychangesupport.firepropertychange 1925
sun.reflect.delegatingmethodaccessorimpl.invoke 1863
org.openide.util.mutex.writeaccess 1429
javax.swing.abstractbutton.doclick 1420
javax.swing.plaf.basic.basicmenuitemui.doclick 1340
java.awt.dialog.show 1277
javax.swing.plaf.basic.basicbuttonlistener.mousereleased 1248
org.openide.util.lookup.proxylookupr.computeresult 1200
sun.reflect.nativemethodaccessorimpl.invoke 1189
org.openide.util.lookup.proxylookupr.allinstances 1159
java.security.accesscontroller.doprivileged 1108
org.openide.util.mutex.doeventaccess 1077
org.netbeans.core.timableeventqueue.dispatchevent 1077
java.awt.dialog.run 1068
javax.swing.plaf.basic.basicmenuitemuihandler.mousereleased 1067
org.openide.util.mutex.doevent 1055
org.netbeans.core.windows.services.nbpresenter.doshow 1027
org.netbeans.core.windows.services.nbpresenter.supershow 1027
org.netbeans.core.windows.services.nbpresenter.run 1026

In [86]:
# From train data, remove all frequent frames
def remove_frequent_frames():
    for row in train_data:
        for stack in ["anchor", "positive", "negative"]:
            row[stack] = [frame for frame in row[stack] if frame not in frames]

In [87]:
frame_freq

{'java.awt.component.dispatchevent': 10401,
 'java.awt.container.dispatcheventimpl': 10400,
 'java.awt.eventqueue.dispatchevent': 9394,
 'java.awt.eventdispatchthread.pumpeventsforhierarchy': 8513,
 'java.awt.eventdispatchthread.pumpevents': 8010,
 'java.awt.eventdispatchthread.run': 7970,
 'org.netbeans.api.java.classpath.classpath.getclasspath': 7733,
 'org.netbeans.modules.web.freeform.webmodules.findclasspath': 7683,
 'org.netbeans.modules.java.project.projectclasspathprovider.findclasspath': 7679,
 'org.netbeans.modules.java.freeform.lookupmergerimplclasspathproviderimpl.findclasspath': 7677,
 'org.netbeans.modules.web.freeform.webmodulesffwebmodule.findclasspath': 7674,
 'java.awt.component.dispatcheventimpl': 6192,
 'java.awt.eventdispatchthread.pumponeeventforhierarchy': 6175,
 'org.openide.util.requestprocessorprocessor.run': 5764,
 'org.openide.util.requestprocessortask.run': 5742,
 'java.awt.window.dispatcheventimpl': 5213,
 'java.awt.component.processevent': 5034,
 'java.awt.container.processevent': 5015,
 'java.awt.lightweightdispatcher.dispatchevent': 4224,
 'java.awt.lightweightdispatcher.retargetmouseevent': 4176,
 'java.awt.event.invocationevent.dispatch': 4126,
 'java.awt.lightweightdispatcher.processmouseevent': 4099,
 'java.awt.component.processmouseevent': 3996,
 'javax.swing.jcomponent.paint': 3983,
 'org.netbeans.api.java.classpath.classpath.entries': 3611,
 'org.netbeans.modules.java.jseplatform.platformdefinition.defaultclasspathprovidercompileclasspathimpl.getresources': 3578,
 'javax.swing.jcomponent.paintchildren': 3381,
 'javax.swing.jcomponent.processmouseevent': 2841,
 'java.awt.eventdispatchthread.pumponeeventforfilters': 2813,
 'javax.swing.abstractbutton.fireactionperformed': 2806,
 'java.awt.eventdispatchthread.pumpeventsforfilter': 2801,
 'org.openide.util.task.run': 2778,
 'javax.swing.defaultbuttonmodel.fireactionperformed': 2709,
 'javax.swing.defaultbuttonmodel.setpressed': 2611,
 'org.netbeans.modules.javacore.jmiimpl.javamodel.parameterizedtypeimpl.rebuildobject': 2548,
 'org.netbeans.modules.javacore.jmiimpl.javamodel.parameterizedtypeimpl.substitute': 2547,
 'org.openide.util.mutex.readaccess': 2464,
 'java.lang.thread.run': 2439,
 'javax.swing.abstractbuttonhandler.actionperformed': 2151,
 'java.lang.reflect.method.invoke': 2103,
 'org.netbeans.modules.php.editor.parser.gsfphpparser.parsebuffer': 2080,
 'org.netbeans.modules.php.editor.parser.gsfphpparser.sanitize': 2071,
 'java.beans.propertychangesupport.firepropertychange': 1925,
 'sun.reflect.delegatingmethodaccessorimpl.invoke': 1863,
 'org.openide.util.mutex.writeaccess': 1429,
 'javax.swing.abstractbutton.doclick': 1420,
 'javax.swing.plaf.basic.basicmenuitemui.doclick': 1340,
 'java.awt.dialog.show': 1277,
 'javax.swing.plaf.basic.basicbuttonlistener.mousereleased': 1248,
 'org.openide.util.lookup.proxylookupr.computeresult': 1200,
 'sun.reflect.nativemethodaccessorimpl.invoke': 1189,
 'org.openide.util.lookup.proxylookupr.allinstances': 1159,
 'java.security.accesscontroller.doprivileged': 1108,
 'org.openide.util.mutex.doeventaccess': 1077,
 'org.netbeans.core.timableeventqueue.dispatchevent': 1077,
 'java.awt.dialog.run': 1068,
 'javax.swing.plaf.basic.basicmenuitemuihandler.mousereleased': 1067,
 'org.openide.util.mutex.doevent': 1055,
 'org.netbeans.core.windows.services.nbpresenter.doshow': 1027,
 'org.netbeans.core.windows.services.nbpresenter.supershow': 1027,
 'org.netbeans.core.windows.services.nbpresenter.run': 1026,
 'org.openide.filesystems.filesystem.runatomicaction': 1000,
 'org.openide.filesystems.eventcontrol.runatomicaction': 1000,
 'java.lang.classloader.loadclass': 996,
 'java.awt.container.addnotify': 990,
 'java.io.objectinputstream.readobject': 970,
 'javax.swing.jcomponent.addnotify': 961,
 'org.netbeans.modules.xml.xam.abstractmodel.sync': 897,
 'org.netbeans.modules.xml.xam.abstractmodelfactory.getmodel': 894,
 'org.netbeans.modules.xml.axi.impl.modelaccessimpl.sync': 890,
 'org.netbeans.modules.xml.axi.impl.aximodelimpl.sync': 886,
 'org.netbeans.modules.xml.axi.impl.aximodelimpl.getreferencedmodels': 886,
 'org.netbeans.core.nongui.run': 885,
 'org.netbeans.modules.xml.axi.impl.aximodelimpl.updatereferencedmodellistener': 884,
 'org.netbeans.modules.xml.axi.aximodelfactory.getmodel': 881,
 'java.awt.defaultkeyboardfocusmanager.dispatchevent': 856,
 'org.openide.util.weaklistenerimplpropertychange.propertychange': 851,
 'java.awt.defaultkeyboardfocusmanager.typeaheadassertions': 819,
 'org.netbeans.core.windows.services.nbpresenter.show': 789,
 'java.awt.keyboardfocusmanager.redispatchevent': 770,
 'javax.swing.jcomponent.processkeyevent': 769,
 'java.awt.defaultkeyboardfocusmanager.predispatchkeyevent': 747,
 'java.awt.component.show': 746,
 'java.awt.component.setvisible': 745,
 'org.netbeans.core.startup.main.start': 743,
 'java.io.objectinputstream.readordinaryobject': 741,
 'com.sun.source.util.treepathscanner.scan': 740,
 'org.netbeans.core.startup.topthreadgroup.run': 739,
 'java.awt.defaultkeyboardfocusmanager.dispatchkeyevent': 730,
 'org.netbeans.core.main.run': 726,
 'java.awt.awteventmulticaster.mousereleased': 718,
 'sun.reflect.generatedmethodaccessor.invoke': 714,
 'javax.swing.jcomponent.processkeybindings': 686,
 'java.util.concurrent.executorsrunnableadapter.call': 647,
 'java.util.concurrent.futuretasksync.innerrun': 638,
 'org.openide.util.changesupport.firechange': 638,
 'org.netbeans.core.startup.nbinstaller.load': 619,
 'org.netbeans.core.startup.main.getmodulesystem': 618,
 'org.netbeans.modulemanager.enable': 618,
 'java.util.concurrent.futuretask.run': 616,
 'org.openide.loaders.dataobject.firepropertychange': 610,
 'org.openide.loaders.datanode.getcookie': 610,
 'java.util.concurrent.threadpoolexecutorworker.run': 604,
 'org.openide.nodes.nodelookup.addcookie': 602,
 'org.netbeans.core.startup.modulelist.installnew': 601,
 'org.openide.loaders.dataloaderpool.finddataobject': 598,
 'org.openide.loaders.datanode.access': 597,
 'com.sun.tools.javac.code.symbolparamsymbol.getsimplename': 596,
 'javax.swing.abstractbuttonforwardactionevents.actionperformed': 594,
 'org.openide.nodes.node.firecookiechange': 594,
 'org.openide.loaders.datanode.run': 593,
 'org.netbeans.core.topthreadgroup.run': 592,
 'org.netbeans.core.startup.modulelist.trigger': 591,
 'org.netbeans.core.startup.modulesystem.restore': 589,
 'org.openide.loaders.dataloader.finddataobject': 586,
 'org.openide.nodes.nodelookup.updatelookupascookiesarechanged': 585,
 'org.netbeans.modules.openide.util.actionsbridge.doperformaction': 583,
 'java.util.concurrent.threadpoolexecutorworker.runtask': 582,
 'org.netbeans.modules.java.source.usages.symboldumper.dump': 581,
 'org.openide.nodes.cookieset.firechangeevent': 580,
 'org.netbeans.modules.java.source.paramnameresolver.resolvenames': 580,
 'org.netbeans.modules.java.source.usages.symboldumper.dumpimpl': 579,
 'org.openide.loaders.datanodepropl.propertychange': 577,
 'org.openide.loaders.datanode.firechange': 577,
 'org.openide.loaders.multidataobject.firecookiechange': 576,
 'org.netbeans.modules.java.source.paramnameresolver.dumpsymfile': 576,
 'org.openide.loaders.multidataobjectchangeandbefore.statechanged': 568,
 'java.io.objectinputstream.readserialdata': 566,
 'javax.swing.swingutilities.notifyaction': 564,
 'javax.swing.jcomponent.processkeybinding': 552,
 'org.openide.util.lookup.abstractlookupr.allinstances': 552,
 'org.openide.util.mutex.postrequest': 550,
 'org.netbeans.core.startup.nbinstaller.loadcode': 541,
 'org.openide.loaders.multifileloader.handlefinddataobject': 538,
 'javax.swing.systemeventqueueutilitiescomponentworkrequest.run': 530,
 'org.openide.util.actions.callablesystemaction.run': 525,
 'java.awt.container.dolayout': 523,
 'org.openide.explorer.exploreractions.access': 520,
 'java.io.objectstreamclass.invokereadobject': 511,
 'com.sun.source.util.treescanner.scanandreduce': 508,
 'org.netbeans.editor.baseaction.actionperformed': 504,
 'org.netbeans.modules.uml.ui.swing.trackbar.trackcoupling.updatecontraints': 504,
 'org.netbeans.modules.uml.ui.swing.trackbar.trackcoupling.resizetofitneighbors': 504,
 'org.netbeans.modules.uml.ui.swing.trackbar.trackcar.push': 504,
 'org.netbeans.modules.uml.ui.swing.trackbar.trackitem.push': 504,
 'org.netbeans.modules.uml.ui.swing.trackbar.trackitem.notifyneighborsofmove': 501,
 'org.openide.loaders.dataobject.find': 499,
 'org.openide.loaders.folderinstance.defaultprocessobjects': 481,
 'org.openide.loaders.folderinstance.access': 478,
 'org.openide.loaders.folderinstance.run': 476,
 'org.openide.filesystems.fileobjected.dispatch': 469,
 'org.openide.util.actions.callablesystemaction.actionperformed': 457,
 'org.netbeans.api.java.source.javasourcecompilationjob.run': 451,
 'org.openide.filesystems.fclsupport.dispatchevent': 448,
 'org.netbeans.api.java.source.support.cancellabletreepathscanner.scan': 448,
 'org.openide.util.actions.nodeactiondelegateaction.actionperformed': 447,
 'javax.swing.repaintmanager.paintdirtyregions': 444,
 'org.openide.loaders.folderlookupicitem.getinstance': 433,
 'org.netbeans.modules.settings.convertors.serialdataconvertorsettingsinstance.instancecreate': 432,
 'org.netbeans.modules.settings.convertors.xmlsettingssupportsettingsrecognizer.instancecreate': 432,
 'org.openide.util.mutex.postwriterequest': 428,
 'javax.swing.jcomponent.paintcomponent': 424,
 'org.openide.loaders.defaultdataobject.getcookie': 420,
 'java.awt.awteventmulticaster.mousepressed': 416,
 'org.openide.nodes.cookieset.add': 414,
 'com.sun.tools.javac.comp.attr.attribtree': 411,
 'javax.swing.jcomponent._paintimmediately': 410,
 'javax.swing.jcomponent.paintimmediately': 408,
 'org.openide.loaders.templatewizard.instantiate': 403,
 'org.openide.loaders.templatewizard.instantiateimpl': 403,
 'org.openide.nodes.children.getnodes': 384,
 'org.netbeans.modules.uml.parser.java.javatreeparser.expr': 383,
 'org.netbeans.modules.uml.parser.java.javatreeparser.conditionalexpr': 383,
 'java.net.urlclassloader.run': 371,
 'org.netbeans.core.windows.persistence.persistencemanager.gettopcomponentpersistentforid': 367,
 'org.netbeans.core.windows.persistence.persistencemanager.gettopcomponentforid': 366,
 'java.net.urlclassloader.findclass': 360,
 'java.awt.window.setvisible': 352,
 'javax.swing.jviewport.paint': 351,
 'java.awt.dialog.setvisible': 351,
 'org.openide.loaders.dataobjectpool.handlefinddataobject': 350,
 'java.lang.reflect.constructor.newinstance': 349,
 'java.util.regex.patterngrouphead.match': 348,
 'org.netbeans.spi.editor.completion.support.asynccompletiontask.run': 347,
 'org.netbeans.modules.java.hints.exportnonaccessibleelement.visittype': 347,
 'com.sun.tools.javac.code.symbolclasssymbol.accept': 347,
 'java.util.regex.patternbranch.match': 347,
 'java.util.regex.patterngrouptail.match': 346,
 'javax.swing.legacygluefocustraversalpolicy.getcomponentafter': 345,
 'javax.swing.defaultfocusmanager.getcomponentafter': 344,
 'java.util.regex.patternloop.match': 344,
 'org.netbeans.modules.vcscore.commands.commandprocessorinitialcomponentfocustraversalpolicy.getcomponentafter': 343,
 'java.util.regex.patterncharproperty.match': 343,
 'javax.swing.jlayeredpane.paint': 342,
 'java.util.regex.patternbranchconn.match': 342,
 'org.netbeans.modules.subversion.ui.diff.multidiffview.layout': 341,
 'org.netbeans.modules.subversion.ui.diff.multidiffview.layoutimpl': 341,
 'org.netbeans.modules.bpel.xpath.model.node.visitor.nodelocalvariabletreeexpandervisitor.visittreenode': 341,
 'org.netbeans.modules.bpel.xpath.model.nodes.impl.xsdelementnodeimpl.accept': 340,
 'org.netbeans.modules.bpel.xpath.model.node.visitor.nodelocalvariabletreeexpandervisitor.visit': 340,
 'sun.reflect.delegatingconstructoraccessorimpl.newinstance': 339,
 'org.netbeans.proxyclassloader.loadclass': 339,
 'org.netbeans.modules.websvc.registry.ui.testwebservicemethoddlg.traversetype': 339,
 'org.netbeans.modules.websvc.registry.ui.testwebservicemethoddlg.addparameterarrayinstances': 339,
 'org.openide.loaders.dataobject.run': 335,
 'com.sun.source.util.treescanner.scan': 335,
 'proxy.actionperformed': 334,
 'org.netbeans.modules.settings.convertors.xmlsettingssupportsettingsrecognizer.readserial': 331,
 'org.openide.wizarddescriptor.access': 331,
 'org.openide.loaders.folderlist.access': 329,
 'org.netbeans.api.java.source.javasource.runuseractiontask': 329,
 'java.lang.class.newinstance': 326,
 'org.netbeans.core.modules.modulemanager.enable': 325,
 'javax.swing.plaf.basic.basicmenuitemuimouseinputhandler.mousereleased': 322,
 'org.netbeans.core.modules.modulelist.installnew': 316,
 'org.netbeans.api.project.projectmanager.run': 314,
 'org.netbeans.spi.project.ui.projectopenedhook.projectopened': 314,
 'org.openide.util.requestprocessorprocessorthread.run': 310,
 'sun.reflect.nativeconstructoraccessorimpl.newinstance': 307,
 'org.netbeans.core.main.start': 304,
 'org.openide.loaders.folderlist.getobjects': 303,
 'org.openide.filesystems.eventcontrol.exitatomicaction': 303,
 'org.openide.topmanager.getdefault': 300,
 'org.openide.topmanager.initializetopmanager': 300,
 'org.netbeans.core.nbtopmanager.get': 299,
 'org.netbeans.core.modules.modulelist.trigger': 298,
 'org.openide.util.mutex.run': 297,
 'org.netbeans.core.nbtopmanager.getnbtopmanager': 297,
 'org.openide.loaders.folderlistlisttask.run': 295,
 'org.netbeans.core.main.main': 293,
 'org.netbeans.modules.java.javaeditor.run': 293,
 'org.openide.loaders.multifileloader.findprimaryfileimpl': 293,
 'org.openide.loaders.folderlookupicitem.init': 293,
 'javax.swing.plaf.componentui.update': 292,
 'org.openide.filesystems.eventcontrol.invokedispatchers': 292,
 'org.openide.util.actions.nodeaction.performaction': 290,
 'javax.swing.jcomponent.getpreferredsize': 289,
 'org.openide.nodes.children.calladdnotify': 281,
 'org.netbeans.core.windows.viewrequestor.dispatchrequest': 281,
 'org.openide.util.actions.callbacksystemaction.updateenabled': 280,
 'org.openide.util.actions.nodeaction.actionperformed': 278,
 'org.netbeans.core.modules.nbinstaller.load': 276,
 'org.netbeans.core.windows.view.defaultview.changegui': 276,
 'org.openide.filesystems.mimesupport.findmimetype': 275,
 'org.netbeans.modules.project.ui.openprojectlist.notifyopened': 274,
 'java.awt.eventdispatchthread.pumponeevent': 273,
 'java.lang.classloader.loadclassinternal': 273,
 'javax.swing.jcomponent.paintdoublebuffered': 273,
 'javax.swing.jcomponent.paintwithoffscreenbuffer': 273,
 'org.openide.util.actions.callbacksystemaction.setactionperformer': 273,
 'org.openide.explorer.exploreractions.updateactions': 271,
 'org.openide.util.actions.nodeactiondelegateaction.run': 269,
 'java.awt.awteventmulticaster.mouseclicked': 268,
 'org.netbeans.core.windows.persistencehandler.gettopcomponentforid': 268,
 'org.openide.loaders.folderlist.createboth': 266,
 'org.netbeans.core.windows.viewrequestor.schedulerequest': 262,
 'org.netbeans.modules.java.source.usages.repositoryupdatercompileworker.run': 261,
 'org.netbeans.editor.basedocument.render': 258,
 'org.openide.explorer.exploreractions.updateactionsstate': 257,
 'org.openide.explorer.exploreractionsactionstateupdater.update': 257,
 'com.rfidgs.utilities.handheld.logger.logerror': 256,
 'com.rfidgs.utilities.handheld.logger.getinstance': 256,
 'com.rfidgs.utilities.handheld.appconfig.getlogfilename': 255,
 'com.rfidgs.utilities.handheld.appconfig.getbundleinstance': 255,
 'org.openide.nodes.children.getarray': 253,
 'org.openide.loaders.unifileloader.findprimaryfile': 253,
 'org.openide.explorer.exploreractionscopycutactionperformer.isenabled': 253,
 'com.sun.tools.javac.comp.attr.attribstat': 253,
 'org.openide.nodes.childrenkeys.setkeys': 251,
 'org.openide.loaders.extensionlist.isregistered': 251,
 'org.openide.filesystems.multifileobject.getmimetype': 251,
 'org.openide.filesystems.fileutil.getmimetypeordefault': 251,
 'sun.misc.launcherappclassloader.loadclass': 250,
 'org.openide.nodes.childrenkeyske.nodes': 248,
 'org.netbeans.modules.javacore.jmiimpl.javamodel.resourceimpl.directupdate': 248,
 'org.netbeans.core.execution.runclassthread.run': 247,
 'org.openide.util.actions.callablesystemaction.doperformaction': 247,
 'org.netbeans.core.windows.persistencehandler.load': 245,
 'org.openide.util.weaklistenerimplproxylistener.invoke': 245,
 'org.openide.loaders.templatewizard.handleinstantiate': 244,
 'org.netbeans.modules.javacore.jmiimpl.javamodel.resourceimpl.checkuptodate': 242,
 'org.netbeans.modules.project.ui.actions.newfile.doperform': 241,
 'org.openide.filesystems.fileobject.getmimetype': 241,
 'org.netbeans.modules.java.hints.infrastructure.hintstaskscannerimpl.scan': 241,
 'org.openide.windows.topcomponent.open': 240,
 'org.openide.nodes.childrenarray.nodesfor': 238,
 'org.openide.filesystems.mimesupportcachedfileobject.getresolvers': 237,
 'org.apache.tools.ant.task.perform': 236,
 'com.sun.tools.javac.tree.jctreejcclassdecl.accept': 233,
 'org.apache.tools.ant.unknownelement.execute': 231,
 'org.openide.filesystems.abstractfolder.find': 230,
 'org.openide.filesystems.abstractfolder.getchild': 229,
 'org.openide.filesystems.mimesupportcachedfileobject.isanyresolver': 228,
 'org.openide.filesystems.multifilesystem.findresource': 228,
 'org.openide.nodes.childrenkeys.applykeys': 226,
 'org.netbeans.api.java.source.javasource.runmodificationtask': 226,
 'org.openide.filesystems.multifileobject.createfile': 226,
 'org.openide.filesystems.multifileobject.init': 226,
 'org.openide.filesystems.multifileobject.update': 226,
 'org.openide.filesystems.multifilesystem.writablelayer': 226,
 'org.netbeans.modules.apisupport.project.layers.layerfilesystem.createwritableon': 226,
 'java.awt.component.firepropertychange': 225,
 'org.openide.nodes.filternodechildren.updatekeys': 224,
 'org.netbeans.core.windows.windowsystemimpl.load': 224,
 'org.openide.nodes.filternodechildrenadapter.run': 223,
 'org.netbeans.modules.editor.hints.hintsoperatorhintpopuptaskimpl.run': 223,
 'org.netbeans.core.moduleactions.run': 220,
 'org.netbeans.editor.guardeddocument.runatomic': 220,
 'org.netbeans.modules.php.editor.parser.astnodes.visitors.defaultvisitor.scan': 219,
 'java.awt.container.addimpl': 216,
 'org.openide.util.lookup.proxylookupr.mybeforelookup': 215,
 'java.awt.container.add': 214,
 'java.lang.class.forname': 212,
 'org.openide.util.actions.nodeaction.run': 211,
 'javax.swing.timer.fireactionperformed': 210,
 'org.netbeans.core.windows.modeimpl.requestfocus': 210,
 'org.netbeans.core.windows.modeimpl.dorequestfocus': 210,
 'org.openide.explorer.explorermanager.setselectednodes': 209,
 'org.netbeans.modules.refactoring.api.abstractrefactoring.pluginsprepare': 209,
 'org.netbeans.modules.refactoring.api.abstractrefactoring.prepare': 207,
 'org.openide.loaders.instancedataobject.instancecreate': 206,
 'org.netbeans.editor.settings.firesettingschange': 206,
 'org.netbeans.core.moduleactions.invokeaction': 205,
 'javax.swing.timerdopostevent.run': 205,
 'org.netbeans.core.windows.windowmanagerimpl.findtopcomponent': 205,
 'org.netbeans.modules.javacore.jmiimpl.javamodel.metadataelement.initcheck': 205,
 'org.openide.nodes.childreninfo.nodes': 203,
 'org.openide.loaders.instancedataobjectser.instancecreate': 203,
 'com.sun.tools.javac.tree.jctreejccompilationunit.accept': 202,
 'com.sun.tools.javac.tree.jctreejcblock.accept': 201,
 'org.netbeans.modules.java.source.save.casualdiff.difftree': 200,
 'org.netbeans.mdr.nbmdrepositoryimpl.begintrans': 199,
 'org.netbeans.modules.javacore.jmmanager.run': 199,
 'javax.swing.text.boxview.paint': 198,
 'javax.swing.text.boxview.paintchild': 198,
 'org.apache.tools.ant.module.loader.antprojectdataloader.findprimaryfile': 198,
 'org.openide.nodes.children.setentries': 197,
 'org.netbeans.modules.project.ui.openprojectlist.getdefault': 197,
 'org.openide.nodes.filternodechildren.addnotifyimpl': 196,
 'org.netbeans.modules.javacore.exclusivemutex.enter': 196,
 'org.netbeans.modules.project.ui.actions.newfile.access': 194,

In [88]:
from pprint import pprint
# Find frame frequency from the training data
def y():
    for row in train_data:
        for stack in ["anchor", "positive", "negative"]:
            for frame in row[stack]:
                if frame == "org.eclipse.swt.widgets.display.readanddispatch":
                    pprint(row)
                    return

y()

In [89]:
frame_freq["org.eclipse.ui.internal.workbench.run"]

KeyError: 'org.eclipse.ui.internal.workbench.run'

In [61]:
gg = ['org.eclipse.core.launcher.main.main',
              'org.eclipse.core.launcher.main.run',
              'org.eclipse.core.launcher.main.basicrun',
              'java.lang.reflect.method.invoke',
              'org.eclipse.core.boot.bootloader.run',
              'org.eclipse.core.internal.boot.internalbootloader.run',
              'org.eclipse.ui.internal.workbench.run',
              'org.eclipse.ui.internal.workbench.runeventloop',
              'org.eclipse.swt.widgets.display.readanddispatch',
              'org.eclipse.swt.widgets.display.rundeferredevents',
              'org.eclipse.swt.widgets.eventtable.sendevent',
              'org.eclipse.jface.action.actioncontributionitemactionlistener.handleevent',
              'org.eclipse.jface.action.actioncontributionitem.handlewidgetselection',
              'org.eclipse.ui.internal.wwinpluginaction.runwithevent',
              'org.eclipse.ui.internal.pluginaction.runwithevent',
              'org.eclipse.team.internal.ccvs.ui.actions.cvsaction.run',
              'org.eclipse.team.internal.ccvs.ui.actions.workspaceaction.beginexecution']

In [62]:
gg[-8:]

['org.eclipse.swt.widgets.display.rundeferredevents',
 'org.eclipse.swt.widgets.eventtable.sendevent',
 'org.eclipse.jface.action.actioncontributionitemactionlistener.handleevent',
 'org.eclipse.jface.action.actioncontributionitem.handlewidgetselection',
 'org.eclipse.ui.internal.wwinpluginaction.runwithevent',
 'org.eclipse.ui.internal.pluginaction.runwithevent',
 'org.eclipse.team.internal.ccvs.ui.actions.cvsaction.run',
 'org.eclipse.team.internal.ccvs.ui.actions.workspaceaction.beginexecution']

In [63]:
len(train_data)

4920

In [71]:
updated_train_data = []
updated_test_data = []

# Remove all frames from train_data that has a frequency over 2000
for row in train_data:
    new_row = {}
    for stack in ["anchor", "positive", "negative"]:
        previous = len(row[stack])

        if previous < 5:
            updated_train_data.append(row)
            continue
        
        new_row[stack] = [frame for frame in row[stack] if frame_freq[frame] <= 500]
        current = len(new_row[stack])
        print(previous, current)
        updated_train_data.append(new_row)

19 6
17 5
13 9
50 21
16 11
23 22
38 19
31 17
9 6
35 14
36 15
15 5
12 11
12 11
6 5
30 21
30 21
17 7
22 15
54 26
50 25
21 9
17 9
2 2
7 2
7 2
38 18
21 7
19 7
18 5
17 5
21 7
31 17
17 9
17 9
35 18
20 9
30 21
25 7
22 18
13 10
38 20
28 15
28 15
19 14
30 16
31 15
26 25
44 29
50 30
63 43
20 9
19 12
23 8
22 18
22 18
15 3
30 12
36 16
5 4
25 19
54 26
37 21
41 29
44 29
41 15
16 5
15 7
42 24
20 7
22 7
46 27
24 8
21 6
28 16
23 12
22 7
19 4
12 0
39 11
39 30
53 26
24 8
19 7
1 1
43 18
20 6
18 7
22 7
13 11
20 7
20 7
2 2
25 21
63 38
31 31
54 24
25 21
29 17
41 23
18 7
26 13
19 8
12 5
22 9
7 6
19 17
11 5
28 12
14 5
18 12
26 15
28 15
43 18
16 5
16 5
29 6
15 3
16 2
19 6
35 18
39 18
48 25
47 25
21 6
52 20
18 16
39 18
30 14
106 47
47 25
35 15
15 3
20 7
8 8
28 11
37 18
13 2
19 8
19 8
18 13
12 5
19 8
63 36
53 26
106 47
20 9
14 0
14 0
15 15
32 29
39 30
12 12
34 29
41 32
23 14
43 30
41 32
44 18
16 14
8 7
21 8
29 10
37 18
30 14
9 8
9 8
34 23
37 18
39 18
20 9
53 32
53 32
38 22
40 23
40 23
25 12
28 13
26 13
23 9
48 33
48 33
3 2
50 31
22 7
19 4
12 5
19 8
38 17
26 10
10 8
37 21
11 9
38 34
42 25
22 15
25 19
53 28
22 13
48 24
26 11
55 22
22 13
75 53
29 5
27 5
18 4
26 14
48 24
44 20
37 16
30 12
15 11
38 29
32 29
4 2
71 10
28 12
60 31
55 33
71 10
34 16
25 11
71 10
22 18
36 17
25 11
26 11
23 12
26 14
57 21
55 24
55 22
1 1
48 20
23 12
32 13
3 3
23 12
33 19
77 25
71 10
8 7
96 69
47 40
13 12
19 19
40 25
1 1
31 16
50 29
23 7
33 19
33 19
11 10
48 24
23 12
9 9
60 26
48 24
4 3
37 5
37 5
37 22
26 14
55 22
8 7
33 19
33 19
26 13
24 8
19 6
25 13
48 24
23 12
33 16
42 29
42 29
9 2
36 17
36 17
12 5
31 16
28 12
44 20
16 10
48 24
46 26
27 11
27 11
34 15
22 13
23 12
17 10
68 39
16 10
32 16
55 24
38 16
22 7
30 10
71 10
17 11
55 35
71 10
12 3
38 13
38 13
37 23
32 16
55 35
27 11
37 16
33 19
41 13
49 36
39 30
34 17
35 19
35 19
39 16
37 22
35 19
11 5
39 15
10 8
9 1
60 35
60 35
609 405
89 54
36 17
21 8
35 14
29 13
27 10
22 5
55 33
27 9
26 17
50 29
54 35
75 30
14 0
23 10
46 21
19 8
53 34
8 7
46 21
15 7
49 32
23 11
18 5
16 7
46 21
17 12
22 5
31 16
29 15
33 16
35 14
41 23
73 73
49 32
60 26
36 17
30 10
26 13
24 11
22 11
46 29
16 9
19 8
23 11
66 43
66 43
26 13
38 15
75 30
34 22
55 22
26 14
16 13
40 19
14 0
43 13
18 9
8 7
9 2
35 16
55 33
19 4
74 42
32 16
12 11
31 13
75 30
35 13
55 24
55 24
77 25
22 19
19 17
20 8
28 27
26 25
75 56
85 48
74 44
26 14
27 12
27 13
71 10
8 7
6 5
35 19
23 12
23 12
8 5
36 17
35 16
26 13
5 2
5 2
2 2
35 19
15 14
30 8
32 19
27 12
41 20
60 34
31 18
11 4
38 17
55 35
12 8
45 27
45 27
53 34
38 16
34 7
19 12
22 5
89 54
55 30
19 6
17 6
22 18
31 16
26 17
29 15
41 14
41 18
37 21
53 31
45 16
15 14
41 18
41 18
12 0
46 33
35 27
29 10
6 0
6 0
9 8
9 8
9 8
13 12
40 12
10 9
16 13
35 15
29 14
26 11
60 39
80 45
9 8
15 11
15 11
18 16
78 43
75 42
40 12
14 9
14 10
10 6
16 14
20 18
33 16
38 22
30 16
11 9
32 16
37 19
15 11
32 16
37 19
6 3
1 1
11 9
21 5
37 17
44 22
20 6
14 0
41 32
37 16
13 4
13 4
19 5
5 2
5 2
40 23
34 12
34 12
23 11
27 7
13 4
28 12
36 22
36 22
34 16
14 0
37 17
8 7
17 3
14 0
12 10
17 11
18 10
15 2
10 8
10 6
32 15
78 43
78 43
14 13
43 23
43 23
32 12
17 3
17 3
32 16
17 11
17 11
31 7
15 2
15 2
50 31
2 2
1 1
5 4
13 11
78 43
28 12
80 53
58 34
15 2
20 16
58 34
7 6
29 10
30 24
27 14
78 53
80 53
31 17
32 13
80 53
10 6
11 9
11 9
40 22
31 15
31 15
21 7
42 24
31 23
26 13
44 31
35 27
36 18
20 9
20 9
5 3
29 8
29 8
23 10
42 29
39 30
41 18
43 18
21 12
19 10
45 16
21 12
35 25
16 5
17 6
41 37
38 10
38 10
59 35
30 7
38 10
12 0
19 6
16 5
50 29
33 8
29 8
36 17
12 0
20 6
33 17
19 6
16 5
36 12
7 6
37 32
28 11
47 17
30 7
60 35
36 32
7 6
27 25
25 16
28 17
17 3
38 10
38 10
1 1
47 16
48 19
31 9
38 10
38 10
2 2
30 15
48 28
19 15
11 9
1 1
34 8
66 20
34 14
30 15
37 16
36 16
22 11
38 10
38 10
38 22
19 6
19 6
42 24
55 30
17 9
8 7
56 35
43 30
40 23
48 17
38 10
27 26
38 10
38 10
25 16
8 5
38 10
17 8
29 17
30 15
41 23
25 5
25 5
19 8
19 6
19 6
9 7
44 32
30 15
44 27
24 16
22 10
10 10
22 10
22 10
38 13
15 8
9 2
12 10
29 22
29 17
40 20
10 9
33 22
41 18
29 22
48 28
34 34
48 21
51 24
22 10
20 17
21 19
18 6
13 13
53 25
1 1
38 24
21 19
30 10
60 35
50 22
4 3
26 22
23 12
104 51
24 15
25 16
42 17
3 3
14 0
85 48
36 7
36 7
50 31
17 4
17 4
29 17
25 24
16 14
29 11
50 39
47 34
13 12
86 86
6 6
6 6
27 12
27 12
39 14
27 12
27 12
41 18
27 12
27 12
21 7
55 34
23 12
15 13
25 25
18 18
50 30
27 19
6 0
37 12
20 9
20 9
17 10
14 5
15 8
20 16
45 29
44 28
14 9
15 12
73 47
505 505
82 58
29 28
33 16
82 58
29 28
17 12
40 20
22 12
5 5
20 20
29 28
30 21
6 0
18 11
32 7
22 13
55 22
12 12
26 20
24 20
5 2
17 16
82 58
33 15
15 13
52 26
41 37
102 74
9 9
27 6
89 65
9 9
6 0
28 15
14 0
25 18
38 23
37 21
10 9
31 31
17 16
8 8
32 19
14 0
16 10
104 51
104 51
32 7
74 51
26 25
38 17
26 3
26 3
33 12
6 0
6 0
31 25
6 1
27 12
14 0
37 15
39 15
13 12
40 23
44 27
57 26
42 20
39 15
32 15
49 34
40 27
27 9
74 52
89 65
14 9
8 5
8 5
15 7
33 23
102 74
43 18
49 36
41 32
38 13
38 23
31 25
35 24
21 12
39 15
47 19
43 31
53 41
6 1
63 34
50 25
29 19
24 11
10 10
29 13
30 15
396 195
10 9
6 0
6 0
20 8
59 33
31 18
41 18
38 20
40 22
15 10
37 13
37 13
49 32
39 9
7 6
17 11
6 0
31 18
15 10
31 14
33 14
35 13
20 17
11 10
28 10
16 16
16 16
22 10
31 13
28 10
93 62
11 8
11 8
42 29
28 10
31 13
21 19
45 25
45 25
30 21
14 0
56 37
8 6
46 26
45 25
8 5
27 7
28 10
22 18
45 25
45 25
25 25
42 22
45 25
35 14
17 5
15 3
1 1
27 7
31 13
26 9
17 13
37 13
22 20
58 37
83 45
28 25
59 40
83 45
32 15
24 6
24 11
29 17
44 17
59 31
40 12
31 20
30 21
70 29
15 6
15 6
41 32
22 7
22 7
25 11
30 19
30 19
22 16
19 4
17 4
13 0
32 9
33 5
42 21
41 21
42 17
22 15
56 39
56 39
27 9
56 39
56 39
52 26
40 21
63 34
14 0
7 6
7 6
17 15
13 12
13 12
56 34
33 24
20 20
41 29
4 3
3 3
40 12
42 12
44 17
63 39
16 7
6 0
36 7
25 25
2 2
40 22
9 2
18 11
16 16
15 8
6 0
14 12
13 13
46 27
40 12
38 17
38 17
22 5
5 5
5 5
27 10
63 40
54 32
10 1
7 6
7 6
18 18
30 6
46 19
24 23
42 12
57 32
25 10
44 22
28 19
20 9
33 14
44 22
38 17
23 23
43 28
14 0
16 14
20 11
77 59
21 21
43 28
15 6
24 15
54 33
38 10
32 9
43 14
39 22
34 15
31 14
75 46
9 8
9 8
9 2
24 9
5 5
28 24
8 6
10 8
18 5
6 0
6 0
34 30
18 12
42 17
6 0
8 7
8 7
16 11
13 12
13 12
5 5
12 11
13 12
5 5
25 24
18 17
26 25
25 1
1 0
12 11
2 2
1 1
29 10
54 22
49 26
15 10
13 12
13 12
77 59
25 1
1 0
42 25
55 25
49 26
19 4
12 4
22 5
22 10
44 31
26 22
63 34
15 12
15 12
41 15
14 0
14 0
8 8
25 1
25 1
39 22
21 3
21 3
77 25
38 10
38 12
4 4
9 8
15 8
20 6
14 0
14 0
19 19
37 12
38 10
18 12
11 8
46 20
18 4
5 4
4 3
28 8
27 17
40 21
55 34
37 27
51 25
21 21
39 20
39 20
48 27
29 12
31 12
6 6
40 21
42 21
15 11
29 20
29 20
30 9
39 19
44 27
17 6
37 15
37 15
26 25
9 8
9 8
54 22
20 16
22 18
46 19
9 8
9 8
9 8
38 11
38 11
29 14
18 15
23 22
12 10
21 19
35 26
14 0
15 12
15 12
34 14
22 18
22 18
79 39
24 15
40 21
21 18
9 8
44 26
16 14
51 42
20 17
77 42
6 0
16 7
14 5
37 28
35 26
6 0
33 13
32 12
6 5
20 18
37 28
25 10
27 6
25 4
16 16
3 2
3 2
15 12
5 4
3 2
21 19
6 0
6 0
21 15
14 0
61 23
6 6
70 42
86 50
36 18
58 46
20 18
16 5
32 12
32 12
11 10
25 1
25 1
36 16
34 18
35 17
5 5
82 54
49 24
35 6
30 9
61 23
59 40
30 9
14 0
42 13
37 33
36 30
18 16
71 39
46 22
66 40
32 12
32 12
28 25
45 25
16 7
13 12
19 13
30 6
51 25
24 16
41 32
21 15
13 12
13 12
18 9
55 30
69 38
41 18
39 10
41 10
40 21
15 15
15 15
25 1
32 12
32 12
7 6
40 15
50 19
8 6
69 38
61 25
46 22
2 2
2 2
3 3
37 24
43 28
3 3
20 15
20 15
41 21
15 12
15 12
63 21
38 23
16 16
39 23
20 15
20 15
1 1
13 12
13 12
5 3
94 34
36 19
27 15
17 3
36 19
21 3
46 17
94 34
5 4
46 17
46 17
20 15
5 5
6 6
19 16
20 15
20 15
56 26
52 23
52 23
25 4
6 0
6 0
20 18
30 18
30 18
1 1
55 23
52 23
19 4
28 25
8 7
39 18
11 4
2 1
32 29
35 12
33 13
39 30
80 34
80 34
7 7
8 0
17 6
19 10
12 11
13 13
50 20
6 0
6 0
22 18
6 0
6 0
71 10
23 22
35 34
10 8
20 15
20 15
27 26
21 12
6 0
21 11
48 37
50 39
29 13
22 21
27 24
4 4
8 0
8 0
4 3
23 19
27 24
1 1
33 31
23 19
44 14
48 25
12 11
56 39
9 8
13 12
55 24
292 214
13 10
14 0
85 49
55 35
74 52
9 7
292 214
25 4
11 10
34 14
21 7
19 16
26 25
8 7
35 22
9 7
33 14
44 18
41 21
1 1
27 24
19 15
42 13
46 44
19 15
44 14
2 1
2 1
11 9
35 33
9 8
48 35
25 16
8 7
8 7
21 15
21 15
45 32
11 9
19 16
40 15
21 20
26 25
28 28
40 10
8 7
14 0
40 11
40 11
17 7
34 12
20 9
55 35
2 1
2 1
36 17
8 6
8 6
16 14
38 13
40 15
30 21
44 27
46 26
19 10
9 8
10 9
53 41
10 8
58 46
20 7
39 12
8 7
13 11
8 6
8 6
24 24
26 6
2 2
20 4
45 34
35 33
32 9
81 47
55 35
30 19
19 13
21 15
39 16
26 23
8 7
27 7
17 0
16 2
23 8
5 4
7 6
21 6
12 1
6 0
57 21
11 9
28 25
13 13
3 2
3 2
29 14
40 11
40 11
30 14
89 55
94 58
86 23
11 2
11 2
78 43
8 0
8 0
30 6
15 5
15 5
27 27
16 12
9 8
5 5
8 0
8 0
54 18
8 0
8 0
26 26
8 0
8 0
6 0
9 8
10 9
34 8
39 25
11 2
21 16
11 5
11 5
16 3
40 15
40 15
20 6
4 3
35 33
25 7
11 10
14 12
57 34
34 11
34 11
35 33
25 6
27 8
20 6
25 6
27 8
20 15
10 8
10 8
110 68
17 0
17 0
53 27
34 13
10 8
55 35
50 30
44 27
40 27
19 13
8 0
45 24
13 12
7 7
28 6
16 7
8 7
15 12
15 8
4 1
24 5
4 1
15 8
11 2
38 19
11 2
13 12
64 34
2 2
36 19
49 29
11 2
38 22
29 8
29 8
9 8
19 13
21 15
23 8
40 20
13 13
25 8
8 0
19 13
14 0
59 22
74 51
28 25
41 25
46 27
24 10
36 24
49 29
43 30
21 17
22 18
22 20
25 13
8 0
46 22
36 24
49 29
24 11
46 17
6 6
4 3
25 13
8 0
6 0
36 24
39 25
19 6
67 40
32 12
20 18
34 12
7 6
22 5
61 25
11 2
80 34
25 13
8 0
17 16
68 30
11 9
43 18
30 17
49 29
10 8
30 17
11 2
19 13
30 17
11 2
10 9
30 17
30 17
6 0
30 17
30 17
27 15
30 17
36 24
37 15
30 16
30 17
10 10
40 19
39 25
9 7
25 13
8 0
44 14
25 13
8 0
6 0
66 43
59 20
7 7
25 13
8 0
15 8
36 24
40 19
38 17
28 7
11 2
42 16
35 18
53 23
12 12
25 13
25 13
5 4
46 17
89 55
15 12
33 8
27 3
10 5
93 56
90 55
36 32
33 14
31 14
79 39
27 10
32 12
20 17
107 65
45 24
40 27
20 9
20 9
54 32
32 20
30 17
29 14
20 9
20 9
47 27
8 0
8 0
31 12
20 15
41 25
49 26
25 13
8 0
28 24
25 13
8 0
49 26
17 3
17 3
14 0
8 8
48 20
38 11
7 0
7 0
38 28
44 13
41 15
30 12
25 13
8 0
28 8
8 7
31 11
20 4
25 19
72 45
93 62
12 4
12 4
24 7
47 23
25 19
20 9
45 25
30 16
35 15
33 20
27 16
31 25
13 10
63 40
40 23
27 10
27 10
23 23
7 0
6 0
15 13
11 10
9 8
30 21
10 9
9 8
39 19
64 28
62 26
9 9
9 1
64 28
19 13
31 10
61 25
38 23
26 8
11 9
20 18
10 10
48 28
21 12
57 28
64 34
11 2
80 16
33 15
33 33
8 0
25 13
12 4
33 9
33 15
49 22
36 24
30 17
11 11
9 9
8 0
34 6
33 16
80 16
23 4
34 17
33 16
14 13
56 22
56 22
40 17
47 20
33 9
13 10
17 0
34 17
9 2
20 14
20 14
13 13
7 6
8 7
11 8
20 14
20 14
12 4
73 47
20 14
38 21
32 11
27 10
3 2
30 22
20 14
60 27
20 14
30 22
8 6
14 5
14 5
32 29
55 27
37 16
27 7
20 14
20 14
6 0
20 14
30 22
13 12
33 12
27 10
8 7
30 11
67 29
75 64
42 24
42 24
6 0
63 26
37 16
30 15
16 16
12 12
75 39
39 19
39 19
6 6
25 13
25 13
41 8
49 24
2 2
14 13
59 41
30 25
11 9
35 6
35 6
15 15
39 10
47 16
45 16
35 6
35 6
78 43
11 10
33 19
24 20
35 6
4 4
16 10
13 4
10 4
17 5
44 12
35 6
38 23
14 7
14 7
33 6
35 13
46 19
6 1
58 36
90 55
9 8
62 28
77 35
110 68
29 12
46 19
14 14
32 20
45 25
6 0
49 21
5 3
28 10
29 12
29 12
40 15
45 18
29 12
53 37
28 9
26 7
28 4
8 1
8 1
21 5
59 18
45 18
6 0
40 21
35 13
35 6
8 1
8 1
22 5
26 7
26 7
11 10
60 39
65 43
21 19
20 16
22 18
89 65
33 14
31 14
29 8
47 18
59 18
29 14
6 6
36 17
10 8
6 0
22 16
25 24
10 3
10 3
28 1
17 0
3 3
67 29
36 27
58 46
62 26
68 31
67 30
50 28
70 36
67 30
12 8
33 13
3 3
48 20
30 11
30 11
2 2
20 9
20 9
14 12
31 13
33 13
50 22
26 7
28 9
8 1
26 6
26 6
30 6
46 26
46 26
36 16
68 31
70 36
6 0
27 17
27 17
30 12
27 17
27 17
39 10
16 13
3 3
17 0
28 13
15 4
2 2
36 14
15 4
27 17
46 26
46 26
7 6
37 16
24 10
19 16
12 11
69 39
37 16
205 125
52 23
22 9
13 6
11 4
50 25
12 12
6 0
38 28
8 7
7 6
5 5
10 10
9 9
59 22
35 12
45 17
74 40
28 9
28 9
43 21
55 27
35 12
13 5
21 16
22 17
28 13
68 31
68 31
49 18
33 10
33 10
4 3
62 35
61 33
42 12
67 29
30 11
30 17
230 136
52 23
10 7
8 1
8 1
42 19
35 24
36 27
18 11
14 11
14 11
11 10
26 22
14 11
39 8
9 9
4 3
29 20
14 11
14 11
48 17
16 16
18 18
8 1
26 22
14 11
22 8
35 18
35 18
41 21
26 22
26 22
13 10
9 9
12 11
17 11
28 7
50 25
25 13
36 10
36 10
6 0
12 10
8 7
24 11
46 26
48 28
14 0
7 6
7 6
1 1
57 36
58 34
45 18
13 12
13 12
20 15
13 12
13 12
37 12
53 30
57 36
40 15
30 3
30 4
68 31
33 5
33 5
45 25
79 42
57 36
15 14
9 9
9 9
6 0
56 32
58 34
25 6
44 26
2 0
31 30
55 34
58 34
21 16
25 4
23 2
47 19
9 9
9 9
30 11
58 31
50 25
26 6
70 35
49 24
26 26
9 9
9 9
71 39
22 16
37 29
14 11
21 15
37 29
33 13
57 25
44 19
12 8
21 3
21 3
18 14
5 4
10 10
52 18
31 10
48 13
64 38
35 14
36 15
12 1
53 30
50 29
27 10
68 41
61 33
32 12
20 20
16 16
25 13
39 26
22 16
35 6
19 13
19 13
15 5
24 5
26 7
11 10
8 7
13 5
33 12
53 23
66 34
55 23
47 16
17 15
40 21
24 5
26 7
58 40
35 6
34 5
60 28
17 16
13 5
13 13
53 23
66 34
48 23
17 17
16 16
20 15
30 11
44 13
46 41
34 12
34 12
13 10
4 2
4 2
8 5
23 23
23 23
9 9
71 33
9 9
60 27
52 52
29 29
17 13
44 43
59 58
42 29
14 14
63 33
21 8
3 3
23 18
46 26
48 17
54 23
33 33
46 21
69 34
28 24
8 7
8 7
22 16
34 32
11 10
48 23
74 42
50 29
46 20
11 10
11 10
15 8
25 13
8 0
71 33
21 5
21 4
29 29
48 21
45 21
14 7
33 10
33 10
45 12
10 1
10 1
29 29
12 12
68 30
8 7
11 10
11 10
8 7
22 18
20 16
43 27
97 55
62 35
23 4
19 13
21 15
49 19
19 13
19 13
19 18
49 28
57 28
39 10
18 18
14 14
55 24
12 11
11 10
2 2
22 5
38 9
26 7
30 10
62 39
20 19
78 39
9 9
24 6
20 20
30 30
88 53
11 10
11 10
26 7
11 10
11 10
6 0
59 25
58 24
94 70
37 18
6 6
12 11
20 3
44 17
1 1
53 30
53 30
17 0
17 17
15 15
22 13
41 13
42 13
38 16
34 6
54 16
14 9
62 40
64 42
33 5
11 10
11 10
6 0
53 23
53 23
25 3
37 17
39 19
33 5
38 15
44 11
40 20
45 16
47 16
19 19
48 17
45 11
27 18
21 4
64 42
26 8
45 11
45 11
6 4
38 17
41 21
88 55
30 10
30 10
31 10
44 16
11 8
14 5
8 3
8 3
6 6
42 9
44 11
3 3
44 11
38 15
34 11
27 6
59 31
49 24
8 3
8 3
7 7
30 12
44 11
28 7
9 8
10 9
8 7
40 14
44 11
55 27
19 13
21 15
20 4
18 16
18 16
19 12
30 10
30 10
31 14
18 16
18 16
64 37
18 16
18 16
87 55
33 14
32 11
41 11
18 16
18 16
27 10
27 6
66 43
38 7
19 2
50 29
24 4
45 16
47 16
22 11
11 10
11 10
4 2
54 31
53 30
50 25
8 3
8 3
11 10
48 27
48 27
18 16
62 40
64 42
10 10
43 34
39 30
56 34
111 39
29 20
5 5
11 3
11 3
55 26
18 16
18 16
24 9
46 24
31 14
21 3
19 2
74 42
18 14
19 19
19 19
46 21
21 14
19 12
20 6
66 25
11 8
34 18
23 6
23 6
23 12
24 17
24 17
17 15
15 14
14 13
5 2
45 17
11 8
29 14
100 61
83 45
7 6
65 24
45 17
9 1
8 3
8 3
39 15
12 8
43 13
48 28
38 17
47 22
59 25
8 7
8 7
11 10
4 3
8 7
37 24
35 9
56 20
6 0
26 26
26 26
6 0
45 20
46 24
59 24
30 9
30 9
4 3
82 17
53 24
10 3
42 17
12 8
97 55
64 42
64 42
21 3
35 11
40 22
56 23
9 9
9 9
36 24
9 9
9 9
38 28
28 12
28 12
3 1
28 12
28 12
17 17
15 14
15 14
13 13
15 6
39 23
23 23
62 37
79 48
35 16
9 2
9 2
21 15
26 8
43 13
18 16
54 29
34 7
40 22
32 5
21 4
10 9
32 30
19 16
12 1
54 31
54 31
3 2
92 39
19 2
28 25
55 17
61 18
3 3
8 0
9 2
6 0
54 31
54 31
18 18
8 3
8 3
1 1
3 2
28 27
30 19
58 33
56 31
30 9
57 31
58 33
13 6
42 14
39 11
78 44
19 2
37 16
29 12
33 12
34 13
34 7
64 37
50 28
29 8
29 28
66 43
6 6
8 6
50 28
7 6
47 19
45 21
27 7
84 58
8 6
27 14
62 37
64 37
3 3
42 23
14 11
34 9
64 37
64 37
89 65
10 10
11 11
13 5
101 59
74 42
38 29
50 28
64 37
46 27
53 24
19 2
10 10
26 9
19 2
13 12
8 3
8 3
39 35
11 11
10 10
3 2
10 8
84 58
79 46
10 10
11 11
9 8
62 37
64 37
49 24
51 22
51 22
71 33
84 52
26 26
22 15
36 13
2 2
9 8
35 12
44 25
78 39
49 24
50 22
30 11
4 3
7 6
48 16
25 6
32 12
8 7
25 6
25 6
25 3
41 21
51 22
30 12
36 16
49 24
12 11
36 16
49 24
2 2
33 13
36 16
46 26
44 13
53 22
8 0
45 13
34 13
39 19
35 16
49 24
53 24
66 21
24 13
5 4
23 13
35 24
8 1
65 21
56 26
31 30
8 3
8 3
31 10
67 23
56 26
11 10
38 15
70 35
30 17
63 29
62 28
25 13
15 14
22 20
30 10
6 0
25 13
118 73
9 8
9 8
80 16
22 22
22 22
40 20
10 9
10 9
1 1
25 6
25 6
19 19
31 10
53 30
12 11
44 19
111 39
6 6
21 4
17 0
38 19
41 9
44 11
41 18
15 14
15 14
20 11
11 9
23 20
57 32
24 21
11 9
41 21
25 5
26 8
26 22
9 8
9 8
10 9
11 10
10 9
24 6
32 15
52 24
93 62
81 47
49 19
38 25
36 6
12 6
14 0
29 28
59 20
39 10
10 10
6 6
44 43
24 23
41 38
13 5
62 30
25 7
41 22
42 13
58 33
13 9
43 12
43 12
48 27
67 35
34 17
11 10
41 9
41 9
29 29
45 14
58 25
13 5
24 6
37 26
51 45
47 28
56 30
35 6
33 10
33 10
19 18
65 27
59 22
40 18
1 1
8 7
111 39
60 33
24 6
12 11
59 28
59 28
46 14
60 28
59 28
5 4
59 28
60 28
24 15
27 18
28 19
10 3
17 14
86 23
23 2
15 14
15 14
32 10
15 14
15 14
62 24
15 14
15 14
17 13
28 20
28 20
19 18
41 21
43 23
10 8
17 13
8 7
14 8
10 9
11 10
3 2
33 14
39 18
49 22
99 78
40 22
30 5
9 8
9 8
27 10
5 5
11 11
27 6
58 27
24 6
70 42
11 11
59 28
74 40
22 22
33 33
9 8
66 25
68 27
7 5
12 12
12 12
7 6
49 19
63 26
37 9
43 15
43 15
30 30
52 21
52 21
37 12
52 21
52 21
44 17
40 22
57 28
40 20
54 28
30 24
47 23
56 29
30 24
19 2
44 19
131 66
23 14
22 20
35 29
35 34
27 11
27 11
19 1
35 16
8 5
64 37
35 6
33 7
44 27
3 2
3 2
9 8
3 2
3 2
24 20
44 12
35 6
54 25
55 30
59 28
8 1
49 16
62 34
37 9
35 7
46 15
1 1
25 21
27 23
4 1
44 14
49 16
13 10
8 0
8 0
20 9
7 7
49 16
7 7
28 6
30 9
44 20
48 19
89 24
8 7
8 0
8 0
25 4
28 7
28 6
73 47
80 45
80 45
39 11
19 12
20 9
40 12
13 12
13 12
17 0
31 10
39 13
12 4
21 3
19 1
54 28
43 14
80 45
9 8
43 15
43 15
25 1
6 6
72 35
45 18
36 6
30 9
25 13
17 0
52 24
46 26
22 13
13 10
3 2
22 3
19 1
19 16
23 20
13 12
40 22
43 15
43 15
4 2
13 12
12 11
25 6
11 11
27 23
38 19
13 13
11 11
40 20
66 24
89 24
25 6
25 24
25 24
39 17
11 3
11 3
20 14
54 27
26 9
29 29
29 13
29 13
20 18
28 27
6 6
19 13
15 15
17 17
29 29
22 22
36 36
16 9
27 9
53 20
21 14
23 16
17 15
15 14
13 9
10 8
37 14
12 8
58 46
40 5
43 15
43 15
20 6
5 4
64 35
22 22
62 27
52 30
34 12
24 15
24 15
4 1
29 27
24 15
15 12
41 11
89 24
70 40
17 5
15 12
9 8
27 9
11 9
31 5
68 29
63 24
53 20
31 5
35 6
8 3
11 10
11 10
25 7
44 25
6 6
24 9
1 0
11 10
12 1
33 10
33 10
6 5
40 37
25 21
16 12
39 36
25 21
70 42
40 37
40 37
46 17
12 11
1 0
8 7
45 11
11 11
26 8
11 3
11 3
58 29
13 10
13 10
43 21
27 9
27 9
27 9
27 9
27 9
41 15
50 25
57 25
24 10
8 0
8 0
35 28
13 10
39 36
3 2
13 10
25 21
11 5
4 4
38 28
35 14
43 23
35 17
74 51
8 0
8 0
15 13
32 10
40 13
48 28
57 29
34 11
10 8
45 20
32 10
10 9
1 0
11 10
9 8
42 22
18 15
1 1
27 9
27 9
54 22
33 26
24 17
32 20
24 6
25 9
14 13
33 24
28 19
11 2
63 32
26 25
15 6
33 26
24 17
28 1
25 16
73 37
11 10
8 0
8 0
38 21
12 11
11 10
27 9
49 16
5 4
18 9
44 21
52 23
14 14
8 8
39 18
29 8
42 22
42 22
20 6
28 12
24 6
14 14
47 23
56 31
1 1
17 13
50 18
31 15
17 13
30 9
3 3
28 5
15 4
82 17
36 15
39 18
25 13
9 6
9 6
35 26
17 8
17 8
23 15
36 13
32 13
20 18
30 12
32 14
16 16
27 26
25 24
71 46
27 9
27 9
65 27
31 7
45 11
51 24
33 12
33 12
20 15
51 23
13 11
29 20
20 6
20 6
26 7
34 14
55 24
52 32
39 20
8 8
62 28
4 1
1 1
51 22
6 6
6 6
47 28
15 15
36 33
8 6
29 12
44 21
20 9
17 0
17 0
81 47
36 14
51 23
6 0
17 16
5 4
4 2
63 31
63 31
25 13
75 39
77 41
41 26
93 60
93 60
23 8
49 19
33 10
55 17
75 55
61 60
13 10
26 17
31 22
11 10
52 26
52 23
47 23
18 6
18 6
41 12
42 19
13 11
56 30
85 65
27 6
33 12
59 23
39 12
48 15
62 27
62 27
57 34
25 24
27 26
15 14
60 36
53 28
27 26
55 21
66 29
37 27
19 19
65 29
36 5
22 22
31 22
29 9
61 21
66 21
41 21
2 2
1 1
23 13
48 16
49 16
33 19
63 20
42 12
51 24
56 34
55 29
28 4
42 18
63 20
12 1
6 4
63 20
11 10
37 14
33 10
10 8
11 2
11 2
2 2
59 24
59 24
27 10
47 14
42 19
52 33
48 14
30 9
54 23
11 10
11 10
18 8
46 18
13 11
23 22
33 12
28 7
68 41
33 13
12 8
28 7
12 11
12 11
67 40
70 32
59 27
25 1
12 10
13 11
71 35
14 14
31 22
5 2
63 36
38 17
4 1
4 4
8 8
32 12
28 8
28 8
49 15
9 9
9 9
80 16
28 8
28 8
52 32
26 20
26 20
34 14
24 13
24 13
20 9
29 29
22 22
26 20
30 9
49 19
48 28
12 12
8 8
29 13
12 11
1 0
8 0
25 22
23 20
13 4
30 21
29 29
21 4
12 12
4 4
36 10
27 5
28 8
40 19
30 21
31 22
8 0
33 29
33 29
8 6
41 12
27 5
59 31
9 9
9 9
19 2
38 13
45 18
9 2
23 6
36 6
69 32
59 23
39 12
87 55
30 9
33 10
43 43
27 9
27 9
8 8
5 5
5 5
7 6
60 28
47 23
8 0
17 17
5 5
33 13
28 8
28 8
145 106
56 25
107 61
17 0
48 27
49 28
2 1
8 0
8 0
12 11
17 11
14 8
14 11
8 0
8 0
7 7
9 9
9 9
28 10
58 35
47 25
14 13
8 0
8 0
14 14
11 9
11 9
38 29
30 9
30 9
1 1
54 20
55 21
64 42
28 6
28 6
62 40
55 24
27 9
33 15
10 8
27 9
26 21
4 3
8 0
9 9
4 3
8 0
7 6
14 14
42 22
17 0
10 8
11 9
4 3
28 27
28 27
16 15
28 6
34 11
6 4
64 28
64 28
89 24
64 28
64 28
9 8
64 28
64 28
59 43
64 28
64 28
27 9
64 28
64 28
108 68
26 20
26 20
38 17
6 5
6 5
45 16
8 0
4 3
10 9
76 40
1 1
33 10
2 1
24 22
2 2
26 9
17 0
45 13
13 6
4 3
41 16
18 17
18 17
14 14
21 20
6 6
1 1
5 5
52 19
10 10
8 0
8 0
34 12
26 5
49 32
19 13
1 1
9 9
49 19
10 3
4 3
8 0
31 13
50 22
22 13
73 70
27 27
109 68
62 20
42 13
37 12
54 20
54 20
34 32
24 14
24 13
10 1
82 50
59 20

In [100]:
updated_train_data[-5]

{'anchor': [], 'positive': [], 'negative': []}

In [78]:
import pandas as pd
# Load json data into a pandas dataframe
df = pd.read_json("/home/mdafifal.mamun/research/S3M/dataset/EMSE_data/netbeans_2016/netbeans_stacktraces.json")

In [60]:
df.head()

,bug_id,bug_severity,bug_status,comments,component,creation_ts,delta_ts,description,dup_id,exception,keywords,op_sys,priority,product,rep_platform,resolution,short_desc,target_milestone,version,stacktrace
0,755,normal,CLOSED,[],Text,906750420,1230028497,External deleting .java file do not cloze open...,NaN,NaN,,All,P4,platform,All,DUPLICATE,External deleting .java file do not close open...,TBD,3.x,[{'exception': 'java.lang.ArrayIndexOutOfBound...
1,1106,normal,CLOSED,[],-- Other --,917921167,1230029124,This is the Windows Eastern European character...,NaN,NaN,,All,P2,platform,All,FIXED,RESOURCE_ENCODING set to Cp1250 in production ...,TBD,3.x,[{'exception': 'java.io.UnsupportedEncodingExc...
2,1329,normal,CLOSED,[],-- Other --,922132797,1230030864,Exception: /opt/local/jdk1.2/bin/java not foun...,NaN,NaN,,Other,P2,platform,All,FIXED,Execution does not work. In solaris (but maybe...,TBD,3.x,"[{'exception': 'java.io.IOException', 'message..."
3,1331,normal,CLOSED,[],-- Other --,922133018,1230031026,Exception occurred during event dispatching:\n...,NaN,NaN,,All,P2,platform,All,FIXED,"Menu ""Window"" sometimes can not be opened.",TBD,3.x,[{'exception': 'java.lang.NullPointerException...
4,1339,normal,CLOSED,[],Code,922135048,1027092528,[IAN] Problem of browser functionality in Swin...,NaN,NaN,,All,P4,javaee,All,FIXED,Very slow opening of pages with exception (in ...,TBD,3.x,[{'exception': 'javax.swing.text.StateInvarian...

# Analyze Relationship

In [75]:
from pprint import pprint

In [79]:
df_dup = df[df["dup_id"].notna()]

In [77]:
# Convert all dup_id to int
df["dup_id"] = df["dup_id"].apply(lambda x: int(x))

In [74]:
df.head()

,bug_id,bug_severity,bug_status,comments,component,creation_ts,delta_ts,description,dup_id,exception,keywords,op_sys,priority,product,rep_platform,resolution,short_desc,target_milestone,version,stacktrace
818,8811,normal,CLOSED,[],-- Other --,976205998,1229974614,[stable 3.1-22] On reinstaling module exceptio...,8766,NaN,,All,P3,platform,PC,DUPLICATE,ConCurrentModificationException in DataObjectPool,TBD,3.x,[{'exception': 'java.util.ConcurrentModificati...
848,9049,normal,CLOSED,[],-- Other --,979069728,1229981954,While renaming the name of a class and the nam...,8666,NaN,,Windows ME/2000,P1,platform,PC,FIXED,Invalid lock for file - FSException,3.x,3.x,[{'exception': 'org.openide.filesystems.FSExce...
894,9246,normal,CLOSED,[],Unsupported,980514610,1190798053,**WARNING: unexpected null reference in .class...,8117,NaN,,Linux,P4,java,PC,FIXED,NullPointerException at ParsingEnter.attribTre...,3.x,3.x,[{'exception': 'java.lang.NullPointerException...
910,9350,normal,CLOSED,[],Window System,981080000,1229968777,Obeying Exception dialog\n*********** Exceptio...,8868,NaN,,Other,P4,platform,Other,DUPLICATE,Exception when running an Gui app within the GUI,TBD,3.x,[{'exception': '2001java.lang.IllegalArgumentE...
958,9631,major,CLOSED,[],Window System,982196332,1229977917,"In my property editor, in setText, if the valu...",8413,NaN,,All,P3,platform,All,FIXED,Entering incorrect value into property sheet i...,3.x,3.x,"[{'exception': 'java.lang.Exception', 'message..."

In [217]:
def get_row(index):
    row = df_dup.iloc[index]
    # pprint(row)
    dup_id = int(row["dup_id"])
    main_st = df_dup.iloc[index]["stacktrace"][0]
    
    print("Bug id", row["bug_id"], "Dup id", dup_id)
    print("Main Desc", "="*20)
    pprint(df_dup.iloc[index]["description"])
    main_st = [st["function"] for st in main_st["frames"]]
    # pprint(main_st)
    dup_st = df[df["bug_id"] == dup_id]

    print("Dup Desc", "="*20)
    pprint(dup_st.iloc[0]["description"])

    dup_st = dup_st.iloc[0]["stacktrace"][0]
    # pprint(dup_st)
    dup_st = [st.get("function") for st in dup_st["frames"]]

    print("Main", "="*20)
    pprint(list(dict.fromkeys(main_st)))
    print("Dup", "="*20)
    pprint(list(dict.fromkeys(dup_st)))

    return list(dict.fromkeys(main_st)), list(dict.fromkeys(dup_st))

In [218]:
# Good 4, 22, 29, 30
main, dup = get_row(30)

Bug id 10614 Dup id 9794
Main Desc ====================
('I get the attached stack trace when creating a new JPanel\n'
 'using the wizard.  This occurs on the second page (Choose target)\n'
 'but only happens spuriously.\n'
 '\n'
 'Thu Mar 22 21:24:54 EST 2001java.lang.NullPointerException: null\n'
 'java.lang.NullPointerException\n'
 '        at ice.pilots.html4.ThePilot.clear(ice/pilots/html4/ThePilot)\n'
 '        at ice.storm.StormBase.$Gb(ice/storm/StormBase)\n'
 '        at ice.storm.StormBase.$Hb(ice/storm/StormBase)\n'
 '        at ice.storm.DefaultPilotContext.run(ice/storm/DefaultPilotContext)\n'
 '[catch] at java.lang.Thread.run(Thread.java:484)')
Dup Desc ====================
('If I select a package in the explorer and right-click ->New -> choose '
 'something\n'
 '(say Classes->Class), it tries to bring up the Template Chooser step instead '
 'of\n'
 'going directly to the name step and I get this exception.  If I dismiss it '
 'and\n'
 'do it again right away, it works.\n'
 '\n'
 'Thu Feb 22 22:42:31 PST 2001java.lang.InterruptedException: null\n'
 'java.lang.InterruptedException\n'
 '        at ice.storm.ImageCache.<init>(ice/storm/ImageCache)\n'
 '        at ice.storm.ImageCache.getInstance(ice/storm/ImageCache)\n'
 '        at ice.pilots.html4.ObjectPool.clear(ice/pilots/html4/ObjectPool)\n'
 '        at ice.pilots.html4.ThePilot.dispose(ice/pilots/html4/ThePilot)\n'
 '        at\n'
 'ice.storm.DefaultPilotContext.removePilot(ice/storm/DefaultPilotContext)\n'
 '        at ice.storm.Viewport.removePilot(ice/storm/Viewport)\n'
 '        at ice.storm.Viewport.setPilot(ice/storm/Viewport)\n'
 '        at ice.storm.StormBase.$Gb(ice/storm/StormBase)\n'
 '        at ice.storm.StormBase.$Hb(ice/storm/StormBase)\n'
 '        at ice.storm.DefaultPilotContext.run(ice/storm/DefaultPilotContext)\n'
 '[catch] at java.lang.Thread.run(Thread.java:484)')
Main ====================
['ice.pilots.html4.ThePilot.clear',
 'ice.storm.StormBase.$Gb',
 'ice.storm.StormBase.$Hb',
 'ice.storm.DefaultPilotContext.run',
 'java.lang.Thread.run']
Dup ====================
['ice.storm.ImageCache.<init>',
 'ice.storm.ImageCache.getInstance',
 'ice.pilots.html4.ObjectPool.clear',
 'ice.pilots.html4.ThePilot.dispose',
 'ice.storm.DefaultPilotContext.removePilot',
 'ice.storm.Viewport.removePilot',
 'ice.storm.Viewport.setPilot',
 'ice.storm.StormBase.$Gb',
 'ice.storm.StormBase.$Hb',
 'ice.storm.DefaultPilotContext.run',
 'java.lang.Thread.run']

In [41]:
# Sort by creation_ts
df = df.sort_values(by="creation_ts")
df.head()

,bug_id,bug_severity,bug_status,comments,component,creation_ts,delta_ts,description,dup_id,exception,keywords,op_sys,priority,product,rep_platform,resolution,short_desc,target_milestone,version,stacktrace
818,8811,normal,CLOSED,[],-- Other --,976205998,1229974614,[stable 3.1-22] On reinstaling module exceptio...,8766.0,NaN,,All,P3,platform,PC,DUPLICATE,ConCurrentModificationException in DataObjectPool,TBD,3.x,[{'exception': 'java.util.ConcurrentModificati...
848,9049,normal,CLOSED,[],-- Other --,979069728,1229981954,While renaming the name of a class and the nam...,8666.0,NaN,,Windows ME/2000,P1,platform,PC,FIXED,Invalid lock for file - FSException,3.x,3.x,[{'exception': 'org.openide.filesystems.FSExce...
894,9246,normal,CLOSED,[],Unsupported,980514610,1190798053,**WARNING: unexpected null reference in .class...,8117.0,NaN,,Linux,P4,java,PC,FIXED,NullPointerException at ParsingEnter.attribTre...,3.x,3.x,[{'exception': 'java.lang.NullPointerException...
910,9350,normal,CLOSED,[],Window System,981080000,1229968777,Obeying Exception dialog\n*********** Exceptio...,8868.0,NaN,,Other,P4,platform,Other,DUPLICATE,Exception when running an Gui app within the GUI,TBD,3.x,[{'exception': '2001java.lang.IllegalArgumentE...
958,9631,major,CLOSED,[],Window System,982196332,1229977917,"In my property editor, in setText, if the valu...",8413.0,NaN,,All,P3,platform,All,FIXED,Entering incorrect value into property sheet i...,3.x,3.x,"[{'exception': 'java.lang.Exception', 'message..."

In [151]:
from sentence_transformers import SentenceTransformer

sbert_model = SentenceTransformer("/work/disa_lab/afif/projects/deduplication/trained_embedding_models/baai_bge-base-en-v1.5_netbeans_10frames_5train_0trim_4200_traindays/final")

/home/mdafifal.mamun/miniconda3/envs/tracesim/lib/python3.8/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

In [153]:
import os
os.getcwd()

'/home/mdafifal.mamun/research/S3M'

In [154]:
from src.data.formatters import get_formatter

In [156]:
formatter = get_formatter("java", 10)

Selected formatter: java num_frames: 10

In [219]:
formatted_main = formatter.format(main)
formatted_dup = formatter.format(dup)
random_st, _ = get_row(1222)
formatted_random = formatter.format(random_st)

Bug id 42307 Dup id 36909
Main Desc ====================
("Here's the stack trace:\n"
 '\n'
 'Annotation: Exception occurred in Request Processor\n'
 'java.lang.IndexOutOfBoundsException: Index: 0\n'
 '\tat\n'
 'java.util.Collections$EmptyList.get(Collections.java:1628)\n'
 'at\n'
 'org.netbeans.modules.xml.text.completion.XMLCompletionQuery.query(XMLCompletionQuery.java:149)\n'
 'at\n'
 'org.netbeans.editor.ext.Completion.performQuery(Completion.java:581)\n'
 'at\n'
 'org.netbeans.editor.ext.Completion.access$700(Completion.java:47)\n'
 'at\n'
 'org.netbeans.editor.ext.Completion$1$QueryTask.run(Completion.java:511)\n'
 '\tat org.openide.util.Task.run(Task.java:136)\n'
 'at\n'
 'org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:328)\n'
 '[catch] at\n'
 'org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:670)')
Dup Desc ====================
('[Nb build 2003101900, jdk1.4.2] \n'
 ' \n'
 'Steps to reproduce: \n'
 '--------------------------- \n'
 '1) open atached XML document \n'
 "2) put the cursot behaind determined '<' \n"
 '3) press Ctrl+Space \n'
 ' \n'
 'IDE throws: IndexOutOfBoundsException: Index: 0 \n'
 ' \n'
 'Peter looked at this and said it looks like \n'
 'completion connot find the parent element because \n'
 'of unmatched <br>.')
Main ====================
['java.util.Collections$EmptyList.get',
 'org.netbeans.modules.xml.text.completion.XMLCompletionQuery.query',
 'org.netbeans.editor.ext.Completion.performQuery',
 'org.netbeans.editor.ext.Completion.access$700',
 'org.netbeans.editor.ext.Completion$1$QueryTask.run',
 'org.openide.util.Task.run',
 'org.openide.util.RequestProcessor$Task.run',
 'org.openide.util.RequestProcessor$Processor.run']
Dup ====================
['java.util.Collections$EmptyList.get',
 'org.netbeans.modules.xml.text.completion.XMLCompletionQuery.query',
 'org.netbeans.editor.ext.Completion.performQuery',
 'org.netbeans.editor.ext.Completion.access$700',
 'org.netbeans.editor.ext.Completion$1$QueryTask.run',
 'org.openide.util.Task.run',
 'org.openide.util.RequestProcessor$Task.run',
 'org.openide.util.RequestProcessor$Processor.run']

In [196]:
# FInd consine similarity with sentence transformer
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(sbert_model.encode(formatted_main).reshape(1, -1), sbert_model.encode(formatted_dup).reshape(1, -1))

array([[0.8891839]], dtype=float32)

In [216]:
cosine_similarity(sbert_model.encode(formatted_main).reshape(1, -1), sbert_model.encode(formatted_random).reshape(1, -1))

array([[0.30909148]], dtype=float32)

In [15]:
ts = df.iloc[0]["creation_ts"]
# Convert timestamp to date
import datetime
start_date = datetime.datetime.fromtimestamp(ts)

In [16]:

date = datetime.datetime(2005, 12, 21)
diff = date - start_date
diff

datetime.timedelta(days=2643, seconds=39180)

In [20]:
# Add days to the date
new_date = start_date + datetime.timedelta(days=diff.days)

# List all rows that are within the date range
df[(df["creation_ts"] >= start_date.timestamp()) & (df["creation_ts"] <= new_date.timestamp())]

,bug_id,bug_severity,bug_status,comments,component,creation_ts,delta_ts,description,dup_id,exception,keywords,op_sys,priority,product,rep_platform,resolution,short_desc,target_milestone,version,stacktrace
0,755,normal,CLOSED,[],Text,906750420,1230028497,External deleting .java file do not cloze open...,NaN,NaN,,All,P4,platform,All,DUPLICATE,External deleting .java file do not close open...,TBD,3.x,[{'exception': 'java.lang.ArrayIndexOutOfBound...
1,1106,normal,CLOSED,[],-- Other --,917921167,1230029124,This is the Windows Eastern European character...,NaN,NaN,,All,P2,platform,All,FIXED,RESOURCE_ENCODING set to Cp1250 in production ...,TBD,3.x,[{'exception': 'java.io.UnsupportedEncodingExc...
2,1329,normal,CLOSED,[],-- Other --,922132797,1230030864,Exception: /opt/local/jdk1.2/bin/java not foun...,NaN,NaN,,Other,P2,platform,All,FIXED,Execution does not work. In solaris (but maybe...,TBD,3.x,"[{'exception': 'java.io.IOException', 'message..."
3,1331,normal,CLOSED,[],-- Other --,922133018,1230031026,Exception occurred during event dispatching:\n...,NaN,NaN,,All,P2,platform,All,FIXED,"Menu ""Window"" sometimes can not be opened.",TBD,3.x,[{'exception': 'java.lang.NullPointerException...
4,1339,normal,CLOSED,[],Code,922135048,1027092528,[IAN] Problem of browser functionality in Swin...,NaN,NaN,,All,P4,javaee,All,FIXED,Very slow opening of pages with exception (in ...,TBD,3.x,[{'exception': 'javax.swing.text.StateInvarian...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12962,70638,blocker,VERIFIED,[],Refactoring,1135087207,1175623334,"[release50-200512192030, JDK 1.5.0_06]\n\nStep...",70423.0,NaN,,All,P2,editor,All,DUPLICATE,IOE thrown when doing Refac. Push Down,5.x,5.x,[{'exception': 'javax.jmi.reflect.InvalidObjec...
12963,70640,blocker,RESOLVED,[],Code,1135089571,1135175738,Ran into this one during the attempt to delete...,NaN,NaN,,Windows XP,P3,guibuilder,PC,WORKSFORME,java.lang.NullPointerException at org.netbeans...,TBD,5.x,[{'exception': 'java.lang.NullPointerException...
12964,70644,blocker,VERIFIED,[],Autoupdate,1135092195,1161621560,Since the following commit it is impossible to...,NaN,NaN,,All,P1,platform,All,FIXED,Unable to connect to UC - stream closed,6.x,6.x,"[{'exception': 'java.io.IOException', 'message..."
12965,70650,blocker,VERIFIED,[],EJB,1135097572,1141651172,build 200512192030\n\nwhen creating session be...,NaN,NaN,,All,P2,javaee,Macintosh,FIXED,java.lang.reflect.UndeclaredThrowableException...,5.x,5.x,[{'exception': 'java.lang.reflect.UndeclaredTh...
12966,70651,blocker,RESOLVED,[],-- Other --,1135097735,1194270284,IDE version: 5.0 Dev 200512182080\nJDK version...,NaN,NaN,,Linux,P3,editor,All,WORKSFORME,IDE freezes after successive keystroke on read...,6.x,5.x,[{'exception': 'java.lang.reflect.UndeclaredTh...

In [3]:
df.iloc[0]["stacktrace"]

[{'exception': 'java.io.InterruptedIOException',
  'message': 'Read timed out',
  'frames': [{'function': 'java.net.SocketInputStream.socketRead',
    'file': 'NativeMethod',
    'fileline': None,
    'depth': 0},
   {'function': 'java.net.SocketInputStream.read',
    'file': 'SocketInputStream.java(CompiledCode',
    'fileline': None,
    'depth': 1},
   {'function': 'java.io.BufferedInputStream.fill',
    'file': 'BufferedInputStream.java(CompiledCode',
    'fileline': None,
    'depth': 2},
   {'function': 'java.io.BufferedInputStream.read',
    'file': 'BufferedInputStream.java(CompiledCode',
    'fileline': None,
    'depth': 3},
   {'function': 'org.eclipse.vcm.internal.core.ccvs.client.Connection.readLineOrUntil',
    'file': 'Connection.java(CompiledCode',
    'fileline': None,
    'depth': 4},
   {'function': 'org.eclipse.vcm.internal.core.ccvs.client.Connection.readToken',
    'file': 'Connection.java(CompiledCode',
    'fileline': None,
    'depth': 5},
   {'function': 'org.eclipse.vcm.internal.core.ccvs.client.Client.processResponses',
    'file': 'Client.java(CompiledCode',
    'fileline': None,
    'depth': 6},
   {'function': 'org.eclipse.vcm.internal.core.ccvs.client.Client.processResponses',
    'file': 'Client.java',
    'fileline': 397,
    'depth': 7},
   {'function': 'org.eclipse.vcm.internal.core.ccvs.client.Client.execute',
    'file': 'Client.java',
    'fileline': 257,
    'depth': 8},
   {'function': 'org.eclipse.vcm.internal.core.ccvs.CVSAdapter.createProjectVersion',
    'file': 'CVSAdapter.java',
    'fileline': 313,
    'depth': 9},
   {'function': 'org.eclipse.vcm.internal.core.SharingManager.createProjectVersion',
    'file': 'SharingManager.java',
    'fileline': 71,
    'depth': 10},
   {'function': 'org.eclipse.vcm.internal.ui.actions.VersionAction$VersionLocalOperation.version',
    'file': 'VersionAction.java',
    'fileline': 121,
    'depth': 11},
   {'function': 'org.eclipse.vcm.internal.ui.VersionResourcesOperation.run',
    'file': 'VersionResourcesOperation.java',
    'fileline': 45,
    'depth': 12},
   {'function': 'org.eclipse.jface.operation.ModalContext$ModalContextThread.run',
    'file': 'ModalContext.java',
    'fileline': 98,
    'depth': 13}],
  'nested': []}]

In [68]:
updated_train_data

[{'anchor': ['org.eclipse.team.internal.ccvs.ui.actions.workspaceaction.beginexecution']},
 {'positive': ['org.eclipse.team.internal.ccvs.ui.actions.workspaceaction.beginexecution']},
 {'negative': ['com.oti.eclipsetools.internal.create.pluginimportwizard.run',
   'org.eclipse.debug.internal.core.launchmanager.resourcechanged',
   'org.eclipse.core.internal.events.resourcedelta.accept',
   'org.eclipse.debug.internal.core.launchmanagerlaunchmanagervisitor.visit']},
 {'anchor': ['org.eclipse.jdt.ui.actions.renameaction.run',
   'org.eclipse.jdt.internal.ui.refactoring.actions.renamejavaelementaction.run',
   'org.eclipse.jdt.internal.ui.refactoring.refactoringsupportfactoryrenamesupport.rename',
   'org.eclipse.jdt.internal.ui.refactoring.actions.performrefactoringutil.performrefactoring',
   'org.eclipse.jdt.internal.ui.refactoring.performchangeoperation.run',
   'org.eclipse.jdt.internal.ui.refactoring.performchangeoperation.executechange',
   'org.eclipse.jdt.internal.core.builder.javabuilder.getlaststate',
   'org.eclipse.jdt.internal.core.javamodelmanager.getlastbuiltstate',
   'org.eclipse.jdt.internal.core.javamodelmanager.readstate',
   'org.eclipse.jdt.internal.core.builder.javabuilder.readstate',
   'org.eclipse.jdt.internal.core.builder.state.read',
   'org.eclipse.jdt.internal.core.javaproject.getoption',
   'org.eclipse.jdt.internal.core.javaproject.getpreferences',
   'org.eclipse.jdt.internal.core.javaproject.loadpreferences']},
 {'positive': ['org.eclipse.jdt.internal.core.deltaprocessor.resourcechanged',
   'org.eclipse.jdt.internal.core.deltaprocessor.updateclasspathmarkers',
   'org.eclipse.jdt.internal.core.javaproject.getoption',
   'org.eclipse.jdt.internal.core.javaproject.getpreferences',
   'org.eclipse.jdt.internal.core.javaproject.loadpreferences']},
 {'negative': ['org.eclipse.update.internal.ui.wizards.installwizard.run',
   'org.eclipse.update.internal.ui.wizards.installwizard.access',
   'org.eclipse.update.internal.ui.wizards.installwizard.execute',
   'org.eclipse.update.internal.core.configuredsite.install',
   'org.eclipse.update.internal.core.sitefile.install',
   'org.eclipse.update.core.feature.install',
   'org.eclipse.update.internal.core.featurepackagedcontentprovider.getpluginentryarchivereferences',
   'org.eclipse.update.core.featurecontentprovider.aslocalreference',
   'org.eclipse.update.core.contentreference.getinputsize',
   'org.eclipse.update.internal.core.updatemanagerutils.checkconnectionresult',
   'java.net.httpurlconnection.getresponsecode',
   'sun.net.www.protocol.http.httpurlconnection.getinputstream',
   'sun.net.www.protocol.http.httpurlconnection.connect',
   'sun.net.www.http.httpclient.new',
   'sun.net.www.http.httpclient.init',
   'sun.net.www.http.httpclient.openserver',
   'sun.net.networkclient.doconnect',
   'java.net.socket.init',
   'java.net.plainsocketimpl.connect',
   'java.net.plainsocketimpl.connecttoaddress',
   'java.net.plainsocketimpl.doconnect',
   'java.net.plainsocketimpl.socketconnect']},
 {'anchor': ['org.eclipse.debug.internal.ui.actions.openlaunchconfigurationsaction.run',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.open',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.dolastlaunchedconfig',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.createcontents',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.doinitialtreeselection',
   'org.eclipse.jface.viewers.viewer.setselection',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.selectionchanged',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.setlaunchconfiguration',
   'org.eclipse.pde.internal.ui.launcher.workbenchlaunchertabgroup.initializefrom',
   'org.eclipse.pde.internal.ui.launcher.workbenchlaunchertabgroup.run',
   'org.eclipse.pde.internal.ui.launcher.advancedlaunchertab.initialize',
   'org.eclipse.pde.internal.ui.launcher.advancedlaunchertab.computeinitialcheckstate',
   'java.util.hashtable.put']},
 {'positive': ['org.eclipse.debug.internal.ui.actions.openlaunchconfigurationsaction.run',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.open',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.dolastlaunchedconfig',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.createcontents',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.doinitialtreeselection',
   'org.eclipse.jface.viewers.viewer.setselection',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.selectionchanged',
   'org.eclipse.debug.internal.ui.launchconfigurations.launchconfigurationdialog.setlaunchconfiguration',
   'org.eclipse.pde.internal.ui.launcher.workbenchlaunchertabgroup.initializefrom',
   'org.eclipse.pde.internal.ui.launcher.workbenchlaunchertabgroup.run',
   'org.eclipse.pde.internal.ui.launcher.advancedlaunchertab.initialize',
   'org.eclipse.pde.internal.ui.launcher.advancedlaunchertab.computeinitialcheckstate',
   'java.util.hashtable.put']},
 {'negative': ['org.eclipse.jdt.internal.core.newbuilder.javabuilder.build',
   'org.eclipse.jdt.internal.core.newbuilder.javabuilder.buildall',
   'org.eclipse.jdt.internal.core.newbuilder.batchimagebuilder.build',
   'org.eclipse.jdt.internal.core.newbuilder.abstractimagebuilder.compile',
   'org.eclipse.jdt.internal.core.newbuilder.buildnotifier.abouttocompile',
   'java.lang.string.substring']},
 {'anchor': ['org.eclipse.ui.internal.editormanager.saveeditor',
   'org.eclipse.ui.internal.editormanager.runprogressmonitoroperation',
   'com.ibm.etools.ctc.flow.ui.microflowmultipageeditor.dosave',
   'com.ibm.etools.ctc.flow.ui.microflowresourcemanager.dosave',
   'org.eclipse.ui.views.tasklist.tasklistcontentprovider.resourcechanged']},
 {'positive': ['org.eclipse.ui.internal.editormanager.saveeditor',
   'org.eclipse.ui.internal.editormanager.runprogressmonitoroperation',
   'org.eclipse.jdt.internal.ui.javaeditor.compilationuniteditor.performsaveoperation',
   'org.eclipse.ui.texteditor.abstracttexteditor.performsaveoperation',
   'org.eclipse.ui.views.tasklist.tasklistcontentprovider.resourcechanged']},
 {'negative': ['slimlauncher.main',
   'org.eclipse.debug.internal.ui.actions.controlactiondelegate.run']},
 {'anchor': ['org.eclipse.jdt.internal.core.search.processing.jobmanager.run',
   'org.eclipse.jdt.internal.core.search.indexing.indexmanager.notifyidle',
   'org.eclipse.jdt.internal.core.search.indexing.indexmanager.saveindexes',
   'org.eclipse.jdt.internal.core.index.impl.index.save',
   'org.eclipse.jdt.internal.core.index.impl.index.merge',
   'org.eclipse.jdt.internal.core.index.impl.mergefactory.merge',
   'org.eclipse.jdt.internal.core.index.impl.mergefactory.mergereferences',
   'org.eclipse.jdt.internal.core.index.impl.blocksindexinput.movetonextwordentry',
   'org.eclipse.jdt.internal.core.index.impl.gammacompressedindexblock.nextentry',
   'org.eclipse.jdt.internal.core.index.impl.codebytestream.readgamma',
   'org.eclipse.jdt.internal.core.index.impl.codebytestream.readunary']},
 {'positive': ['org.eclipse.jdt.internal.core.search.processing.jobmanager.run',
   'org.eclipse.jdt.internal.core.search.indexing.indexmanager.notifyidle',
   'org.eclipse.jdt.internal.core.search.indexing.indexmanager.saveindexes',
   'org.eclipse.jdt.internal.core.index.impl.index.save',
   'org.eclipse.jdt.internal.core.index.impl.index.merge',
   'org.eclipse.jdt.internal.core.index.impl.mergefactory.merge',
   'org.eclipse.jdt.internal.core.index.impl.mergefactory.mergereferences',
   'org.eclipse.jdt.internal.core.index.impl.blocksindexinput.movetonextwordentry',
   'org.eclipse.jdt.internal.core.index.impl.gammacompressedindexblock.nextentry',
   'org.eclipse.jdt.internal.core.index.impl.codebytestream.readgamma',
   'org.eclipse.jdt.internal.core.index.impl.codebytestream.readunary']},
 {'negative': ['org.eclipse.jdt.internal.debug.core.eventdispatcher.run',
   'org.eclipse.jdi.internal.event.eventqueueimpl.remove',
   'org.eclipse.jdi.internal.event.eventsetimpl.read',
   'org.eclipse.jdi.internal.event.eventimpl.read',
   'org.eclipse.jdi.internal.request.eventrequestmanagerimpl.findrequest']},
 {'anchor': ['org.eclipse.core.internal.boot.internalbootloader.getrunnable',
   'org.eclipse.core.internal.runtime.internalplatform.loadergetrunnable',
   'org.eclipse.core.internal.plugins.configurationelement.createexecutableextension',
   'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
   'org.eclipse.core.internal.boot.delegatingurlclassloader.findclassprerequisites',
   'org.eclipse.core.internal.boot.delegatingurlclassloaderdelegateloader.loadclass',
   'org.eclipse.core.internal.boot.delegatingurlclassloader.access',
   'org.eclipse.core.internal.plugins.pluginclassloader.findclassparentsself',
   'org.eclipse.core.internal.plugins.pluginclassloader.activateplugin',
   'org.eclipse.core.internal.plugins.plugindescriptor.run',
   'org.eclipse.core.resources.resourcesplugin.startup',
   'org.eclipse.core.internal.resources.workspace.open',
   'org.eclipse.core.internal.resources.localmetaarea.readworkspace',
   'org.eclipse.core.internal.resources.modelobjectreader.read',
   'javax.xml.parsers.documentbuilderfactory.newinstance']},
 {'positive': ['org.eclipse.core.internal.boot.internalbootloader.getrunnable',
   'org.eclipse.core.internal.runtime.internalplatform.loadergetrunnable',
   'org.eclipse.core.internal.plugins.configurationelement.createexecutableextension',
   'org.eclipse.core.internal.plugins.plugindescriptor.createexecutableextension',
   'org.eclipse.core.internal.boot.delegatingurlclassloader.findclassprerequisites',
   'org.eclipse.core.internal.boot.delegatingurlclassloaderdelegateloader.loadclass',
   'org.eclipse.core.internal.boot.delegatingurlclassloader.access',
   'org.eclipse.core.internal.plugins.pluginclassloader.findclassparentsself',
   'org.eclipse.core.internal.plugins.pluginclassloader.activateplugin',
   'org.eclipse.core.internal.plugins.plugindescriptor.run',
   'org.eclipse.core.resources.resourcesplugin.startup',
   'org.eclipse.core.internal.resources.workspace.open',
   'org.eclipse.core.internal.resources.localmetaarea.readworkspace',
   'org.eclipse.core.internal.resources.modelobjectreader.read',
   'javax.xml.parsers.documentbuilderfactory.newinstance']},
 {'negative': ['eclipseruntimelauncher.main',
   'org.eclipse.ui.internal.exceptionhandler.handleexception',
   'org.eclipse.ui.internal.exceptionhandler.openquestiondialog',
   'org.eclipse.ui.internal.dialogs.internalerrordialog.openquestion',
   'org.eclipse.debug.internal.ui.debugactiongroupsmanager.run',
   'org.eclipse.debug.internal.ui.debugactiongroupsmanager.updatedebugactiongroups',
   'org.eclipse.debug.internal.ui.debugactiongroupsmanager.processcontributionitems']},
 {'anchor': ['org.eclipse.pde.internal.ui.wizards.imports.pluginimportwizard.run',
   'org.eclipse.jdt.internal.core.deltaprocessor.resourcechanged',
   'org.eclipse.jdt.internal.core.javamodelmanager.fire',
   'org.eclipse.jdt.internal.core.javamodelmanager.run',
   'org.eclipse.jdt.internal.debug.ui.javamodellistener.elementchanged',
   'org.eclipse.debug.internal.core.breakpointmanager.getbreakpoints',
   'org.eclipse.debug.internal.core.breakpointmanager.initializebreakpoints',
   'org.eclipse.debug.internal.core.breakpointmanager.loadbreakpoints',
   'org.eclipse.debug.internal.core.breakpointmanager.addbreakpoints',
   'org.eclipse.core.internal.resources.workspace.beginoperation']},
 {'positive': ['org.eclipse.ui.internal.keytable.handleevent',
   'org.eclipse.ui.internal.keybindingmenu.keypressed',
   'org.eclipse.ui.internal.registry.acceleratorscope.processkey',
   'org.eclipse.ui.internal.registry.acceleratorscopeacceleratoraction.run',
   'org.eclipse.ui.internal.editormanager.saveeditor',
   'org.eclipse.ui.internal.editormanager.runprogressmonitoroperation',
   'org.eclipse.jdt.internal.ui.javaeditor.compilationuniteditor.performsaveoperation',
   'org.eclipse.ui.texteditor.abstracttexteditor.performsaveoperation',
   'org.eclipse.jdt.internal.core.deltaprocessor.resourcechanged',
   'org.eclipse.jdt.internal.core.javamodelmanager.fire',
   'org.eclipse.jdt.internal.core.javamodelmanager.run',
   'org.eclipse.jdt.internal.debug.ui.javamodellistener.elementchanged',
   'org.eclipse.debug.internal.core.breakpointmanager.getbreakpoints',
   'org.eclipse.debug.internal.core.breakpointmanager.initializebreakpoints',
   'org.eclipse.debug.internal.core.breakpointmanager.loadbreakpoints',
   'org.eclipse.debug.internal.core.breakpointmanager.addbreakpoints',
   'org.eclipse.core.internal.resources.workspace.beginoperation']},
 {'negative': ['org.eclipse.ui.internal.editormanager.saveeditor',
   'org.eclipse.ui.internal.editormanager.runprogressmonitoroperation',
   'org.eclipse.jdt.internal.ui.javaeditor.compilationuniteditor.performsaveoperation',
   'org.eclipse.ui.texteditor.abstracttexteditor.performsaveoperation',
   'org.eclipse.jdt.internal.core.newbuilder.javabuilder.build',
   'org.eclipse.jdt.internal.core.newbuilder.javabuilder.builddeltas',
   'org.eclipse.jdt.internal.core.newbuilder.javabuilder.buildall',
   'org.eclipse.jdt.internal.core.newbuilder.batchimagebuilder.build',
   'org.eclipse.jdt.internal.core.newbuilder.abstractimagebuilder.compile',
   'org.eclipse.jdt.internal.compiler.compiler.begintocompile',
   'org.eclipse.jdt.internal.compiler.lookup.lookupenvironment.buildtypebindings',
   'org.eclipse.jdt.internal.compiler.lookup.compilationunitscope.buildtypebindings',
   'org.eclipse.jdt.internal.compiler.lookup.lookupenvironment.ispackage',
   'org.eclipse.jdt.internal.core.newbuilder.nameenvironment.ispackage',
   'org.eclipse.jdt.internal.core.newbuilder.classpathjar.ispackage']},
 {'anchor': ['org.eclipse.core.internal.boot.internalbootloader.shutdown',
   'org.eclipse.core.internal.runtime.internalplatform.loadershutdown',
   'org.eclipse.core.internal.plugins.pluginregistry.shutdown',
   'org.eclipse.core.internal.plugins.pluginregistry.shutdownplugins',
   'org.eclipse.core.internal.plugins.pluginregistry.accept',
   'org.eclipse.core.internal.plugins.pluginregistry.visit',
   'org.eclipse.core.internal.plugins.pluginregistry.run',
   'org.eclipse.pde.internal.core.pdecore.shutdown',
   'org.eclipse.pde.internal.core.pluginmodelmanager.shutdown']},
 {'positive': ['org.eclipse.core.internal.boot.internalbootloader.shutdown',
   'org.eclipse.core.internal.runtime.internalplatform.loadershutdown',
   'org.eclipse.core.internal.plugins.pluginregistry.shutdown',
   'org.eclipse.core.internal.plugins.pluginregistry.shutdownplugins',
   'org.eclipse.core.internal.plugins.pluginregistry.accept',
   'org.eclipse.core.internal.plugins.pluginregistry.visit',
   'org.eclipse.core.internal.plugins.pluginregistry.run',
   'org.eclipse.pde.internal.core.pdecore.shutdown',
   'org.eclipse.pde.internal.core.pluginmodelmanager.shutdown']},
 {'negative': ['org.eclipse.jdt.core.dom.expression.resolvetypebinding',
   'org.eclipse.jdt.core.dom.defaultbindingresolver.resolveexpressiontype']},
 {'anchor': ['org.eclipse.swt.examples.controlexample.controlexample.main',
   'org.eclipse.swt.examples.controlexample.coolbartabcoolitemselectionlistener.widgetselected']},
 {'positive': ['org.eclipse.swt.examples.controlexample.controlexample.main',
   'org.eclipse.swt.examples.controlexample.coolbartabcoolitemselectionlistener.widgetselected']},
 {'negative': ['org.eclipse.ui.internal.editormanager.saveeditor',
   'org.eclipse.ui.internal.editormanager.runprogressmonitoroperation',
   'org.eclipse.jdt.internal.ui.javaeditor.compilationuniteditor.performsaveoperation',
   'org.eclipse.ui.texteditor.abstracttexteditor.performsaveoperation',
   'org.eclipse.ui.texteditor.abstracttexteditor.execute',
   'org.eclipse.ui.texteditor.abstractdocumentprovider.savedocument',
   'org.eclipse.jdt.internal.ui.javaeditor.compilationunitdocumentprovider.dosavedocument',
   'org.eclipse.jdt.internal.core.workingcopy.reconcile',
   'org.eclipse.jdt.internal.core.javamodelmanager.fire',
   'org.eclipse.jdt.internal.ui.javaeditor.javaoutlinepageelementchangedlistener.elementchanged',
   'org.eclipse.swt.widgets.control.getdisplay']},
 {'anchor': ['org.eclipse.swt.internal.gtk.os.gtk_main_iteration',
   'org.eclipse.swt.widgets.table.processevent',
   'org.eclipse.swt.widgets.widget.processevent',
   'org.eclipse.swt.widgets.table.processmousedown',
   'org.eclipse.swt.widgets.composite.processmousedown',
   'org.eclipse.swt.widgets.control.processmousedown',
   'org.eclipse.swt.widgets.menu.setvisible']},
 {'positive': ['org.eclipse.swt.internal.gtk.os.gtk_main_iteration',
   'org.eclipse.swt.widgets.table.processevent',
   'org.eclipse.swt.widgets.widget.processevent',
   'org.eclipse.swt.widgets.table.processmousedown',
   'org.eclipse.swt.widgets.composite.processmousedown',
   'org.eclipse.swt.widgets.control.processmousedown',
   'org.eclipse.swt.widgets.menu.setvisible']},
 {'negative': ['org.eclipse.ui.texteditor.abstracttexteditor.mousedoubleclick',
   'org.eclipse.ui.texteditor.abstracttexteditor.triggeraction',
   'org.eclipse.ui.texteditor.markerruleraction.run',
   'org.eclipse.jdt.internal.ui.javaeditor.breakpointruleraction.addmarker',
   'org.eclipse.jdt.debug.core.jdidebugmodel.linebreakpointexists']},
 {'anchor': ['org.eclipse.swt.internal.gtk.os.gtk_main_iteration',
   'org.eclipse.swt.widgets.widget.processevent',
   'org.eclipse.swt.widgets.composite.processmousedown',
   'org.eclipse.swt.widgets.control.processmousedown',
   'org.eclipse.swt.widgets.menu.setvisible']},
 {'positive': ['org.eclipse.swt.internal.gtk.os.gtk_main_iteration',
   'org.eclipse.swt.widgets.table.processevent',
   'org.eclipse.swt.widgets.widget.processevent',
   'org.eclipse.swt.widgets.table.processmousedown',
   'org.eclipse.swt.widgets.composite.processmousedown',
   'org.eclipse.swt.widgets.control.processmousedown',
   'org.eclipse.swt.widgets.menu.setvisible']},
 {'negative': ['org.eclipse.swt.custom.ctabfolder.access',
   'org.eclipse.swt.custom.ctabfolder.closenotify',
   'org.eclipse.ui.internal.editorworkbook.itemclosed',
   'org.eclipse.ui.internal.editorpane.dohide',
   'org.eclipse.ui.internal.workbenchpageactionswitcher.updateactivepart',
   'org.eclipse.ui.internal.workbenchpage.updateactionbars',
   'org.eclipse.ui.internal.workbenchwindow.updateactionbars',
   'org.eclipse.jface.action.menumanager.updateall',
   'org.eclipse.jface.action.menumanager.updateall',
   'org.eclipse.ui.internal.reopeneditormenu.fill',
   'org.eclipse.ui.internal.reopeneditormenu.calctext',
   'java.lang.string.substring']},
 {'anchor': ['org.eclipse.core.internal.boot.internalbootloader.shutdown',
   'org.eclipse.core.internal.runtime.internalplatform.loadershutdown',
   'org.eclipse.core.internal.plugins.pluginregistry.shutdown',
   'org.eclipse.core.internal.plugins.pluginregistry.shutdownplugins',
   'org.eclipse.core.internal.plugins.pluginregistry.accept',
   'org.eclipse.core.internal.plugins.pluginregistry.visit',
   'org.eclipse.core.internal.plugins.pluginregistry.run',
   'org.eclipse.pde.internal.core.pdecore.shutdown',
   'org.eclipse.pde.internal.core.pluginmodelmanager.shutdown']},
 {'positive': ['org.eclipse.core.internal.boot.internalbootloader.shutdown',
   'org.eclipse.core.internal.runtime.internalplatform.loadershutdown',
   'org.eclipse.core.internal.plugins.pluginregistry.shutdown',
   'org.eclipse.core.internal.plugins.pluginregistry.shutdownplugins',
   'org.eclipse.core.internal.plugins.pluginregistry.accept',
   'org.eclipse.core.internal.plugins.pluginregistry.visit',
   'org.eclipse.core.internal.plugins.pluginregistry.run',
   'org.eclipse.pde.internal.core.pdecore.shutdown',

In [ ]:
frame_freq

{'org.eclipse.swt.widgets.display.readanddispatch': 8569,
 'java.lang.reflect.method.invoke': 8329,
 'sun.reflect.delegatingmethodaccessorimpl.invoke': 7803,
 'sun.reflect.nativemethodaccessorimpl.invoke': 7644,
 'org.eclipse.swt.widgets.eventtable.sendevent': 7112,
 'org.eclipse.swt.widgets.widget.sendevent': 6946,
 'org.eclipse.core.runtime.adaptor.eclipsestarter.run': 6201,
 'org.eclipse.ui.internal.workbench.runeventloop': 6006,
 'org.eclipse.ui.internal.workbench.createandrunworkbench': 5721,
 'org.eclipse.ui.platformui.createandrunworkbench': 5716,
 'org.eclipse.ui.internal.workbench.runui': 5474,
 'org.eclipse.swt.widgets.display.rundeferredevents': 4871,
 'org.eclipse.core.launcher.main.main': 4799,
 'org.eclipse.core.launcher.main.run': 4737,
 'org.eclipse.core.launcher.main.basicrun': 4732,
 'org.eclipse.ui.internal.workbench.run': 4363,
 'org.eclipse.core.runtime.platform.run': 3834,
 'org.eclipse.swt.custom.busyindicator.showwhile': 3696,
 'org.eclipse.core.runtime.internal.adaptor.eclipseapplauncher.start': 3683,
 'org.eclipse.core.runtime.internal.adaptor.eclipseapplauncher.runapplication': 3668,
 'org.eclipse.core.internal.runtime.platformactivator.run': 3213,
 'org.eclipse.ui.internal.ide.ideapplication.run': 3180,
 'org.eclipse.swt.widgets.display.windowproc': 3156,
 'org.eclipse.core.runtime.saferunner.run': 2935,
 'org.eclipse.ui.internal.workbench.access': 2922,
 'org.eclipse.core.databinding.observable.realm.runwithdefault': 2843,
 'org.eclipse.core.internal.runtime.internalplatform.run': 2810,
 'org.eclipse.swt.widgets.control.windowproc': 2798,
 'org.eclipse.core.internal.jobs.worker.run': 2772,
 'org.eclipse.equinox.launcher.main.basicrun': 2768,
 'org.eclipse.equinox.launcher.main.invokeframework': 2768,
 'org.eclipse.equinox.launcher.main.run': 2764,
 'org.eclipse.equinox.internal.app.eclipseapphandle.run': 2743,
 'org.eclipse.ui.internal.ide.application.ideapplication.start': 2507,
 'org.eclipse.swt.widgets.typedlistener.handleevent': 2377,
 'org.eclipse.swt.widgets.synchronizer.runasyncmessages': 2102,
 'org.eclipse.jface.action.actioncontributionitem.handlewidgetselection': 2070,
 'org.eclipse.jface.window.window.open': 2061,
 'org.eclipse.jface.action.actioncontributionitem.access': 2044,
 'org.eclipse.swt.widgets.display.runasyncmessages': 2031,
 'org.eclipse.jface.action.action.runwithevent': 2007,
 'org.eclipse.swt.custom.styledtextrenderer.gettextlayout': 2007,
 'org.eclipse.swt.custom.styledtext.setcaretlocation': 1977,
 'org.eclipse.swt.custom.styledtext.getpointatoffset': 1975,
 'org.eclipse.core.launcher.main.invokeframework': 1795,
 'org.eclipse.jface.window.window.runeventloop': 1769,
 'org.eclipse.jface.action.actioncontributionitem.handleevent': 1758,
 'org.eclipse.core.internal.resources.workspace.run': 1678,
 'org.eclipse.swt.widgets.runnablelock.run': 1619,
 'org.eclipse.swt.swt.error': 1562,
 'org.eclipse.equinox.launcher.main.main': 1369,
 'org.eclipse.core.internal.boot.internalbootloader.run': 1292,
 'org.eclipse.core.boot.bootloader.run': 1291,
 'org.eclipse.jface.util.saferunnable.run': 1007,
 'org.eclipse.ui.internal.jfaceutil.run': 1004,
 'org.eclipse.team.svn.core.operation.abstractactionoperation.run': 983,
 'org.eclipse.jface.operation.modalcontext.run': 965,
 'org.eclipse.team.svn.core.utility.progressmonitorutility.dotask': 958,
 'org.eclipse.swt.internal.win.os.dispatchmessage': 953,
 'org.eclipse.swt.internal.win.os.dispatchmessagew': 952,
 'org.eclipse.core.internal.events.buildmanager.basicbuild': 896,
 'org.eclipse.e.ui.internal.workbench.swt.partrenderingengine.run': 893,
 'org.eclipse.core.internal.events.buildmanager.run': 888,
 'org.eclipse.swt.internal.win.os.defwindowprocw': 860,
 'org.eclipse.swt.internal.win.os.defwindowproc': 856,
 'org.eclipse.ui.internal.workbenchpage.run': 853,
 'org.eclipse.jface.viewers.structuredviewer.run': 824,
 'org.eclipse.jface.dialogs.dialog.widgetselected': 749,
 'org.eclipse.jface.util.openstrategy.access': 744,
 'org.eclipse.ui.actions.workspacemodifyoperation.run': 738,
 'org.eclipse.ui.internal.workbenchpage.access': 738,
 'org.eclipse.swt.widgets.scrollable.callwindowproc': 732,
 'org.eclipse.swt.widgets.widget.notifylisteners': 723,
 'org.eclipse.ui.internal.workbenchwindow.run': 721,
 'org.eclipse.core.commands.command.executewithchecks': 690,
 'org.eclipse.core.commands.parameterizedcommand.executewithchecks': 674,
 'org.eclipse.swt.widgets.widget.sendkeyevent': 659,
 'org.eclipse.ui.internal.handlers.handlerservice.executecommand': 650,
 'org.eclipse.jface.util.openstrategy.handleevent': 643,
 'org.eclipse.team.svn.core.operation.loggedoperation.run': 628,
 'org.eclipse.team.svn.core.utility.progressmonitorutility.dotaskexternal': 625,
 'org.eclipse.swt.widgets.composite.releasechildren': 619,
 'org.eclipse.ui.internal.keys.workbenchkeyboard.processkeyevent': 619,
 'java.lang.thread.run': 615,
 'java.lang.classloader.loadclass': 609,
 'org.eclipse.swt.widgets.display.filterevent': 607,
 'org.eclipse.ui.internal.keys.workbenchkeyboard.press': 604,
 'org.eclipse.ui.internal.keys.workbenchkeyboard.executecommand': 602,
 'org.eclipse.jface.operation.modalcontextmodalcontextthread.run': 584,
 'org.eclipse.jface.window.applicationwindow.run': 570,
 'org.eclipse.ui.internal.keys.workbenchkeyboard.access': 564,
 'org.eclipse.ui.internal.keys.workbenchkeyboard.filterkeysequencebindings': 564,
 'org.eclipse.ui.internal.workbenchpage.openeditor': 563,
 'org.eclipse.jface.operation.modalcontext.runincurrentthread': 558,
 'org.eclipse.swt.widgets.widget.error': 556,
 'org.eclipse.swt.widgets.decorations.windowproc': 553,
 'org.eclipse.jface.viewers.structuredviewer.preservingselection': 549,
 'org.eclipse.ui.internal.workbenchpage.busyopeneditor': 547,
 'org.eclipse.ui.internal.workbenchpartreference.getpart': 540,
 'org.eclipse.jdt.ui.actions.selectiondispatchaction.run': 539,
 'org.eclipse.jdt.ui.actions.selectiondispatchaction.dispatchrun': 539,
 'org.eclipse.jdt.internal.core.javamodeloperation.run': 485,
 'org.eclipse.ui.internal.pluginaction.runwithevent': 483,
 'org.eclipse.core.internal.events.buildmanager.build': 454,
 'org.eclipse.swt.widgets.control.wm_char': 446,
 'org.eclipse.jface.wizard.wizarddialog.buttonpressed': 441,
 'org.eclipse.swt.widgets.widget.release': 441,
 'org.eclipse.ui.internal.workbenchpage.busyopeneditorbatched': 426,
 'org.eclipse.core.internal.resources.internalworkspacejob.run': 425,
 'org.eclipse.ui.internal.keys.workbenchkeyboardkeydownfilter.handleevent': 402,
 'org.eclipse.ui.internal.editormanager.run': 396,
 'org.eclipse.ui.internal.workbench.init': 392,
 'org.eclipse.ui.internal.workbench.restorestate': 390,
 'javax.servlet.http.httpservlet.service': 389,
 'org.eclipse.jface.viewers.editingsupport.savecelleditorvalue': 389,
 'org.eclipse.jface.viewers.columnviewereditor.applyeditorvalue': 389,
 'java.lang.throwable.init': 388,
 'java.security.accesscontroller.doprivileged': 388,
 'org.eclipse.jface.viewers.columnviewereditor.saveeditorvalue': 388,
 'org.eclipse.jface.viewers.columnviewer.setvalue': 386,
 'org.eclipse.datatools.sqltools.data.internal.ui.editor.tabledatacellmodifier.modify': 386,
 'org.eclipse.datatools.sqltools.data.internal.ui.editor.tabledataeditor.getorcreaterow': 386,
 'org.eclipse.jface.viewers.abstracttableviewer.insert': 386,
 'org.eclipse.jface.viewers.columnviewer.applyeditorvalue': 386,
 'org.eclipse.jdt.core.dom.astnode.accept': 385,
 'org.eclipse.ui.internal.editorreference.createpart': 385,
 'org.eclipse.ui.internal.editorreference.createparthelper': 385,
 'org.eclipse.ui.commands.actionhandler.execute': 378,
 'org.apache.catalina.core.standardpipelinestandardpipelinevalvecontext.invokenext': 376,
 'org.eclipse.ui.internal.partlistenerlist.run': 375,
 'org.eclipse.swt.widgets.canvas.windowproc': 375,
 'org.eclipse.team.svn.core.utility.progressmonitorutility.dosubtask': 375,
 'org.eclipse.ltk.ui.refactoring.refactoringwizardopenoperation.run': 373,
 'org.eclipse.core.internal.events.buildmanager.basicbuildloop': 371,
 'org.eclipse.jface.window.window.create': 365,
 'org.eclipse.swt.widgets.widget.checkwidget': 365,
 'org.eclipse.jface.viewers.viewer.fireselectionchanged': 357,
 'org.eclipse.jface.wizard.wizarddialog.run': 353,
 'org.eclipse.jface.viewers.structuredviewer.refresh': 352,
 'org.eclipse.swt.internal.win.os.callwindowprocw': 351,
 'org.eclipse.swt.internal.win.os.callwindowproc': 348,
 'org.eclipse.jdt.core.javacore.run': 341,
 'org.eclipse.jface.viewers.abstracttreeviewer.run': 339,
 'org.eclipse.cdt.internal.core.dom.parser.cpp.cppsemantics.resolvebinding': 339,
 'org.eclipse.jpt.common.utility.internal.iterators.transformationiterator.hasnext': 337,
 'org.eclipse.jpt.common.utility.internal.iterators.compositeiterator.hasnext': 337,
 'org.eclipse.jpt.common.utility.internal.iterators.compositeiterator.loadcurrentiterator': 337,
 'org.eclipse.swt.widgets.composite.releasewidget': 335,
 'org.eclipse.team.svn.core.operation.abstractactionoperation.protectstep': 335,
 'org.eclipse.jface.viewers.abstracttreeviewer.doupdateitem': 331,
 'org.eclipse.jface.viewers.structuredviewer.updateselection': 330,
 'org.eclipse.osgi.framework.internal.core.bundlehost.startworker': 330,
 'org.eclipse.ui.internal.partstack.refreshpresentationselection': 329,
 'org.eclipse.cdt.internal.core.dom.parser.cpp.cppvisitor.resolvebinding': 327,
 'org.eclipse.team.svn.core.operation.compositeoperation.runimpl': 323,
 'org.eclipse.jface.viewers.structuredviewer.handleopen': 321,
 'org.eclipse.swt.widgets.widget.wmchar': 321,
 'org.eclipse.cdt.internal.core.dom.parser.cpp.cppvisitor.getexpressiontype': 321,
 'org.eclipse.e.ui.internal.workbench.swt.partrenderingengine.access': 319,
 'org.eclipse.jface.viewers.contentviewer.setinput': 317,
 'org.eclipse.jface.viewers.structuredviewer.widgetselected': 316,
 'org.eclipse.osgi.framework.internal.core.bundleloader.findclass': 316,
 'org.eclipse.core.internal.events.autobuildjob.dobuild': 315,
 'org.eclipse.core.internal.events.autobuildjob.run': 314,
 'org.eclipse.jface.action.actioncontributionitemactionlistener.handleevent': 313,
 'org.eclipse.e.ui.internal.workbench.swt.partrenderingengine.creategui': 313,
 'junit.framework.testsuite.runtest': 310,
 'org.eclipse.ui.internal.handlers.slavehandlerservice.executecommand': 310,
 'java.lang.classloader.loadclassinternal': 309,
 'org.eclipse.swt.custom.styledtext.handleevent': 308,
 'junit.framework.testsuite.run': 308,
 'org.eclipse.swt.widgets.widget.windowproc': 306,
 'org.eclipse.ui.internal.partpane.setvisible': 305,
 'org.eclipse.core.internal.registry.configurationelement.createexecutableextension': 305,
 'org.eclipse.swt.widgets.widget.releaseresources': 299,
 'org.eclipse.osgi.framework.internal.core.bundlecontextimpl.start': 298,
 'org.eclipse.jface.action.actioncontributionitem.handlewidgetevent': 295,
 'org.eclipse.jface.commands.actionhandler.execute': 295,
 'org.eclipse.jface.dialogs.dialog.create': 292,
 'org.eclipse.jface.viewers.structuredviewer.fireopen': 291,
 'org.eclipse.jface.util.openstrategy.fireopenevent': 290,
 'org.eclipse.jface.viewers.structuredviewer.updateitem': 280,
 'org.eclipse.osgi.framework.internal.core.bundleloader.findlocalclass': 280,
 'org.eclipse.jface.viewers.viewer.run': 279,
 'org.eclipse.core.internal.resources.workspace.endoperation': 277,
 'org.eclipse.jface.viewers.structuredviewer.setinput': 277,
 'org.eclipse.team.internal.ui.actions.jobrunnablecontext.run': 273,
 'org.eclipse.e.ui.internal.workbench.swt.partrenderingengine.safecreategui': 272,
 'org.eclipse.ui.application.workbenchadvisor.openwindows': 271,
 'org.eclipse.jface.dialogs.progressmonitordialog.run': 270,
 'org.eclipse.jface.wizard.wizarddialog.finishpressed': 270,
 'org.eclipse.jface.viewers.structuredviewerupdateitemsaferunnable.run': 269,
 'org.eclipse.core.internal.events.notificationmanager.run': 267,
 'org.eclipse.ui.internal.abstractworkingset.getelements': 267,
 'org.eclipse.ui.internal.abstractworkingset.getelementsarray': 267,
 'org.eclipse.core.internal.events.notificationmanager.notify': 266,
 'org.eclipse.ui.internal.presentations.presentablepart.setvisible': 265,
 'org.eclipse.ui.internal.aggregateworkingset.restoreworkingset': 265,
 'org.eclipse.team.internal.ui.actions.jobrunnablecontextresourcejob.runinworkspace': 264,
 'org.eclipse.e.ui.internal.workbench.eworkbench.createandrunui': 264,
 'org.eclipse.ui.internal.aggregateworkingset.constructelements': 262,
 'org.eclipse.osgi.framework.internal.core.bundlecontextimpl.startactivator': 260,
 'org.eclipse.ui.internal.editormanager.openeditor': 256,
 'org.eclipse.jdt.internal.core.javamodeloperation.runoperation': 255,
 'org.eclipse.ui.internal.editormanager.openeditorfromdescriptor': 254,
 'org.eclipse.jdt.internal.core.javaproject.getresolvedclasspath': 252,
 'org.eclipse.osgi.framework.eventmgr.eventmanager.dispatchevent': 252,
 'org.eclipse.jdt.internal.ui.refactoring.actions.refactoringstarter.activate': 249,
 'org.eclipse.swt.widgets.display.eventproc': 246,
 'org.eclipse.swt.internal.gtk.os.gtk_main_do_event': 246,
 'org.eclipse.cdt.internal.core.pdom.dom.cpp.pdomcpplinkage.resolvebinding': 244,
 'org.eclipse.cdt.internal.core.pdom.pdom.findbinding': 243,
 'org.eclipse.cdt.internal.core.pdom.dom.cpp.pdomcpplinkage._resolvebinding': 243,
 'org.eclipse.cdt.internal.core.pdom.dom.cpp.pdomcpplinkage.resolvefunctioncall': 243,
 'org.eclipse.cdt.internal.core.pdom.dom.cpp.pdomcpplinkage.gettypes': 243,
 'org.eclipse.cdt.internal.core.index.cindex.findbinding': 242,
 'org.eclipse.ui.ide.ide.openeditor': 240,
 'org.eclipse.cdt.internal.core.dom.parser.cpp.cppsemantics.postresolution': 240,
 'org.eclipse.ui.internal.handlers.legacyhandlerwrapper.execute': 239,
 'org.eclipse.core.internal.events.notificationmanager.broadcastchanges': 237,
 'org.eclipse.ui.internal.workbenchwindow.restorestate': 235,
 'org.eclipse.ui.internal.editorstack.add': 235,
 'org.eclipse.ui.internal.partstack.add': 235,
 'org.apache.catalina.core.standardpipeline.invoke': 232,
 'org.eclipse.osgi.internal.baseadaptor.defaultclassloader.loadclass': 230,
 'org.eclipse.ui.internal.openpreferencesaction.run': 228,
 'org.eclipse.ui.internal.startupthreadingstartuprunnable.run': 228,
 'org.apache.catalina.core.containerbase.invoke': 226,
 'org.eclipse.ui.internal.handlers.handlerproxy.execute': 226,
 'org.eclipse.ui.internal.workbenchwindow.close': 225,
 'org.eclipse.ui.internal.workbenchwindow.access': 225,
 'org.eclipse.ui.internal.workbenchwindow.busyclose': 225,
 'org.eclipse.ui.internal.partstack.setselection': 225,
 'org.apache.commons.logging.logfactory.getlog': 225,
 'org.eclipse.jface.action.menumanager.update': 224,
 'org.eclipse.ui.internal.presentations.util.tabbedstackpresentation.selectpart': 224,
 'org.eclipse.ui.internal.presentations.util.lefttorighttaborder.select': 224,
 'org.eclipse.ui.internal.presentations.util.presentablepartfolder.select': 224,
 'org.eclipse.swt.widgets.shell.windowproc': 224,
 'org.eclipse.ui.internal.partlistenerlist.fireevent': 223,
 'org.eclipse.jface.viewers.abstracttreeviewer.createchildren': 222,
 'org.eclipse.jface.text.abstractdocument.replace': 222,
 'org.eclipse.ui.internal.actions.commandaction.runwithevent': 222,
 'org.eclipse.ui.internal.workbenchpage.setactivepart': 221,
 'org.eclipse.team.svn.core.utility.progressmonitorutility.run': 221,
 'org.eclipse.emf.ecore.impl.basiceobjectimpl.eset': 220,
 'org.eclipse.swt.widgets.table.windowproc': 218,
 'org.eclipse.jface.util.openstrategy.fireselectionevent': 217,
 'org.eclipse.ui.progress.uijob.run': 217,
 'org.eclipse.ui.internal.editorreference.geteditor': 217,
 'org.eclipse.swt.internal.gtk.os.g_main_context_iteration': 216,
 'org.eclipse.core.internal.registry.configurationelementhandle.createexecutableextension': 215,
 'org.slfj.loggerfactory.getlogger': 215,
 'org.eclipse.swt.widgets.display.syncexec': 213,
 'org.slfj.impl.jclloggerfactory.getlogger': 213,
 'org.apache.commons.logging.impl.slfjlogfactory.getinstance': 213,
 'java.lang.class.newinstance': 212,
 'org.eclipse.osgi.internal.baseadaptor.defaultclassloader.findlocalclass': 212,
 'org.eclipse.osgi.baseadaptor.loader.classpathmanager.findlocalclass': 212,
 'org.eclipse.swt.internal.gtk.os._g_main_context_iteration': 211,
 'org.eclipse.swt.widgets.synchronizer.syncexec': 210,
 'org.eclipse.ui.internal.partsashcontainer.createcontrol': 208,
 'org.eclipse.gmf.gmfgraph.impl.diagramelementimpl.eset': 208,
 'org.eclipse.jdt.internal.compiler.compiler.compile': 207,
 'org.eclipse.swt.custom.styledtext.handlekeydown': 207,
 'org.eclipse.swt.widgets.control.sendkeyevent': 206,
 'org.eclipse.osgi.framework.internal.core.abstractbundle.start': 206,
 'org.eclipse.swt.widgets.table.callwindowproc': 205,
 'org.eclipse.ui.texteditor.textoperationaction.run': 204,
 'org.eclipse.jdt.internal.core.builder.abstractimagebuilder.compile': 203,
 'org.eclipse.swt.custom.ctabfolder.handleevent': 202,
 'junit.framework.testresult.runprotected': 202,
 'org.eclipse.ui.internal.uisynchronizer.syncexec': 202,
 'org.eclipse.osgi.framework.internal.core.bundlecontextimpl.run': 202,
 'org.eclipse.jface.viewers.abstracttreeviewerupdateitemsaferunnable.run': 200,
 'org.eclipse.ui.internal.perspective.onactivate': 199,
 'org.eclipse.jface.viewers.structuredviewer.setselection': 197,
 'org.eclipse.jface.viewers.structuredviewer.handleselect': 196,
 'org.eclipse.ui.internal.workbenchpage.setperspective': 196,
 'org.eclipse.swt.widgets.control.wm_notify': 195,
 'org.eclipse.jdt.core.javacore.getclasspathcontainer': 195,
 'org.eclipse.team.svn.ui.utility.svnteamoperationwrapper.run': 194,
 'org.eclipse.jdt.internal.core.builder.javabuilder.build': 192,
 'org.eclipse.ui.internal.editormanager.createeditortab': 190,
 'org.eclipse.jdt.core.dom.astnode.acceptchildren': 188,
 'org.eclipse.osgi.framework.internal.core.startlevelmanager.dosetstartlevel': 188,
 'org.eclipse.jface.preference.preferencedialog.run': 187,
 'org.eclipse.swt.widgets.widget.dispose': 187,
 'org.eclipse.ui.part.multipageeditorpart.createpartcontrol': 187,
 'org.eclipse.core.internal.registry.osgi.registrystrategyosgi.createexecutableextension': 186,
 'org.eclipse.ui.internal.partpane.createchildcontrol': 184,
 'org.eclipse.jface.viewers.abstracttreeviewer.createtreeitem': 184,
 'org.eclipse.jdt.internal.junit.runner.remotetestrunner.run': 183,
 'org.eclipse.ui.internal.wwinpluginaction.runwithevent': 181,
 'org.eclipse.debug.internal.core.launchconfiguration.launch': 181,
 'org.eclipse.core.internal.registry.extensionregistry.createexecutableextension': 180,
 'org.eclipse.ui.internal.workbench.close': 179,
 'org.eclipse.ui.internal.workbench.busyclose': 179,
 'org.eclipse.jface.operation.modalcontextmodalcontextthread.block': 178,
 'hudson.security.chainedservletfilter.dofilter': 178,
 'org.eclipse.ui.internal.workbenchplugin.createextension': 177,
 'org.eclipse.jdt.internal.junit.runner.remotetestrunner.runtests': 177,
 'org.eclipse.jface.dialogs.dialog.buttonpressed': 177,
 'org.eclipse.swt.internal.gtk.os._gtk_main_do_event': 177,
 'sun.reflect.generatedmethodaccessor.invoke': 176,
 'org.eclipse.cdt.internal.core.dom.parser.cpp.cppsemantics.lookup': 175,
 'org.eclipse.jdt.internal.ui.javaeditor.editorutility.openineditor': 174,
 'org.eclipse.swt.widgets.control.setbounds': 173,
 'junit.framework.testcase.run': 172,
 'java.lang.nullpointerexception.init': 172,
 'junit.framework.testresult.protect': 171,
 'org.eclipse.ui.internal.progress.progressmanager.run': 171,
 'org.eclipse.ui.internal.workbenchwindow.setactivepage': 170,
 'org.eclipse.jface.wizard.wizarddialog.nextpressed': 170,
 'org.eclipse.cdt.internal.core.dom.parser.cpp.cppastidexpression.getexpressiontype': 170,
 'org.eclipse.swt.custom.styledtext.modifycontent': 169,
 'junit.framework.testresult.run': 169,
 'org.eclipse.swt.widgets.shell.callwindowproc': 168,
 'org.eclipse.emf.common.notify.impl.basicnotifierimpl.enotify': 168,

In [106]:
coder(6036, transformer=True)

[]

In [90]:
import matplotlib.pyplot as plt
import torch
from sentence_transformers import (
    SentenceTransformer,
    SentenceTransformerModelCardData,
    SentenceTransformerTrainer,
    SentenceTransformerTrainingArguments,
)
from sentence_transformers.evaluation import (
    EmbeddingSimilarityEvaluator,
    TripletEvaluator,
)
from sentence_transformers.losses import MultipleNegativesRankingLoss
from sentence_transformers.training_args import BatchSamplers
from sklearn.manifold import TSNE
from tqdm import tqdm

from data.buckets.bucket_data import BucketData, OtherBucketData
from data.buckets.issues_data import BucketDataset
from data.triplet_selector import RandomTripletSelector
from datasets import Dataset
from preprocess.entry_coders import Stack2Seq
from preprocess.seq_coder import SeqCoder
from preprocess.tokenizers import SimpleTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

model = SentenceTransformer("BAAI/bge-base-en")
print(f"Model sequence length: {model.max_seq_length}")

# Find model size in CUDA
print(f"Model size: {torch.cuda.memory_allocated() / 1024 ** 3:.2f} GB")


dataset_key = "eclipse_pretrain_f"
run_name = "bge-base-eclipse_f"
generate_dataset = True
batch_size = 16
eval_size = 1000
num_frames = 10


def format_stack(stack):
    # Select last 10 frames
    stack = stack[-num_frames:]
    return "\n".join([f"{i+1}: {frame}" for i, frame in enumerate(stack)])


def get_data_row(coder, event, similar_stack_id, dissimilar_stack_id):
    return {
        "anchor": format_stack(coder(event.st_id, transformer=True)),
        "positive": format_stack(coder(similar_stack_id, transformer=True)),
        "negative": format_stack(coder(dissimilar_stack_id, transformer=True)),
    }


if generate_dataset:
    triplet_selector_train = RandomTripletSelector(1)
    triplet_selector_eval = RandomTripletSelector(1)
    print("Load bucket data...")
    bucket_data = OtherBucketData(
        "eclipse",
        "/home/mdafifal.mamun/research/S3M/dataset/EMSE_data/eclipse_2018/eclipse_stacktraces.json",
        3850,
        700,
        350,
        140,
    )
    bucket_data.load()
    stack_loader = bucket_data.stack_loader()
    data_gen = BucketDataset(bucket_data)
    unsup_stacks = data_gen.train_stacks()

    data_gen.reset()

    stack2seq = Stack2Seq(cased=False, trim_len=0, sep=".")

    coder = SeqCoder(
        stack_loader, stack2seq, SimpleTokenizer(), min_freq=0, max_len=None
    )

    coder.fit(unsup_stacks)

    train_data = []
    test_data = []

    print("Generate the dataset...")
    for i, event in tqdm(enumerate(data_gen.train()), desc="Step"):
        similar_stack_ids, dissimilar_stack_ids = triplet_selector_train(event)
        for similar_stack_id, dissimilar_stack_id in zip(
            similar_stack_ids, dissimilar_stack_ids
        ):
            train_data.append(
                get_data_row(coder, event, similar_stack_id, dissimilar_stack_id)
            )


    for i, event in tqdm(enumerate(data_gen.test()), desc="Step"):
        similar_stack_ids, dissimilar_stack_ids = triplet_selector_eval(event)
        for similar_stack_id, dissimilar_stack_id in zip(
            similar_stack_ids, dissimilar_stack_ids
        ):
            test_data.append(
                get_data_row(coder, event, similar_stack_id, dissimilar_stack_id)
            )


    frame_freq = {}
    for row in train_data:
        for stack in ["anchor", "positive", "negative"]:
            for frame in row[stack]:
                # if frame == "org.eclipse.swt.widgets.display.readanddispatch":
                #     pprint(row)
                #     return
                if frame not in frame_freq:
                    frame_freq[frame] = 0
                frame_freq[frame] += 1

    frame_freq = dict(
        sorted(frame_freq.items(), key=lambda item: item[1], reverse=True)
    )

    updated_train_data = []
    updated_test_data = []

    # Remove all frames from train_data that has a frequency over 2000
    for row in train_data:
        new_row = {}
        for stack in ["anchor", "positive", "negative"]:
            previous = len(row[stack])

            if previous < 5:
                updated_train_data.append(row)
                continue

            new_row[stack] = [frame for frame in row[stack] if frame_freq[frame] <= 500]
            current = len(new_row[stack])
            updated_train_data.append(new_row)


    # Remove all frames from test_data that has a frequency over 2000
    for row in test_data:
        new_row = {}
        for stack in ["anchor", "positive", "negative"]:
            previous = len(row[stack])

            if previous < 5:
                updated_test_data.append(row)
                continue

            new_row[stack] = [frame for frame in row[stack] if frame_freq[frame] <= 500]
            current = len(new_row[stack])
            updated_test_data.append(new_row)


    # Convert train_data list to a Dataset
    train_dataset = Dataset.from_list(updated_train_data)
    test_dataset = Dataset.from_list(updated_test_data)
    train_dataset.save_to_disk(f"datasets/{dataset_key}_train")
    test_dataset.save_to_disk(f"datasets/{dataset_key}_eval")

Using device: cuda
Model sequence length: 512
Model size: 0.41 GB
Load bucket data...
Generate the dataset...

Step: 5180it [01:06, 77.44it/s]
Step: 2146it [00:17, 120.77it/s]

Saving the dataset (0/1 shards):   0%|          | 0/14760 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/6171 [00:00<?, ? examples/s]

In [97]:
frame_freq

{'e': 1018232,
 '.': 810441,
 'r': 643854,
 'i': 559653,
 't': 558910,
 'o': 498215,
 'n': 463346,
 'a': 458664,
 's': 444151,
 'c': 418155,
 'l': 394427,
 'p': 298665,
 'g': 248864,
 'd': 216169,
 'u': 181804,
 'm': 141581,
 ':': 135427,
 ' ': 135427,
 '\n': 120667,
 'w': 93692,
 'v': 82477,
 'f': 80700,
 'b': 72926,
 'h': 71929,
 'j': 64209,
 'y': 48722,
 'x': 38464,
 'k': 37940,
 '1': 26885,
 '2': 14526,
 '3': 14313,
 '4': 14045,
 '5': 13763,
 '6': 13459,
 '7': 13135,
 '8': 12836,
 '9': 12465,
 '0': 12125,
 'z': 11714,
 'q': 5411,
 '_': 1785}

In [96]:
for row in train_data:
    new_row = {}
    for stack in ["anchor", "positive", "negative"]:
        previous = len(row[stack])

        if previous < 5:
            updated_train_data.append(row)
            continue

        new_row[stack] = [frame for frame in row[stack] if frame_freq[frame] <= 500]
        print([frame for frame in row[stack] if frame_freq[frame] <= 500])
        current = len(new_row[stack])
        updated_train_data.append(new_row)
    break

[]
[]
[]

In [91]:
print("Load the preprocessed dataset")
train_dataset = Dataset.load_from_disk(f"datasets/{dataset_key}_train")
test_dataset = Dataset.load_from_disk(f"datasets/{dataset_key}_eval")

# Optionally preprocess and shuffle the dataset
train_dataset = train_dataset.shuffle(seed=42)
test_dataset = test_dataset.shuffle(seed=42)
eval_dataset = test_dataset.select(range(eval_size))

print("Dataset Sizes - Train:", len(train_dataset), "Test:", len(test_dataset))

# 4. Define a loss function
loss = MultipleNegativesRankingLoss(model)


# Populate the lists with the sentences and their labels from test_dataset
sentences_1 = []
sentences_2 = []
labels = []

for i in range(len(eval_dataset)):
    sentences_1.append(eval_dataset[i]["anchor"])
    sentences_2.append(eval_dataset[i]["positive"])
    labels.append(1)  # 1 means similar pair

    sentences_1.append(eval_dataset[i]["anchor"])
    sentences_2.append(eval_dataset[i]["negative"])
    labels.append(0)  # 0 means dissimilar pair

Load the preprocessed dataset
Dataset Sizes - Train: 14760 Test: 6171

In [92]:
sentences_1

[[],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 ...]

In [98]:
test_dataset = Dataset.load_from_disk(f"datasets/eclipse_pretrain_f_eval")

In [99]:
test_dataset

Dataset({
    features: ['anchor', 'positive'],
    num_rows: 6171
})