In [2]:
import pandas as pd

In [3]:
df = pd.read_json("/home/mdafifal.mamun/research/S3M/dataset/EMSE_data/gnome_2011/gnome_stacktraces.json")

In [4]:
from pprint import pprint

In [5]:
# find a record that has pthread_cond_wait at pthreadcondwait. in the description
pprint(df[df['description'].str.contains('pthread_cond_wait')].iloc[0]["description"])

('Package: galeon\n'
 'Severity: major\n'
 'Version: 1.2.5\n'
 'Synopsis: error visiting web site www.wanadoo.es\n'
 'Bugzilla-Product: galeon\n'
 'Bugzilla-Component: Mozilla interaction\n'
 '\n'
 'Description:\n'
 'It crashes when I go to the following website:\n'
 'www.wanadoo.es\n'
 '\n'
 '\n'
 '\n'
 'Debugging Information:\n'
 '\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...[New Thread '
 '1024 (LWP 1913)]\n'
 '[New Thread 2049 (LWP 1924)]\n'
 '[New Thread 1026 (LWP 1925)]\n'
 '[New Thread 2051 (LWP 1926)]\n'
 '[New Thread 3076 (LWP 1927)]\n'
 '[New Thread 4101 (LWP 1934)]\n'
 '\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...(no debugging symbols found)...\n'
 '(no debugging symbols found)...0x40940a39 in wait4 () from /lib/libc.so.6\n'
 '#0  0x40940a39 in wait4 () from /lib/libc.so.6\n'
 '#1  0x409b7e48 in __check_rhosts_file () from /lib/libc.so.6\n'
 '#2  0x402ab453 in waitpid () from /lib/libpthread.so.0\n'
 '#3  0x4038b866 in gnome_init () from /usr/lib/libgnomeui.so.32\n'
 '#4  0x402a8f54 in pthread_sighandler () from /lib/libpthread.so.0\n'
 '#5  0x408c96b8 in sigaction () from /lib/libc.so.6\n'
 '#6  0x4090ea8b in free () from /lib/libc.so.6\n'
 '#7  0x41952215 in NSGetModule ()\n'
 '   from /usr/lib/mozilla/plugins/libflashplayer.so\n'
 '#8  0x4129e620 in compositeClassRec () from /usr/X11R6/lib/libXt.so.6\n'
 '\n'
 'Thread 6 (Thread 4101 (LWP 1934)):\n'
 '#0  0x408c987e in sigsuspend () from /lib/libc.so.6\n'
 '#1  0x402a8879 in __pthread_wait_for_restart_signal ()\n'
 '   from /lib/libpthread.so.0\n'
 '#2  0x402a5102 in pthread_cond_wait () from /lib/libpthread.so.0\n'
 '#3  0x40151e32 in PR_WaitCondVar () from /usr/lib/libnspr4.so\n'
 '#4  0x400e71d5 in nsThreadPool::GetRequest () from /usr/lib/libxpcom.so\n'
 '#5  0x400e79f4 in nsThreadPoolRunnable::Run () from /usr/lib/libxpcom.so\n'
 '#6  0x400e646e in nsThread::Main () from /usr/lib/libxpcom.so\n'
 '#7  0x40156bad in PR_Select () from /usr/lib/libnspr4.so\n'
 '#8  0x402a60ba in pthread_start_thread () from /lib/libpthread.so.0\n'
 '\n'
 'Thread 5 (Thread 3076 (LWP 1927)):\n'
 '#0  0x40940dc1 in nanosleep () from /lib/libc.so.6\n'
 '#1  0x402a8cda in __pthread_timedsuspend_new () from /lib/libpthread.so.0\n'
 '#2  0x402a535b in pthread_cond_timedwait_relative () from '
 '/lib/libpthread.so.0\n'
 '#3  0x402a54ec in pthread_cond_timedwait () from /lib/libpthread.so.0\n'
 '#4  0x40151c3c in PR_Unlock () from /usr/lib/libnspr4.so\n'
 '#5  0x40151e46 in PR_WaitCondVar () from /usr/lib/libnspr4.so\n'
 '#6  0x400e95b6 in TimerThread::Run () from /usr/lib/libxpcom.so\n'
 '#7  0x400e646e in nsThread::Main () from /usr/lib/libxpcom.so\n'
 '#8  0x40156bad in PR_Select () from /usr/lib/libnspr4.so\n'
 '#9  0x402a60ba in pthread_start_thread () from /lib/libpthread.so.0\n'
 '\n'
 'Thread 4 (Thread 2051 (LWP 1926)):\n'
 '#0  0x408c987e in sigsuspend () from /lib/libc.so.6\n'
 '#1  0x402a8879 in __pthread_wait_for_restart_signal ()\n'
 '   from /lib/libpthread.so.0\n'
 '#2  0x402a5102 in pthread_cond_wait () from /lib/libpthread.so.0\n'
 '#3  0x40151e32 in PR_WaitCondVar () from /usr/lib/libnspr4.so\n'
 '#4  0x40b50bc3 in NSGetModule () from '
 '/usr/lib/mozilla/components/libnecko.so\n'
 '#5  0x40b5066c in NSGetModule () from '
 '/usr/lib/mozilla/components/libnecko.so\n'
 '#6  0x400e646e in nsThread::Main () from /usr/lib/libxpcom.so\n'
 '#7  0x40156bad in PR_Select () from /usr/lib/libnspr4.so\n'
 '#8  0x402a60ba in pthread_start_thread () from /lib/libpthread.so.0\n'
 '\n'
 'Thread 3 (Thread 1026 (LWP 1925)):\n'
 '#0  0x40968b90 in poll () from /lib/libc.so.6\n'
 '#1  0x40155a25 in PR_OpenDir () from /usr/lib/libnspr4.so\n'
 '#2  0x40155b54 in PR_Poll () from /usr/lib/libnspr4.so\n'
 '#3  0x40b470b5 in NSGetModule () from '
 '/usr/lib/mozilla/components/libnecko.so\n'
 '#4  0x400e646e in nsThread::Main () from /usr/lib/libxpcom.so\n'
 '#5  0x40156bad in PR_Select () from /usr/lib/libnspr4.so\n'
 '#6  0x402a60ba in pthread_start_thread () from /lib/libpthread.so.0\n'
 '\n'
 'Thread 2 (Thread 2049 (LWP 1924)):\n'
 '#0  0x40968b90 in poll () from /lib/libc.so.6\n'
 '#1  0x402a5d96 in __pthread_manager () from /lib/libpthread.so.0\n'
 '\n'
 'Thread 1 (Thread 1024 (LWP 1913)):\n'
 '#0  0x40940a39 in wait4 () from /lib/libc.so.6\n'
 '#1  0x409b7e48 in __check_rhosts_file () from /lib/libc.so.6\n'
 '#2  0x402ab453 in waitpid () from /lib/libpthread.so.0\n'
 '#3  0x4038b866 in gnome_init () from /usr/lib/libgnomeui.so.32\n'
 '#4  0x402a8f54 in pthread_sighandler () from /lib/libpthread.so.0\n'
 '#5  0x408c96b8 in sigaction () from /lib/libc.so.6\n'
 '#6  0x4090ea8b in free () from /lib/libc.so.6\n'
 '#7  0x41952215 in NSGetModule ()\n'
 '   from /usr/lib/mozilla/plugins/libflashplayer.so\n'
 '#8  0x4129e620 in compositeClassRec () from /usr/X11R6/lib/libXt.so.6\n'
 '#0  0x40940a39 in wait4 () from /lib/libc.so.6\n'
 '#0  0x40940a39 in wait4 () from /lib/libc.so.6\n'
 'No symbol table info available.\n'
 '#1  0x409b7e48 in __check_rhosts_file () from /lib/libc.so.6\n'
 'No symbol table info available.\n'
 '#2  0x402ab453 in waitpid () from /lib/libpthread.so.0\n'
 'No symbol table info available.\n'
 '#3  0x4038b866 in gnome_init () from /usr/lib/libgnomeui.so.32\n'
 'No symbol table info available.\n'
 '#4  0x402a8f54 in pthread_sighandler () from /lib/libpthread.so.0\n'
 'No symbol table info available.\n'
 '#5  0x408c96b8 in sigaction () from /lib/libc.so.6\n'
 'No symbol table info available.\n'
 '#6  0x4090ea8b in free () from /lib/libc.so.6\n'
 'No symbol table info available.\n'
 '#7  0x41952215 in NSGetModule ()\n'
 '   from /usr/lib/mozilla/plugins/libflashplayer.so\n'
 'No symbol table info available.\n'
 '\n'
 '\n'
 '\n'
 '\n'
 '------- Bug moved to this database by unknown@bugzilla.gnome.org 2002-12-27 '
 '22:48 -------\n'
 '\n'
 'Unknown version 1.2.x in product galeon. Setting version to the default, '
 '"unspecified".\n'
 'Reassigning to the default owner of the component, philipl@mail.utexas.edu.\n'
 '\n')

In [6]:
pprint(df.head().iloc[0]["description"])

('Package: Evolution\n'
 'Priority: Normal\n'
 'Version: 0.12\n'
 'Synopsis: Error by getting mail from pop 3 server\n'
 'Bugzilla-Product: Evolution\n'
 'Bugzilla-Component: Mailer\n'
 '\n'
 'Description:\n'
 'create three Mailaccounts\n'
 'click on "Verschicken/Empfangen=send/get mail"\n'
 '\n'
 'you get mail from 2 accounts but not from the third one \n'
 'during conncting the server the client crashes \n'
 '\n'
 '\n'
 'Debugging Information:\n'
 '\n'
 '[New Thread 1024 (LWP 783)]\n'
 '[New Thread 2049 (LWP 946)]\n'
 '[New Thread 1026 (LWP 947)]\n'
 '[New Thread 2051 (LWP 948)]\n'
 '[New Thread 4100 (LWP 953)]\n'
 '[New Thread 12293 (LWP 1454)]\n'
 '0xedbb32c in wait4 () from /lib/libc.so.6\n'
 '#0  0xedbb32c in wait4 () from /lib/libc.so.6\n'
 '#1  0xedbb2e0 in waitpid () from /lib/libc.so.6\n'
 '#2  0xf3ace24 in waitpid () from /lib/libpthread.so.0\n'
 '#3  0xfb80878 in gnome_segv_handle (signum=11) at gnome-init.c:659\n'
 '#4  0x10057490 in segv_redirect (sig=11) at main.c:67\n'
 '#5  0xf3aa09c in pthread_sighandler () from /lib/libpthread.so.0\n'
 '#6  <signal handler called>\n'
 '#7  0xf7d0900 in gtk_progress_set_percentage (progress=0x1022c1e8, \n'
 '    percentage=0) at gtkprogress.c:517\n'
 '#8  0xf7d08b4 in gtk_progress_set_percentage (progress=0x10200640, \n'
 '    percentage=0) at gtkprogress.c:515\n'
 '#9  0xf603fe8 in g_timeout_dispatch (source_data=0x80000000, \n'
 '    dispatch_time=0x43300000, user_data=0x10200640) at gmain.c:1302\n'
 '#10 0xf602d34 in g_main_dispatch (dispatch_time=0x7ffff588) at gmain.c:656\n'
 '#11 0xf6033a0 in g_main_iterate (block=269239776, dispatch=1) at '
 'gmain.c:877\n'
 '#12 0xf6035e4 in g_main_run (loop=0x100e7c80) at gmain.c:935\n'
 '#13 0xf7a9358 in gtk_main () at gtkmain.c:524\n'
 '#14 0xf1d6678 in bonobo_main () at bonobo-main.c:283\n'
 '#15 0x10057644 in main (argc=5, argv=0x7ffff7bc) at main.c:140\n'
 '#16 0xed30a08 in __libc_start_main () from /lib/libc.so.6\n'
 '#0  0xedbb32c in wait4 () from /lib/libc.so.6\n'
 'No symbol table info available.\n'
 '#1  0xedbb2e0 in waitpid () from /lib/libc.so.6\n'
 'No symbol table info available.\n'
 '#2  0xf3ace24 in waitpid () from /lib/libpthread.so.0\n'
 'No symbol table info available.\n'
 '#3  0xfb80878 in gnome_segv_handle (signum=11) at gnome-init.c:659\n'
 'estatus = -725508609\n'
 'in_segv = 1\n'
 'pid = 512\n'
 '#4  0x10057490 in segv_redirect (sig=11) at main.c:67\n'
 'No locals.\n'
 '#5  0xf3aa09c in pthread_sighandler () from /lib/libpthread.so.0\n'
 'No symbol table info available.\n'
 '#6  <signal handler called>\n'
 'No symbol table info available.\n'
 '#7  0xf7d0900 in gtk_progress_set_percentage (progress=0x1022c1e8, \n'
 '    percentage=0) at gtkprogress.c:517\n'
 'No locals.\n'
 '\n'
 '\n'
 'Unknown reporter: JDroste@neptunswelt.de, changed to '
 'bugbuddy-import@ximian.com.\n'
 '\n')

In [7]:
pprint(df.iloc[15225]["stacktrace"])

[{'exception': None,
  'frames': [{'address': '0x4074eb85',
              'args': 'set=0x41e798cc',
              'depth': '0',
              'file': '../sysdeps/unix/sysv/linux/sigsuspend.c',
              'fileline': '45',
              'function': '__sigsuspend'},
             {'address': '0x401ad1c9',
              'args': 'self=0x41e79be0',
              'depth': '1',
              'file': 'pthread.c',
              'fileline': '969',
              'function': '__pthread_wait_for_restart_signal'},
             {'address': '0x401a9bdc',
              'args': 'cond=0x8181b0c, mutex=0x8181aa8',
              'depth': '2',
              'file': 'restart.h',
              'fileline': '34',
              'function': 'pthread_cond_wait'},
             {'address': '0x4014dcad',
              'args': '',
              'depth': '3',
              'dylib': '/usr/lib/libnspr4.so',
              'function': 'PR_WaitCondVar'},
             {'address': '0x400e9bc8',
              'args': '',
              'depth': '4',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'nsThreadPool::GetRequest'},
             {'address': '0x400ea2cd',
              'args': '',
              'depth': '5',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'nsThreadPoolRunnable::Run'},
             {'address': '0x400e8e33',
              'args': '',
              'depth': '6',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'nsThread::Main'},
             {'address': '0x401524d0',
              'args': '',
              'depth': '7',
              'dylib': '/usr/lib/libnspr4.so',
              'function': '_pt_root'},
             {'address': '0x401aac6f',
              'args': 'arg=0x41e79be0',
              'depth': '8',
              'file': 'manager.c',
              'fileline': '284',
              'function': 'pthread_start_thread'}],
  'message': None,
  'nested': []},
 {'exception': None,
  'frames': [{'address': '0x4074eb85',
              'args': 'set=0x4103890c',
              'depth': '0',
              'file': '../sysdeps/unix/sysv/linux/sigsuspend.c',
              'fileline': '45',
              'function': '__sigsuspend'},
             {'address': '0x401ad1c9',
              'args': 'self=0x41038be0',
              'depth': '1',
              'file': 'pthread.c',
              'fileline': '969',
              'function': '__pthread_wait_for_restart_signal'},
             {'address': '0x401a9bdc',
              'args': 'cond=0x81762d4, mutex=0x8176270',
              'depth': '2',
              'file': 'restart.h',
              'fileline': '34',
              'function': 'pthread_cond_wait'},
             {'address': '0x4014dcad',
              'args': '',
              'depth': '3',
              'dylib': '/usr/lib/libnspr4.so',
              'function': 'PR_WaitCondVar'},
             {'address': '0x40be302d',
              'args': '',
              'depth': '4',
              'dylib': '/usr/lib/mozilla/components/libnecko.so',
              'function': 'NSGetModule'},
             {'address': '0x40be2a75',
              'args': '',
              'depth': '5',
              'dylib': '/usr/lib/mozilla/components/libnecko.so',
              'function': 'NSGetModule'},
             {'address': '0x400e8e33',
              'args': '',
              'depth': '6',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'nsThread::Main'},
             {'address': '0x401524d0',
              'args': '',
              'depth': '7',
              'dylib': '/usr/lib/libnspr4.so',
              'function': '_pt_root'},
             {'address': '0x401aac6f',
              'args': 'arg=0x41038be0',
              'depth': '8',
              'file': 'manager.c',
              'fileline': '284',
              'function': 'pthread_start_thread'}],
  'message': None,
  'nested': []},
 {'exception': None,
  'frames': [{'address': '0x40805e17',
              'args': 'fds=0x40e3882c, nfds=3, timeout=35000',
              'depth': '0',
              'file': '../sysdeps/unix/sysv/linux/poll.c',
              'fileline': '63',
              'function': '__poll'},
             {'address': '0x401512bd',
              'args': '',
              'depth': '1',
              'dylib': '/usr/lib/libnspr4.so',
              'function': '_pr_poll_with_poll'},
             {'address': '0x40bd8208',
              'args': '',
              'depth': '2',
              'dylib': '/usr/lib/mozilla/components/libnecko.so',
              'function': 'NSGetModule'},
             {'address': '0x400e8e33',
              'args': '',
              'depth': '3',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'nsThread::Main'},
             {'address': '0x401524d0',
              'args': '',
              'depth': '4',
              'dylib': '/usr/lib/libnspr4.so',
              'function': '_pt_root'},
             {'address': '0x401aac6f',
              'args': 'arg=0x40e38be0',
              'depth': '5',
              'file': 'manager.c',
              'fileline': '284',
              'function': 'pthread_start_thread'}],
  'message': None,
  'nested': []},
 {'exception': None,
  'frames': [{'address': '0x40805e17',
              'args': 'fds=0x81a7bfc, nfds=1, timeout=2000',
              'depth': '0',
              'file': '../sysdeps/unix/sysv/linux/poll.c',
              'fileline': '63',
              'function': '__poll'},
             {'address': '0x401aa920',
              'args': 'arg=0xd',
              'depth': '1',
              'file': 'manager.c',
              'fileline': '140',
              'function': '__pthread_manager'}],
  'message': None,
  'nested': []},
 {'exception': None,
  'frames': [{'address': '0x407daca9',
              'args': '',
              'depth': '0',
              'dylib': '/lib/i686/libc.so.6',
              'function': '__wait4'},
             {'address': '0x408566b4',
              'args': '',
              'depth': '1',
              'dylib': '/lib/i686/libc.so.6',
              'function': '__DTOR_END__'},
             {'address': '0x401af6f3',
              'args': 'pid=5467, stat_loc=0xbffff28c, options=0',
              'depth': '2',
              'file': 'wrapsyscall.c',
              'fileline': '172',
              'function': 'waitpid'},
             {'address': '0x4024d456',
              'args': 'signum=11',
              'depth': '3',
              'file': 'gnome-init.c',
              'fileline': '659',
              'function': 'gnome_segv_handle'},
             {'address': '0x401ada85',
              'args': 'signo=11, ctx=       {gs = 7, __gsh = 0, fs = 0, __fsh '
                      '= 0, es = 43, __esh = 0, ds = 43, __dsh = 0, edi = 43, '
                      'esi = 0, ebp = 3221223076, esp = 3221222956, ebx = '
                      '1079807460, edx = 115, ecx = 4294967295, eax = 0, '
                      'trapno = 14, err = 4, eip = 1079777092, cs = 35, __csh '
                      '= 0, eflags = 2163270, esp_at_signal = 3221222956, ss = '
                      '43, __ssh = 0, fpstate = 0xbffff3b0, oldmask = '
                      '2147483648, cr2 = 43}',
              'depth': '4',
              'file': 'signals.c',
              'fileline': '97',
              'function': 'pthread_sighandler'},
             {'depth': '5',
              'function': '<signal handler called>',
              'is_crash': '1'},
             {'address': '0x405c1744',
              'args': '     format=0x414bd676 "K '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®Ã\x81Ã\x9f %1$dK, %3$sK '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®/Ã\x83Ã\x8a", args=0xbffff714',
              'depth': '6',
              'file': 'gstrfuncs.c',
              'fileline': '1076',
              'function': 'g_printf_string_upper_bound'},
             {'address': '0x405c0fd8',
              'args': '     format=0x414bd672 "%2$sK '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®Ã\x81Ã\x9f %1$dK, %3$sK '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®/Ã\x83Ã\x8a",      '
                      'args1=0xbffff710',
              'depth': '7',
              'file': 'gstrfuncs.c',
              'fileline': '156',
              'function': 'g_strdup_vprintf'},
             {'address': '0x405c101c',
              'args': '     format=0x414bd672 "%2$sK '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®Ã\x81Ã\x9f %1$dK, %3$sK '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®/Ã\x83Ã\x8a"',
              'depth': '8',
              'file': 'gstrfuncs.c',
              'fileline': '172',
              'function': 'g_strdup_printf'},
             {'address': '0x080cfb0d',
              'args': 'this=0x84aaed8,      aWebProgress=0x856dcd4, '
                      'aRequest=0x8558478, aCurSelfProgress=44248,      '
                      'aMaxSelfProgress=1275743, aCurTotalProgress=44248,      '
                      'aMaxTotalProgress=1275743',
              'depth': '9',
              'file': 'ContentHandler.cpp',
              'fileline': '1071',
              'function': 'GDownloadProgressListener::OnProgressChange'},
             {'address': '0x410fd649',
              'args': '',
              'depth': '10',
              'dylib': '/usr/lib/mozilla/components/liburiloader.so',
              'function': 'NSGetModule'},
             {'address': '0x410fd1ed',
              'args': '',
              'depth': '11',
              'dylib': '/usr/lib/mozilla/components/liburiloader.so',
              'function': 'NSGetModule'},
             {'address': '0x400fac06',
              'args': '',
              'depth': '12',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'XPTC_InvokeByIndex'},
             {'address': '0x400eb613',
              'args': '',
              'depth': '13',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'nsProxyObject::Post'},
             {'address': '0x400e67b7',
              'args': '',
              'depth': '14',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'PL_HandleEvent'},
             {'address': '0x400e66c5',
              'args': '',
              'depth': '15',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'PL_ProcessPendingEvents'},
             {'address': '0x400e7827',
              'args': '',
              'depth': '16',
              'dylib': '/usr/lib/libxpcom.so',
              'function': 'nsEventQueueImpl::ProcessPendingEvents'},
             {'address': '0x41503cc6',
              'args': '',
              'depth': '17',
              'dylib': '/usr/lib/mozilla/components/libwidget_gtk.so',
              'function': 'NSGetModule'},
             {'address': '0x41503a15',
              'args': '',
              'depth': '18',
              'dylib': '/usr/lib/mozilla/components/libwidget_gtk.so',
              'function': 'NSGetModule'},
             {'address': '0x405b6a7a',
              'args': 'source_data=0x820b300,      current_time=0xbffffa60, '
                      'user_data=0x8119740',
              'depth': '19',
              'file': 'giounix.c',
              'fileline': '137',
              'function': 'g_io_unix_dispatch'},
             {'address': '0x405b8055',
              'args': 'dispatch_time=0xbffffa60',
              'depth': '20',
              'file': 'gmain.c',
              'fileline': '656',
              'function': 'g_main_dispatch'},
             {'address': '0x405b8659',
              'args': 'block=1, dispatch=1',
              'depth': '21',
              'file': 'gmain.c',
              'fileline': '877',
              'function': 'g_main_iterate'},
             {'address': '0x405b87e8',
              'args': 'loop=0x823a860',
              'depth': '22',
              'file': 'gmain.c',
              'fileline': '935',
              'function': 'g_main_run'},
             {'address': '0x404d527b',
              'args': '',
              'depth': '23',
              'file': 'gtkmain.c',
              'fileline': '524',
              'function': 'gtk_main'},
             {'address': '0x0808f043',
              'args': 'argc=1, argv=0xbffffb64',
              'depth': '24',
              'file': 'main.c',
              'fileline': '259',
              'function': 'main'},
             {'address': '0x4073c627',
              'args': 'main=0x808ee68 <main>, argc=1,      ubp_av=0xbffffb64, '
                      'init=0x806ec18 <_init>, fini=0x80dc900 <_fini>,      '
                      'rtld_fini=0x4000dcc4 <_dl_fini>, stack_end=0xbffffb5c',
              'depth': '25',
              'file': '../sysdeps/generic/libc-start.c',
              'fileline': '129',
              'function': '__libc_start_main'},
             {'address': '0x407daca9',
              'args': '',
              'depth': '0',
              'dylib': '/lib/i686/libc.so.6',
              'function': '__wait4'},
             {'address': '0x407daca9',
              'args': '',
              'depth': '0',
              'dylib': '/lib/i686/libc.so.6',
              'function': '__wait4'},
             {'address': '0x408566b4',
              'args': '',
              'depth': '1',
              'dylib': '/lib/i686/libc.so.6',
              'function': '__DTOR_END__'},
             {'address': '0x401af6f3',
              'args': 'pid=5467, stat_loc=0xbffff28c, options=0',
              'depth': '2',
              'file': 'wrapsyscall.c',
              'fileline': '172',
              'function': 'waitpid'},
             {'address': '0x4024d456',
              'args': 'signum=11',
              'depth': '3',
              'file': 'gnome-init.c',
              'fileline': '659',
              'function': 'gnome_segv_handle'},
             {'address': '0x401ada85',
              'args': 'signo=11, ctx=       {gs = 7, __gsh = 0, fs = 0, __fsh '
                      '= 0, es = 43, __esh = 0, ds = 43, __dsh = 0, edi = 43, '
                      'esi = 0, ebp = 3221223076, esp = 3221222956, ebx = '
                      '1079807460, edx = 115, ecx = 4294967295, eax = 0, '
                      'trapno = 14, err = 4, eip = 1079777092, cs = 35, __csh '
                      '= 0, eflags = 2163270, esp_at_signal = 3221222956, ss = '
                      '43, __ssh = 0, fpstate = 0xbffff3b0, oldmask = '
                      '2147483648, cr2 = 43}',
              'depth': '4',
              'file': 'signals.c',
              'fileline': '97',
              'function': 'pthread_sighandler'},
             {'depth': '5',
              'function': '<signal handler called>',
              'is_crash': '1'},
             {'address': '0x405c1744',
              'args': '     format=0x414bd676 "K '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®Ã\x81Ã\x9f %1$dK, %3$sK '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®/Ã\x83Ã\x8a", args=0xbffff714',
              'depth': '6',
              'file': 'gstrfuncs.c',
              'fileline': '1076',
              'function': 'g_printf_string_upper_bound'},
             {'address': '0x405c0fd8',
              'args': '     format=0x414bd672 "%2$sK '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®Ã\x81Ã\x9f %1$dK, %3$sK '
                      'Â¹Ã\x99Ã\x80Ã\x8cÃ\x86Â®/Ã\x83Ã\x8a",      '
                      'args1=0xbffff710',
              'depth': '7',
              'file': 'gstrfuncs.c',
              'fileline': '156',
              'function': 'g_strdup_vprintf'}],
  'message': None,
  'nested': []}]

In [8]:
df.iloc[0].description

'Package: Evolution\nPriority: Normal\nVersion: 0.12\nSynopsis: Error by getting mail from pop 3 server\nBugzilla-Product: Evolution\nBugzilla-Component: Mailer\n\nDescription:\ncreate three Mailaccounts\nclick on "Verschicken/Empfangen=send/get mail"\n\nyou get mail from 2 accounts but not from the third one \nduring conncting the server the client crashes \n\n\nDebugging Information:\n\n[New Thread 1024 (LWP 783)]\n[New Thread 2049 (LWP 946)]\n[New Thread 1026 (LWP 947)]\n[New Thread 2051 (LWP 948)]\n[New Thread 4100 (LWP 953)]\n[New Thread 12293 (LWP 1454)]\n0xedbb32c in wait4 () from /lib/libc.so.6\n#0  0xedbb32c in wait4 () from /lib/libc.so.6\n#1  0xedbb2e0 in waitpid () from /lib/libc.so.6\n#2  0xf3ace24 in waitpid () from /lib/libpthread.so.0\n#3  0xfb80878 in gnome_segv_handle (signum=11) at gnome-init.c:659\n#4  0x10057490 in segv_redirect (sig=11) at main.c:67\n#5  0xf3aa09c in pthread_sighandler () from /lib/libpthread.so.0\n#6  <signal handler called>\n#7  0xf7d0900 in gtk_progress_set_percentage (progress=0x1022c1e8, \n    percentage=0) at gtkprogress.c:517\n#8  0xf7d08b4 in gtk_progress_set_percentage (progress=0x10200640, \n    percentage=0) at gtkprogress.c:515\n#9  0xf603fe8 in g_timeout_dispatch (source_data=0x80000000, \n    dispatch_time=0x43300000, user_data=0x10200640) at gmain.c:1302\n#10 0xf602d34 in g_main_dispatch (dispatch_time=0x7ffff588) at gmain.c:656\n#11 0xf6033a0 in g_main_iterate (block=269239776, dispatch=1) at gmain.c:877\n#12 0xf6035e4 in g_main_run (loop=0x100e7c80) at gmain.c:935\n#13 0xf7a9358 in gtk_main () at gtkmain.c:524\n#14 0xf1d6678 in bonobo_main () at bonobo-main.c:283\n#15 0x10057644 in main (argc=5, argv=0x7ffff7bc) at main.c:140\n#16 0xed30a08 in __libc_start_main () from /lib/libc.so.6\n#0  0xedbb32c in wait4 () from /lib/libc.so.6\nNo symbol table info available.\n#1  0xedbb2e0 in waitpid () from /lib/libc.so.6\nNo symbol table info available.\n#2  0xf3ace24 in waitpid () from /lib/libpthread.so.0\nNo symbol table info available.\n#3  0xfb80878 in gnome_segv_handle (signum=11) at gnome-init.c:659\nestatus = -725508609\nin_segv = 1\npid = 512\n#4  0x10057490 in segv_redirect (sig=11) at main.c:67\nNo locals.\n#5  0xf3aa09c in pthread_sighandler () from /lib/libpthread.so.0\nNo symbol table info available.\n#6  <signal handler called>\nNo symbol table info available.\n#7  0xf7d0900 in gtk_progress_set_percentage (progress=0x1022c1e8, \n    percentage=0) at gtkprogress.c:517\nNo locals.\n\n\nUnknown reporter: JDroste@neptunswelt.de, changed to bugbuddy-import@ximian.com.\n\n'

In [9]:
# Find how many days there is in the dataset by creation_ts
df['creation_date'] = pd.to_datetime(df['creation_ts'], unit='s')
# Find interval between the first and last date
interval = df['creation_date'].max() - df['creation_date'].min()
print(interval)

15220 days 03:19:00

In [13]:
df['creation_date']

0        1970-04-30 15:42:00
1        1980-01-04 00:50:00
2        1980-02-25 03:49:00
3        1981-12-17 19:53:00
4        1982-02-04 16:18:00
                 ...
218155   2011-12-30 16:56:00
218156   2011-12-30 18:02:00
218157   2011-12-31 13:27:00
218158   2011-12-31 17:43:00
218159   2011-12-31 19:01:00
Name: creation_date, Length: 218160, dtype: datetime64[ns]

In [14]:
# ts to date
x = 10338120
pd.to_datetime(x, unit='s')

Timestamp('1970-04-30 15:42:00')

In [15]:
df[df["dup_id"].notna()]

,bug_id,bug_severity,bug_status,comments,component,creation_ts,delta_ts,description,dup_id,exception,...,priority,product,rep_platform,resolution,short_desc,target_milestone,version,stacktrace,original_bug_id,creation_date
2,61865,normal,RESOLVED,[],Mozilla interaction,320298540,1103752024,Package: galeon\nSeverity: major\nVersion: 1.2...,61865.0,NaN,...,Normal,galeon,Other,DUPLICATE,error visiting web site www.wanadoo.es,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",102081.0,1980-02-25 03:49:00
14,61331,normal,RESOLVED,[],general,883670100,1103752024,Package: gnome-applets\nSeverity: normal\nVers...,61331.0,NaN,...,Normal,gnome-applets,Other,DUPLICATE,please see that report,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",71455.0,1998-01-01 15:55:00
17,5338,normal,RESOLVED,[],general,892009380,1103752024,Package: control-center\nSeverity: normal\nVer...,5338.0,NaN,...,Normal,gnome-control-center,Other,DUPLICATE,,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",57243.0,1998-04-08 04:23:00
23,101918,normal,RESOLVED,[],panel,915170760,1103752024,Package: gnome-panel\nSeverity: blocker\nVersi...,59756.0,NaN,...,Normal,gnome-panel,Other,DUPLICATE,didnt give much info to me about why...,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",NaN,1999-01-01 06:06:00
88,61352,normal,RESOLVED,[],Other Preferences,946686060,1103752024,Package: control-center\nSeverity: normal\nVer...,61352.0,NaN,...,Normal,gnome-control-center,Other,DUPLICATE,"Cannot alter appearance widget, it never opens",---,unspecified,"[{'exception': None, 'message': None, 'frames'...",64135.0,2000-01-01 00:21:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218087,665979,major,RESOLVED,[],general,1323663600,1379034327,I'm running last weeks git/master. I just di...,664639.0,NaN,...,Normal,evolution,Other,DUPLICATE,[regression] evolution hangs on exit,---,3.4.x (obsolete),"[{'exception': None, 'message': None, 'frames'...",NaN,2011-12-12 04:20:00
218093,666022,critical,RESOLVED,[],BugBuddyBugs,1323719340,1323741381,Version: 2.32.1\n\nWhat were you doing when th...,428761.0,NaN,...,Normal,gnome-games-superseded,Other,DUPLICATE,crash in Sudoku: Starting it with a doubl...,---,2.32.x,"[{'exception': None, 'message': None, 'frames'...",NaN,2011-12-12 19:49:00
218100,666158,critical,RESOLVED,[],Widget: GtkFileChooser,1323860340,1351831012,I run Evolution for a day; I routinely save at...,661773.0,NaN,...,Normal,gtk+,Other,DUPLICATE,crash wrt. filesystem model,---,3.2.x,"[{'exception': None, 'message': None, 'frames'...",NaN,2011-12-14 10:59:00
218104,666203,normal,RESOLVED,[],Sound,1323896700,1326106845,Created attachment 203520\nBacktrace obtained ...,654172.0,NaN,...,Normal,gnome-control-center,Other,DUPLICATE,g-c-c crashed in g_type_instance_get_private()...,---,3.2.x,"[{'exception': None, 'message': None, 'frames'...",NaN,2011-12-14 21:05:00
218105,666216,normal,RESOLVED,[],general,1323911520,1323913479,gnome-contacts from jhbuild crashes when I cli...,658685.0,NaN,...,Normal,gnome-contacts,Other,DUPLICATE,Crashes when trying to add a new contact,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",NaN,2011-12-15 01:12:00

In [16]:
# Filter all datata before 1998/01/02
df2 = df[df['creation_date'] > '1998-01-02']

In [17]:
df.head()

,bug_id,bug_severity,bug_status,comments,component,creation_ts,delta_ts,description,dup_id,exception,...,priority,product,rep_platform,resolution,short_desc,target_milestone,version,stacktrace,original_bug_id,creation_date
0,207026,normal,RESOLVED,[],Mailer,10338120,1002679469,Package: Evolution\nPriority: Normal\nVersion:...,NaN,NaN,...,Normal,evolution,Other,DUPLICATE,Crash: Error by getting mail from pop 3 server,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",212077.0,1970-04-30 15:42:00
1,50439,normal,RESOLVED,[],panel,315795000,1103752024,Package: panel\nSeverity: normal\nVersion: 1...,NaN,NaN,...,Normal,gnome-core,Other,FIXED,on startup,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",NaN,1980-01-04 00:50:00
2,61865,normal,RESOLVED,[],Mozilla interaction,320298540,1103752024,Package: galeon\nSeverity: major\nVersion: 1.2...,61865.0,NaN,...,Normal,galeon,Other,DUPLICATE,error visiting web site www.wanadoo.es,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",102081.0,1980-02-25 03:49:00
3,67104,normal,RESOLVED,[],panel,377466780,1103752024,Package: panel\nSeverity: normal\nVersion: 1.0...,NaN,NaN,...,Normal,gnome-core,Other,FIXED,,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",NaN,1981-12-17 19:53:00
4,70489,normal,RESOLVED,[],panel,381687480,1103752024,Package: panel\nSeverity: normal\nVersion: 1.0...,NaN,NaN,...,Normal,gnome-core,Other,INCOMPLETE,,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",NaN,1982-02-04 16:18:00

In [18]:

interval = df2['creation_date'].max() - df2['creation_date'].min()
print(interval)

5111 days 17:20:00

In [19]:
# Keep format while saving
df2.to_json("/home/mdafifal.mamun/research/S3M/dataset/EMSE_data/gnome_2011/gnome_stacktraces_filtered.json", orient='records', lines=False)

In [13]:
df2.head()

,bug_id,bug_severity,bug_status,comments,component,creation_ts,delta_ts,description,dup_id,exception,...,priority,product,rep_platform,resolution,short_desc,target_milestone,version,stacktrace,original_bug_id,creation_date
20,52468,normal,RESOLVED,[],general,915130200,1103752024,Package: gedit\nSeverity: normal\nVersion: 0...,NaN,NaN,...,Normal,gedit,Other,DUPLICATE,SAVE,---,0.9.0,"[{'exception': None, 'message': None, 'frames'...",67103.0,1998-12-31 18:50:00
21,116625,normal,RESOLVED,[],Bookmarks,915158760,1103752024,Package: galeon\nSeverity: normal\nVersion: 1....,NaN,NaN,...,Normal,galeon,Other,NOTGNOME,errror galeon,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",NaN,1999-01-01 02:46:00
22,114115,normal,RESOLVED,[],general,915165000,1057183512,Package: dia\nSeverity: normal\nVersion: 1.4.0...,NaN,NaN,...,Normal,nautilus,Other,OBSOLETE,about Enlightenment window manager,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",NaN,1999-01-01 04:30:00
23,101918,normal,RESOLVED,[],panel,915170760,1103752024,Package: gnome-panel\nSeverity: blocker\nVersi...,59756.0,NaN,...,Normal,gnome-panel,Other,DUPLICATE,didnt give much info to me about why...,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",NaN,1999-01-01 06:06:00
24,112132,normal,RESOLVED,[],gtcd,915252600,1103752024,Package: gtcd\nSeverity: normal\nVersion: 1.0....,NaN,NaN,...,Normal,gnome-media,Other,WONTFIX,,---,unspecified,"[{'exception': None, 'message': None, 'frames'...",NaN,1999-01-02 04:50:00

In [14]:
# Check data types
df2.dtypes

bug_id                       int64
bug_severity                object
bug_status                  object
comments                    object
component                   object
creation_ts                  int64
delta_ts                     int64
description                 object
dup_id                     float64
exception                  float64
keywords                    object
op_sys                      object
priority                    object
product                     object
rep_platform                object
resolution                  object
short_desc                  object
target_milestone            object
version                     object
stacktrace                  object
original_bug_id            float64
creation_date       datetime64[ns]
dtype: object

In [50]:
check_df = pd.read_json("/home/mdafifal.mamun/research/S3M/dataset/EMSE_data/gnome_2011/gnome_stacktraces_filtered.json")

NameError: name 'pd' is not defined

In [34]:
check_df.dtypes

bug_id                int64
bug_severity         object
bug_status           object
comments             object
component            object
creation_ts           int64
delta_ts              int64
description          object
dup_id              float64
exception           float64
keywords             object
op_sys               object
priority             object
product              object
rep_platform         object
resolution           object
short_desc           object
target_milestone     object
version              object
stacktrace           object
original_bug_id     float64
creation_date         int64
dtype: object

In [42]:
# TS to date
x = 883705260
pd.to_datetime(x, unit='s')

Timestamp('1998-01-02 01:41:00')

In [1]:
import json
import os
import sys

sys.path.append("/home/mdafifal.mamun/research/S3M/src")

import matplotlib.pyplot as plt
import torch
from sentence_transformers import (
    SentenceTransformer,
    SentenceTransformerModelCardData,
    SentenceTransformerTrainer,
    SentenceTransformerTrainingArguments,
)
from sentence_transformers.evaluation import (
    EmbeddingSimilarityEvaluator,
    TripletEvaluator,
)
from sentence_transformers.losses import MultipleNegativesRankingLoss
from sentence_transformers.training_args import BatchSamplers
from sklearn.manifold import TSNE
from tqdm import tqdm

from data.buckets.bucket_data import BucketData, OtherBucketData
from data.buckets.issues_data import BucketDataset
from data.triplet_selector import RandomTripletSelector
from datasets import Dataset
from preprocess.entry_coders import Stack2Seq
from preprocess.seq_coder import SeqCoder
from preprocess.tokenizers import SimpleTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

model = SentenceTransformer("BAAI/bge-base-en")
print(f"Model sequence length: {model.max_seq_length}")

# Find model size in CUDA
print(f"Model size: {torch.cuda.memory_allocated() / 1024 ** 3:.2f} GB")


dataset_key = "gnome_pretrain"
run_name = "bge-base-gnome"
generate_dataset = True
batch_size = 16
eval_size = 1000
num_frames = 20
num_train_pairs = 1
num_test_pairs = 1
# trim_length = 0
frame_freq = {}

# Print all training parameters
print("Train pair:", num_train_pairs, "Test pair:", num_test_pairs)

print("Load bucket data...")
bucket_data = OtherBucketData(
    "gnome",
    "/home/mdafifal.mamun/research/S3M/dataset/EMSE_data/gnome_2011/gnome_stacktraces_filtered.json",
    3850,
    700,
    350,
    140,
    is_cpp=True
)
bucket_data.load()
stack_loader = bucket_data.stack_loader()
data_gen = BucketDataset(bucket_data)
unsup_stacks = data_gen.train_stacks()

/home/mdafifal.mamun/miniconda3/envs/tracesim/lib/python3.8/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

Using device: cuda
Model sequence length: 512
Model size: 0.41 GB
Train pair: 1 Test pair: 1
Load bucket data...

In [2]:

def format_stack(stack, from_top=False):
    # Remove duplicate frames
    stack = list(dict.fromkeys(stack))
    stack = [frame for frame in stack if frame != "none"]
    if num_frames > 0:
        if from_top:
            stack = stack[:num_frames]
        else:
            stack = stack[-num_frames:]

    return "\n".join([f"{i+1}: {frame}" for i, frame in enumerate(stack)])


def get_data_row(
    coder, event, similar_stack_id, dissimilar_stack_id, add_to_freq=False
):
    anchor_frames = coder(event.st_id, transformer=True)
    positive_frames = coder(similar_stack_id, transformer=True)
    negative_frames = coder(dissimilar_stack_id, transformer=True)

    if add_to_freq:
        for frames in [anchor_frames, positive_frames, negative_frames]:
            for frame in frames:
                frame_freq[frame] = frame_freq.get(frame, 0) + 1

    return {
        "anchor": format_stack(anchor_frames),
        "positive": format_stack(positive_frames),
        "negative": format_stack(negative_frames),
    }


def generate_dataset_for_train_test(
    bucket_name, dataset_path, num_train_pairs, num_test_pairs, trim_length
):
    triplet_selector_train = RandomTripletSelector(num_train_pairs)
    triplet_selector_eval = RandomTripletSelector(num_test_pairs)
    data_gen.reset()

    stack2seq = Stack2Seq(cased=False, trim_len=trim_length, sep=".")

    coder = SeqCoder(
        stack_loader, stack2seq, SimpleTokenizer(), min_freq=0, max_len=None
    )

    coder.fit(unsup_stacks)

    train_data = []
    test_data = []

    print("Generate the dataset...")
    # for i, event in tqdm(enumerate(data_gen.train()), desc="Step"):
    #     similar_stack_ids, dissimilar_stack_ids = triplet_selector_train(event)
    #     for similar_stack_id, dissimilar_stack_id in zip(
    #         similar_stack_ids, dissimilar_stack_ids
    #     ):
    #         train_data.append(
    #             get_data_row(
    #                 coder,
    #                 event,
    #                 similar_stack_id,
    #                 dissimilar_stack_id,
    #                 add_to_freq=False,
    #             )
    #         )

    for i, event in tqdm(enumerate(data_gen.test()), desc="Step"):
        similar_stack_ids, dissimilar_stack_ids = triplet_selector_eval(event)
        for similar_stack_id, dissimilar_stack_id in zip(
            similar_stack_ids, dissimilar_stack_ids
        ):
            test_data.append(
                get_data_row(coder, event, similar_stack_id, dissimilar_stack_id)
            )

    return train_data, test_data


nb_train, nb_test = generate_dataset_for_train_test(
    "gnome",
    "/home/mdafifal.mamun/research/S3M/dataset/EMSE_data/gnome_2011/gnome_stacktraces_filtered.json",
    num_train_pairs,
    num_test_pairs,
    0,
)

Generate the dataset...

Step: 3097it [00:18, 163.67it/s]

In [3]:
from pprint import pprint

In [61]:
# Print positive and anchor side by side
import random
index = random.randint(0, len(nb_test) - 1)
print("Reading index:", index)
pprint(nb_test[index])

Reading index: 1871
{'anchor': '1: start_thread at libpthread.so.\n'
           '2: g_thread_create_proxy at gthread.c\n'
           '3: open_location_thread at rbshellplayer.c\n'
           '4: totem_pl_parser_parse at totemplparser.c\n'
           '5: totem_pl_parser_parse_with_base at totemplparser.c\n'
           '6: totem_pl_parser_parse_internal at totemplparser.c\n'
           '7: my_g_file_info_get_mime_type_with_data at totemplparser.c\n'
           '8: g_file_read at gfile.c\n'
           '9: g_daemon_file_read at gdaemonfile.c\n'
           '10: do_sync_path_call at gdaemonfile.c\n'
           '11: g_vfs_daemon_call_sync at gvfsdaemondbus.c\n'
           '12: dbus_connection_send_with_reply_and_block at dbusconnection.c\n'
           '13: dbus_pending_call_block at dbuspendingcall.c\n'
           '14: dbus_connection_block_pending_call at dbusconnection.c\n'
           '15: dbus_connection_do_iteration_unlocked at dbusconnection.c\n'
           '16: dbus_transport_do_iteration at dbustransport.c\n'
           '17: socket_do_iteration at dbustransportsocket.c\n'
           '18: dbus_poll at dbussysdepsunix.c\n'
           '19: poll at libc.so.\n'
           '20: kernel_vsyscall',
 'negative': '1: clone at clone.s\n'
             '2: start_thread at pthreadcreate.c\n'
             '3: g_thread_create_proxy at gthread.c\n'
             '4: ia_g_async_queue_pop at gasyncqueue.c\n'
             '5: g_async_queue_pop_intern_unlocked at gasyncqueue.c\n'
             '6: pthread_cond_wait at pthreadcondwait.s\n'
             '7: dl_sysinfo_int at ldlinux.so.',
 'positive': '1: clone at clone.s\n'
             '2: start_thread at pthreadcreate.c\n'
             '3: g_thread_create_proxy at gthread.c\n'
             '4: action_thread_main at rhythmdb.c\n'
             '5: ia_g_async_queue_pop at gasyncqueue.c\n'
             '6: g_async_queue_pop_intern_unlocked at gasyncqueue.c\n'
             '7: pthread_cond_wait at pthreadcondwait.s'}

In [32]:
test_dataset = Dataset.load_from_disk(f"datasets/gnome_pretrain_eval")

In [35]:
pprint(test_dataset[0])

{'anchor': '1: main at main.c\n'
           '2: ia_gtk_main at gtkmain.c\n'
           '3: ia_g_main_loop_run at gmain.c\n'
           '4: g_main_context_iterate at gmain.c\n'
           '5: ia_g_main_context_dispatch at gmain.c\n'
           '6: g_main_dispatch at gmain.c\n'
           '7: g_idle_dispatch at gmain.c\n'
           '8: panel_applet_load_idle_handler at applet.c\n'
           '9: panel_menu_bar_load_from_gconf at panelmenubar.c\n'
           '10: panel_menu_bar_load at panelmenubar.c\n'
           '11: ia_g_object_new at gobject.c\n'
           '12: ia_g_object_new_valist at gobject.c\n'
           '13: ia_g_object_newv at gobject.c\n'
           '14: g_object_constructor at gobject.c\n'
           '15: ia_g_type_create_instance at gtype.c\n'
           '16: panel_menu_bar_init at panelmenubar.c\n'
           '17: panel_place_menu_item_new at panelmenuitems.c\n'
           '18: panel_place_menu_item_init at panelmenuitems.c\n'
           '19: ia_g_volume_monitor_get at gunionvolumemonitor.c\n'
           '20: populate_union_monitor at gunionvolumemonitor.c\n'
           '21: dbus_message_iter_next at libdbus.so.\n'
           '22: signal handler called\n'
           '23: ia_g_spawn_command_line_sync at gspawn.c\n'
           '24: ia_g_spawn_sync at gspawn.c\n'
           '25: waitpid_nocancel at libpthread.so.\n'
           '26: kernel_vsyscall',
 'negative': '1: kernel_vsyscall\n'
             '2: main at nautilusmain.c\n'
             '3: ia_gtk_main at gtkmain.c\n'
             '4: ia_g_main_loop_run at gmain.c\n'
             '5: g_main_context_iterate at gmain.c\n'
             '6: ia_g_main_context_dispatch at gmain.c\n'
             '7: gdk_event_dispatch at gdkeventsx.c\n'
             '8: ia_gtk_main_do_event at gtkmain.c\n'
             '9: gtk_widget_event_internal at gtkwidget.c\n'
             '10: ia_g_signal_emit at gsignal.c\n'
             '11: ia_g_signal_emit_valist at gsignal.c\n'
             '12: signal_emit_unlocked_r at gsignal.c\n'
             '13: ia_g_closure_invoke at gclosure.c\n'
             '14: gtk_marshal_boolean_boxed at gtkmarshalers.c\n'
             '15: nautilus_window_delete_event_callback at '
             'nautilusapplication.c\n'
             '16: ia_gtk_object_destroy at gtkobject.c\n'
             '17: ia_g_object_run_dispose at gobject.c\n'
             '18: gtk_window_dispose at gtkwindow.c\n'
             '19: gtk_widget_dispose at gtkwidget.c\n'
             '20: gtk_object_dispose at gtkobject.c\n'
             '21: g_type_class_meta_marshal at gclosure.c\n'
             '22: ia_g_cclosure_marshal_void_void at gmarshal.c\n'
             '23: gtk_window_destroy at gtkwindow.c\n'
             '24: gtk_container_destroy at gtkcontainer.c\n'
             '25: ia_gtk_container_foreach at gtkcontainer.c\n'
             '26: gtk_bin_forall at gtkbin.c\n'
             '27: gtk_table_forall at gtktable.c\n'
             '28: gtk_paned_forall at gtkpaned.c\n'
             '29: gtk_box_forall at gtkbox.c\n'
             '30: gtk_notebook_destroy at gtknotebook.c\n'
             '31: gtk_notebook_forall at gtknotebook.c\n'
             '32: fm_tree_view_dispose at fmtreeview.c\n'
             '33: gtk_scrolled_window_destroy at gtkscrolledwindow.c\n'
             '34: gtk_scrolled_window_forall at gtkscrolledwindow.c\n'
             '35: gtk_tree_view_destroy at gtktreeview.c\n'
             '36: gtk_tree_view_unref_and_check_selection_tree at '
             'gtktreeview.c\n'
             '37: gtk_tree_view_unref_tree_helper at gtktreeview.c\n'
             '38: ia_gtk_tree_model_unref_node at gtktreemodel.c\n'
             '39: gtk_tree_model_sort_real_unref_node at gtktreemodelsort.c\n'
             '40: fm_tree_model_unref_node at fmtreemodel.c\n'
             '41: ia_g_assertion_message_expr at gtestutils.c\n'
             '42: ia_g_assertion_message\n'
             '43: abort at libc.so.\n'
             '44: raise at libc.so.\n'
             '45: signal handler called\n'
             '46: ia_g_spawn_command_line_sync at gspawn.c\n'
             '47: ia_g_spawn_sync at gspawn.c\n'
             '48: waitpid at libpthread.so.',
 'positive': '1: main at main.c\n'
             '2: ia_gtk_main at gtkmain.c\n'
             '3: ia_g_main_loop_run at gmain.c\n'
             '4: g_main_context_iterate at gmain.c\n'
             '5: ia_g_main_context_dispatch at gmain.c\n'
             '6: g_main_dispatch at gmain.c\n'
             '7: g_idle_dispatch at gmain.c\n'
             '8: panel_applet_load_idle_handler at applet.c\n'
             '9: panel_menu_bar_load_from_gconf at panelmenubar.c\n'
             '10: panel_menu_bar_load at panelmenubar.c\n'
             '11: ia_g_object_new at gobject.c\n'
             '12: ia_g_object_new_valist at gobject.c\n'
             '13: ia_g_object_newv at gobject.c\n'
             '14: g_object_constructor at gobject.c\n'
             '15: ia_g_type_create_instance at gtype.c\n'
             '16: panel_menu_bar_init at panelmenubar.c\n'
             '17: panel_place_menu_item_new at panelmenuitems.c\n'
             '18: panel_place_menu_item_init at panelmenuitems.c\n'
             '19: ia_g_volume_monitor_get at gunionvolumemonitor.c\n'
             '20: populate_union_monitor at gunionvolumemonitor.c\n'
             '21: dbus_message_iter_next at libdbus.so.\n'
             '22: signal handler called\n'
             '23: ia_g_spawn_command_line_sync at gspawn.c\n'
             '24: ia_g_spawn_sync at gspawn.c\n'
             '25: waitpid_nocancel at libpthread.so.\n'
             '26: kernel_vsyscall'}